ACSL Flightstack-winged Documentation: _qrbp_::_pid_::pid Class Reference
_qrbp_::_pid_::pid Class Reference
PID class.
#include <PID.hpp>
Public Member Functions
pid (flight_params *p, const std::string &controller_log_dir_)
~pid ()
void run (const double time_step_rk4_)
Implementing functions from controller_base.
void update (double time, double x, double y, double z, double vx, double vy, double vz, double q0, double q1, double q2, double q3, double roll, double pitch, double yaw, double w_x, double w_y, double w_z)
float get_t1 () const
float get_t2 () const
float get_t3 () const
float get_t4 () const
float get_t5 () const
float get_t6 () const
float get_t7 () const
float get_t8 () const
Public Member Functions inherited from _control_algorithm_base_::controller_base
controller_base (flight_params *p)
~controller_base ()
void read_params ([[maybe_unused]] const std::string &jsonFile)
Read parameters.
void init ()
Initialize initial conditions.
void update ([[maybe_unused]] double time, [[maybe_unused]] double x, [[maybe_unused]] double y, [[maybe_unused]] double z, [[maybe_unused]] double vx, [[maybe_unused]] double vy, [[maybe_unused]] double vz, [[maybe_unused]] double q0, [[maybe_unused]] double q1, [[maybe_unused]] double q2, [[maybe_unused]] double q3, [[maybe_unused]] double roll, [[maybe_unused]] double pitch, [[maybe_unused]] double yaw, [[maybe_unused]] double w_x, [[maybe_unused]] double w_y, [[maybe_unused]] double w_z)
Controller Update state and trajectory.
void run ([[maybe_unused]] const double time_step_rk4_)
Controller run.
float get_t1 () const
float get_t2 () const
float get_t3 () const
float get_t4 () const
float get_t5 () const
float get_t6 () const
float get_t7 () const
float get_t8 () const
Private Member Functions
void read_params (const std::string &jsonFile)
void init ()
void model (const rk4_array< double, NSI > &y, rk4_array< double, NSI > &dy, double t)
Define the model.
void compute_translational_control_in_I ()
Function to compute the translational control in the inertial frame.
void compute_u1_eta_d ()
Function to compute the thrust (u1) and the desired angles.
void compute_rotational_control ()
Function to compute the rotational control input.
void compute_normalized_thrusts ()
Function to compute the normalized thrust.
void assign_from_rk4 ()
Assign the values from rk4 to controller internal members.
void debug2terminal ()
Function to print to terminal.
Private Attributes
piecewise_polynomial_trajectory ud
pid_logger logger
rk4_array< double, NSI > y
rk4_array< double, NSI > dy
rk4_array< double, NSI > zeros
boost::numeric::odeint::runge_kutta4< rk4_array< double, NSI > > rk4
controller_internal_parameters cip
controller_internal_members cim
controller_integrated_state_members csm
Additional Inherited Members
Protected Attributes inherited from _control_algorithm_base_::controller_base
Eigen::Vector< float, 8 > control_input
flight_params * flight_params_ptr
Detailed Description
PID class.
Definition at line 78 of file PID.hpp.
Constructor & Destructor Documentation
pid()
_qrbp_::_pid_::pid::pid (flight_params * p, const std::string & controller_log_dir_)
Definition at line 67 of file PID.cpp.
References init(), and read_params().
~pid()
_qrbp_::_pid_::pid::~pid ()
Definition at line 78 of file PID.cpp.
Member Function Documentation
assign_from_rk4()
void _qrbp_::_pid_::pid::assign_from_rk4 () private
Assign the values from rk4 to controller internal members.
Parameters
None
Definition at line 183 of file PID.cpp.
References _utilities_::assignElementsToMembers(), csm, _qrbp_::_pid_::controller_integrated_state_members::e_eta_I, _qrbp_::_pid_::controller_integrated_state_members::e_tran_pos_I, _qrbp_::_pid_::controller_integrated_state_members::state_pitch_d_filter, _qrbp_::_pid_::controller_integrated_state_members::state_pitch_dot_d_filter, _qrbp_::_pid_::controller_integrated_state_members::state_roll_d_filter, _qrbp_::_pid_::controller_integrated_state_members::state_roll_dot_d_filter, and y.
Referenced by update().
compute_normalized_thrusts()
void _qrbp_::_pid_::pid::compute_normalized_thrusts () private
Function to compute the normalized thrust.
Parameters
None
Definition at line 291 of file PID.cpp.
References cim, _control_algorithm_base_::controller_base::control_input, _utilities_::evaluatePolynomial(), _qrbp_::MAX_THRUST, _qrbp_::MIN_THRUST, _qrbp_::mixer_matrix_qrbp, _qrbp_::_pid_::controller_internal_members::Sat_Thrust, _qrbp_::_pid_::controller_internal_members::Thrust, _qrbp_::thrust_polynomial_coeff_qrbp, and _qrbp_::_pid_::controller_internal_members::u.
Referenced by run().
compute_rotational_control()
void _qrbp_::_pid_::pid::compute_rotational_control () private
Function to compute the rotational control input.
Parameters
None
Definition at line 265 of file PID.cpp.
References cim, cip, csm, _qrbp_::_pid_::controller_internal_members::e_eta, _qrbp_::_pid_::controller_integrated_state_members::e_eta_I, _qrbp_::_pid_::controller_internal_members::e_eta_rate, _qrbp_::_pid_::controller_internal_members::eta_rot, _qrbp_::_pid_::controller_internal_members::eta_rot_acceleration_d, _qrbp_::_pid_::controller_internal_members::eta_rot_d, _qrbp_::_pid_::controller_internal_members::eta_rot_rate, _qrbp_::_pid_::controller_internal_members::eta_rot_rate_d, _qrbp_::inertia_matrix_q, _qrbp_::_pid_::controller_internal_parameters::Kd_rot, _qrbp_::_pid_::controller_internal_parameters::Ki_rot, _qrbp_::_pid_::controller_internal_parameters::Kp_rot, _qrbp_::_pid_::controller_internal_members::omega_rot, _qrbp_::_pid_::controller_internal_members::tau_rot, _qrbp_::_pid_::controller_internal_members::tau_rot_baseline, and _qrbp_::_pid_::controller_internal_members::u.
Referenced by run().
compute_translational_control_in_I()
void _qrbp_::_pid_::pid::compute_translational_control_in_I () private
Function to compute the translational control in the inertial frame.
Parameters
None
Definition at line 208 of file PID.cpp.
References cim, cip, csm, _qrbp_::e3_basis, _qrbp_::_pid_::controller_internal_members::e_tran_pos, _qrbp_::_pid_::controller_integrated_state_members::e_tran_pos_I, _qrbp_::_pid_::controller_internal_members::e_tran_vel, _qrbp_::G, _qrbp_::_pid_::controller_internal_parameters::Kd_tran, _qrbp_::_pid_::controller_internal_parameters::Ki_tran, _qrbp_::_pid_::controller_internal_parameters::Kp_tran, _qrbp_::MASS, _qrbp_::_pid_::controller_internal_members::mu_tran_baseline, _qrbp_::_pid_::controller_internal_members::mu_tran_I, _qrbp_::_pid_::controller_internal_members::r_ddot_user, _qrbp_::_pid_::controller_internal_members::r_dot_user, _qrbp_::_pid_::controller_internal_members::r_user, _qrbp_::_pid_::controller_internal_members::x_tran_pos, and _qrbp_::_pid_::controller_internal_members::x_tran_vel.
Referenced by run().
compute_u1_eta_d()
void _qrbp_::_pid_::pid::compute_u1_eta_d () private
Function to compute the thrust (u1) and the desired angles.
Parameters
None
Definition at line 224 of file PID.cpp.
References _qrbp_::A_filter_pitch_dot_ref, _qrbp_::A_filter_pitch_ref, _qrbp_::A_filter_roll_dot_ref, _qrbp_::A_filter_roll_ref, _qrbp_::B_filter_pitch_dot_ref, _qrbp_::B_filter_pitch_ref, _qrbp_::B_filter_roll_dot_ref, _qrbp_::B_filter_roll_ref, _qrbp_::C_filter_pitch_dot_ref, _qrbp_::C_filter_pitch_ref, _qrbp_::C_filter_roll_dot_ref, _qrbp_::C_filter_roll_ref, cim, csm, _qrbp_::_pid_::controller_internal_members::eta_rot_acceleration_d, _qrbp_::_pid_::controller_internal_members::eta_rot_d, _qrbp_::_pid_::controller_internal_members::eta_rot_rate_d, _qrbp_::_pid_::controller_internal_members::internal_state_pitch_d_filter, _qrbp_::_pid_::controller_internal_members::internal_state_pitch_dot_d_filter, _qrbp_::_pid_::controller_internal_members::internal_state_roll_d_filter, _qrbp_::_pid_::controller_internal_members::internal_state_roll_dot_d_filter, _qrbp_::_pid_::controller_internal_members::mu_tran_I, _qrbp_::_pid_::controller_internal_members::mu_tran_J, _qrbp_::_pid_::controller_internal_members::R_I_J, _qrbp_::_pid_::controller_integrated_state_members::state_pitch_d_filter, _qrbp_::_pid_::controller_integrated_state_members::state_pitch_dot_d_filter, _qrbp_::_pid_::controller_integrated_state_members::state_roll_d_filter, _qrbp_::_pid_::controller_integrated_state_members::state_roll_dot_d_filter, and _qrbp_::_pid_::controller_internal_members::u.
Referenced by run().
debug2terminal()
void _qrbp_::_pid_::pid::debug2terminal () private
Function to print to terminal.
Parameters
None
Definition at line 306 of file PID.cpp.
Referenced by run().
get_t1()
float _qrbp_::_pid_::pid::get_t1 () const
Definition at line 347 of file PID.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t2()
float _qrbp_::_pid_::pid::get_t2 () const
Definition at line 351 of file PID.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t3()
float _qrbp_::_pid_::pid::get_t3 () const
Definition at line 355 of file PID.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t4()
float _qrbp_::_pid_::pid::get_t4 () const
Definition at line 359 of file PID.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t5()
float _qrbp_::_pid_::pid::get_t5 () const
Definition at line 363 of file PID.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t6()
float _qrbp_::_pid_::pid::get_t6 () const
Definition at line 367 of file PID.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t7()
float _qrbp_::_pid_::pid::get_t7 () const
Definition at line 371 of file PID.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t8()
float _qrbp_::_pid_::pid::get_t8 () const
Definition at line 375 of file PID.cpp.
References _control_algorithm_base_::controller_base::control_input.
init()
void _qrbp_::_pid_::pid::init () private
Definition at line 101 of file PID.cpp.
References dy, _qrbp_::is_biplane, _qrbp_::momentary_button, y, and zeros.
Referenced by pid().
model()
void _qrbp_::_pid_::pid::model (const rk4_array< double, NSI > & y, rk4_array< double, NSI > & dy, double t) private
Define the model.
Parameters
y
dy
t
Referenced by run().
read_params()
void _qrbp_::_pid_::pid::read_params (const std::string & jsonFile) private
Definition at line 83 of file PID.cpp.
References cip, file(), _qrbp_::_pid_::controller_internal_parameters::Kd_rot, _qrbp_::_pid_::controller_internal_parameters::Kd_tran, _qrbp_::_pid_::controller_internal_parameters::Ki_rot, _qrbp_::_pid_::controller_internal_parameters::Ki_tran, _qrbp_::_pid_::controller_internal_parameters::Kp_rot, and _qrbp_::_pid_::controller_internal_parameters::Kp_tran.
Referenced by pid().
run()
void _qrbp_::_pid_::pid::run (const double time_step_rk4_)
Implementing functions from controller_base.
Parameters
time_step_rk4_
Definition at line 311 of file PID.cpp.
References _qrbp_::_pid_::controller_internal_members::alg_duration, _qrbp_::_pid_::controller_internal_members::alg_end_time, _qrbp_::_pid_::controller_internal_members::alg_start_time, cim, compute_normalized_thrusts(), compute_rotational_control(), compute_translational_control_in_I(), compute_u1_eta_d(), debug2terminal(), logger, _qrbp_::_pid_::pid_logger::logLogData(), model(), rk4, _qrbp_::_pid_::controller_internal_members::t, and y.
update()
void _qrbp_::_pid_::pid::update (double time, double x, double y, double z, double vx, double vy, double vz, double q0, double q1, double q2, double q3, double roll, double pitch, double yaw, double w_x, double w_y, double w_z)
Definition at line 116 of file PID.cpp.
References _qrbp_::_pid_::controller_internal_members::alg_start_time, assign_from_rk4(), cim, _qrbp_::_pid_::controller_internal_members::eta_rot, _qrbp_::_pid_::controller_internal_members::eta_rot_acceleration_d, _qrbp_::_pid_::controller_internal_members::eta_rot_d, _qrbp_::_pid_::controller_internal_members::eta_rot_rate, _qrbp_::_pid_::controller_internal_members::eta_rot_rate_d, _user_defined_trajectory_base_::trajectory_base::getUserDefinedAcceleration(), _user_defined_trajectory_base_::trajectory_base::getUserDefinedPosition(), _user_defined_trajectory_base_::trajectory_base::getUserDefinedVelocity(), _user_defined_trajectory_base_::trajectory_base::getUserDefinedYaw(), _user_defined_trajectory_base_::trajectory_base::getUserDefinedYawRate(), _user_defined_trajectory_base_::trajectory_base::getUserDefinedYawRateDot(), _qrbp_::_pid_::controller_internal_members::Jacobian_inv, _utilities_::jacobianMatrixInverse(), _qrbp_::_pid_::controller_internal_members::omega_rot, _qrbp_::_pid_::controller_internal_members::q, _qrbp_::_pid_::controller_internal_members::r_ddot_user, _qrbp_::_pid_::controller_internal_members::r_dot_user, _qrbp_::_pid_::controller_internal_members::R_I_J, _qrbp_::_pid_::controller_internal_members::R_J_I, _qrbp_::_pid_::controller_internal_members::r_user, _utilities_::rotationMatrix321GlobalToLocal(), _utilities_::rotationMatrix321LocalToGlobal(), _qrbp_::_pid_::controller_internal_members::t, ud, _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::updateUserDefinedTrajectory(), _qrbp_::_pid_::controller_internal_members::x_tran_pos, _qrbp_::_pid_::controller_internal_members::x_tran_vel, and y.
Member Data Documentation
cim
controller_internal_members _qrbp_::_pid_::pid::cim private
Definition at line 158 of file PID.hpp.
Referenced by compute_normalized_thrusts(), compute_rotational_control(), compute_translational_control_in_I(), compute_u1_eta_d(), run(), and update().
cip
controller_internal_parameters _qrbp_::_pid_::pid::cip private
Definition at line 155 of file PID.hpp.
Referenced by compute_rotational_control(), compute_translational_control_in_I(), and read_params().
csm
controller_integrated_state_members _qrbp_::_pid_::pid::csm private
Definition at line 161 of file PID.hpp.
Referenced by assign_from_rk4(), compute_rotational_control(), compute_translational_control_in_I(), and compute_u1_eta_d().
dy
rk4_array<double, NSI> _qrbp_::_pid_::pid::dy private
Definition at line 136 of file PID.hpp.
Referenced by init().
logger
pid_logger _qrbp_::_pid_::pid::logger private
Definition at line 131 of file PID.hpp.
Referenced by run().
rk4
boost::numeric::odeint::runge_kutta4<rk4_array<double, NSI> > _qrbp_::_pid_::pid::rk4 private
Definition at line 152 of file PID.hpp.
Referenced by run().
ud
piecewise_polynomial_trajectory _qrbp_::_pid_::pid::ud private
Definition at line 128 of file PID.hpp.
Referenced by update().
y
rk4_array<double, NSI> _qrbp_::_pid_::pid::y private
Definition at line 135 of file PID.hpp.
Referenced by assign_from_rk4(), init(), run(), and update().
zeros
rk4_array<double, NSI> _qrbp_::_pid_::pid::zeros private
Definition at line 139 of file PID.hpp.
Referenced by init().
The documentation for this class was generated from the following files:
ACSL-flightstack-winged/src/acsl_flight/include/control/platforms/qrbp/control_algorithms/PID/PID.hpp
ACSL-flightstack-winged/src/acsl_flight/src/control/platforms/qrbp/control_algorithms/PID/PID.cpp