ACSL Flightstack-winged Documentation: _qrbp_::_mrac_pid_::mrac_pid Class Reference
_qrbp_::_mrac_pid_::mrac_pid Class Reference
#include <MRAC_PID.hpp>
Public Member Functions
mrac_pid (flight_params *p, const std::string &controller_log_dir_)
~mrac_pid ()
void run (const double time_step_rk4_)
Implementing functions from controller_base.
void update (double time, double x, double y, double z, double vx, double vy, double vz, double q0, double q1, double q2, double q3, double roll, double pitch, double yaw, double w_x, double w_y, double w_z)
Implementing functions from controller_base.
float get_t1 () const
float get_t2 () const
float get_t3 () const
float get_t4 () const
float get_t5 () const
float get_t6 () const
float get_t7 () const
float get_t8 () const
Public Member Functions inherited from _control_algorithm_base_::controller_base
controller_base (flight_params *p)
~controller_base ()
void read_params ([[maybe_unused]] const std::string &jsonFile)
Read parameters.
void init ()
Initialize initial conditions.
void update ([[maybe_unused]] double time, [[maybe_unused]] double x, [[maybe_unused]] double y, [[maybe_unused]] double z, [[maybe_unused]] double vx, [[maybe_unused]] double vy, [[maybe_unused]] double vz, [[maybe_unused]] double q0, [[maybe_unused]] double q1, [[maybe_unused]] double q2, [[maybe_unused]] double q3, [[maybe_unused]] double roll, [[maybe_unused]] double pitch, [[maybe_unused]] double yaw, [[maybe_unused]] double w_x, [[maybe_unused]] double w_y, [[maybe_unused]] double w_z)
Controller Update state and trajectory.
void run ([[maybe_unused]] const double time_step_rk4_)
Controller run.
float get_t1 () const
float get_t2 () const
float get_t3 () const
float get_t4 () const
float get_t5 () const
float get_t6 () const
float get_t7 () const
float get_t8 () const
Private Member Functions
void read_params (const std::string &jsonFile)
Implementing functions from controller_base.
void init ()
Init function.
void reset_integrator_states ()
Function to reset the integrator states.
void model (const rk4_array< double, NSI > &y, rk4_array< double, NSI > &dy, double t)
Define the model.
void compute_outer_loop_regressor ()
Function to compute the outer loop regressor vector.
void compute_translational_control_in_I ()
Function to compute the translational control in the inertial frame.
void compute_u1_eta_d ()
Function to compute the thrhust (u1) and the desired angles.
void compute_innner_loop_regressor ()
Function to compute the inner loop regressor vector.
void compute_rotational_control ()
Function to compute the rotational control input.
void compute_normalized_thrusts ()
Function to compute the normalized thrust.
void assign_from_rk4 ()
Assign the values from rk4 to controller internal members.
void debug2terminal ()
Function to print to terminal.
Private Attributes
piecewise_polynomial_trajectory ud
mrac_pid_logger logger
rk4_array< double, NSI > y
rk4_array< double, NSI > dy
rk4_array< double, NSI > zeros
boost::numeric::odeint::runge_kutta4< rk4_array< double, NSI > > rk4
controller_internal_parameters cip
controller_internal_members cim
controller_integrated_state_members csm
Additional Inherited Members
Protected Attributes inherited from _control_algorithm_base_::controller_base
Eigen::Vector< float, 8 > control_input
flight_params * flight_params_ptr
Detailed Description
Definition at line 83 of file MRAC_PID.hpp.
Constructor & Destructor Documentation
mrac_pid()
_qrbp_::_mrac_pid_::mrac_pid::mrac_pid (flight_params * p, const std::string & controller_log_dir_)
Definition at line 68 of file MRAC_PID.cpp.
References init(), and read_params().
~mrac_pid()
_qrbp_::_mrac_pid_::mrac_pid::~mrac_pid ()
Definition at line 79 of file MRAC_PID.cpp.
Member Function Documentation
assign_from_rk4()
void _qrbp_::_mrac_pid_::mrac_pid::assign_from_rk4 () private
Assign the values from rk4 to controller internal members.
Definition at line 341 of file MRAC_PID.cpp.
References _utilities_::assignElementsToMembers(), csm, _qrbp_::_mrac_pid_::controller_integrated_state_members::e_eta_I, _qrbp_::_mrac_pid_::controller_integrated_state_members::e_omega_ref_I, _qrbp_::_mrac_pid_::controller_integrated_state_members::e_tran_pos_I, _qrbp_::_mrac_pid_::controller_integrated_state_members::e_tran_pos_ref_I, _qrbp_::_mrac_pid_::controller_integrated_state_members::K_hat_r_rot, _qrbp_::_mrac_pid_::controller_integrated_state_members::K_hat_r_tran, _qrbp_::_mrac_pid_::controller_integrated_state_members::K_hat_x_rot, _qrbp_::_mrac_pid_::controller_integrated_state_members::K_hat_x_tran, _qrbp_::_mrac_pid_::controller_integrated_state_members::omega_ref_rot, _qrbp_::_mrac_pid_::controller_integrated_state_members::state_pitch_d_filter_b, _qrbp_::_mrac_pid_::controller_integrated_state_members::state_pitch_d_filter_q, _qrbp_::_mrac_pid_::controller_integrated_state_members::state_pitch_dot_d_filter_b, _qrbp_::_mrac_pid_::controller_integrated_state_members::state_pitch_dot_d_filter_q, _qrbp_::_mrac_pid_::controller_integrated_state_members::state_roll_d_filter_q, _qrbp_::_mrac_pid_::controller_integrated_state_members::state_roll_dot_d_filter_q, _qrbp_::_mrac_pid_::controller_integrated_state_members::state_yaw_d_filter_b, _qrbp_::_mrac_pid_::controller_integrated_state_members::state_yaw_dot_d_filter_b, _qrbp_::_mrac_pid_::controller_integrated_state_members::Theta_hat_rot, _qrbp_::_mrac_pid_::controller_integrated_state_members::Theta_hat_tran, _qrbp_::_mrac_pid_::controller_integrated_state_members::x_tran_ref, and y.
Referenced by update().
compute_innner_loop_regressor()
void _qrbp_::_mrac_pid_::mrac_pid::compute_innner_loop_regressor () private
Function to compute the inner loop regressor vector.
Definition at line 442 of file MRAC_PID.cpp.
References _qrbp_::_mrac_pid_::controller_internal_members::aero, _qrbp_::AeroStates::alpha, _qrbp_::AeroStates::beta, cim, _qrbp_::_mrac_pid_::controller_internal_members::inner_loop_regressor, _qrbp_::is_biplane, _qrbp_::_mrac_pid_::controller_internal_members::omega_rot_b, _qrbp_::_mrac_pid_::controller_internal_members::omega_rot_q, _qrbp_::_mrac_pid_::controller_internal_members_aero::states, and _qrbp_::AeroStates::v_norm_sq.
Referenced by run().
compute_normalized_thrusts()
void _qrbp_::_mrac_pid_::mrac_pid::compute_normalized_thrusts () private
Function to compute the normalized thrust.
Definition at line 802 of file MRAC_PID.cpp.
References cim, _control_algorithm_base_::controller_base::control_input, _utilities_::evaluatePolynomial(), _qrbp_::MAX_THRUST, _qrbp_::MIN_THRUST, _qrbp_::mixer_matrix_qrbp, _qrbp_::_mrac_pid_::controller_internal_members::Sat_Thrust, _qrbp_::_mrac_pid_::controller_internal_members::Thrust, _qrbp_::thrust_polynomial_coeff_qrbp, and _qrbp_::_mrac_pid_::controller_internal_members::u.
Referenced by run().
compute_outer_loop_regressor()
void _qrbp_::_mrac_pid_::mrac_pid::compute_outer_loop_regressor () private
Function to compute the outer loop regressor vector.
Definition at line 397 of file MRAC_PID.cpp.
References _qrbp_::_mrac_pid_::controller_internal_members::aero, _qrbp_::AeroStates::alpha, _qrbp_::AeroStates::beta, cim, _qrbp_::_mrac_pid_::controller_internal_members::eta_rot_q, _qrbp_::_mrac_pid_::controller_internal_members::outer_loop_regressor, _qrbp_::_mrac_pid_::controller_internal_members_aero::states, and _qrbp_::AeroStates::v_norm_sq.
Referenced by run().
compute_rotational_control()
void _qrbp_::_mrac_pid_::mrac_pid::compute_rotational_control () private
Function to compute the rotational control input.
Definition at line 642 of file MRAC_PID.cpp.
References _qrbp_::_mrac_pid_::controller_internal_members::aero, _qrbp_::_mrac_pid_::controller_internal_members::augmented_inner_loop_regressor, _qrbp_::_mrac_pid_::controller_internal_parameters::B_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::B_rot_q, cim, cip, csm, _qrbp_::_mrac_pid_::controller_internal_members_aero::dyn, _qrbp_::_mrac_pid_::controller_internal_members::e_eta, _qrbp_::_mrac_pid_::controller_integrated_state_members::e_eta_I, _qrbp_::_mrac_pid_::controller_internal_members::e_eta_rate, _qrbp_::_mrac_pid_::controller_internal_members::e_omega, _qrbp_::_mrac_pid_::controller_internal_members::e_omega_ref, _qrbp_::_mrac_pid_::controller_integrated_state_members::e_omega_ref_I, _qrbp_::_mrac_pid_::controller_internal_members::eta_rot, _qrbp_::_mrac_pid_::controller_internal_members::eta_rot_acceleration_d, _qrbp_::_mrac_pid_::controller_internal_members::eta_rot_d, _qrbp_::_mrac_pid_::controller_internal_members::eta_rot_rate, _qrbp_::_mrac_pid_::controller_internal_members::eta_rot_rate_d, _qrbp_::_mrac_pid_::controller_internal_parameters::Gamma_r_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::Gamma_r_rot_q, _qrbp_::_mrac_pid_::controller_internal_parameters::Gamma_Theta_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::Gamma_Theta_rot_q, _qrbp_::_mrac_pid_::controller_internal_parameters::Gamma_x_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::Gamma_x_rot_q, _qrbp_::_mrac_pid_::controller_internal_parameters::inertia_matrix, _qrbp_::AeroDynamicMembers::inner_loop_dynamic_inv, _qrbp_::_mrac_pid_::controller_internal_members::inner_loop_regressor, _qrbp_::is_biplane, _qrbp_::_mrac_pid_::controller_internal_members::Jacobian, _qrbp_::_mrac_pid_::controller_internal_members::Jacobian_dot, _qrbp_::_mrac_pid_::controller_integrated_state_members::K_hat_r_rot, _qrbp_::_mrac_pid_::controller_internal_members::K_hat_r_rot_dot, _qrbp_::_mrac_pid_::controller_integrated_state_members::K_hat_x_rot, _qrbp_::_mrac_pid_::controller_internal_members::K_hat_x_rot_dot, _qrbp_::_mrac_pid_::controller_internal_parameters::Kd_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::Kd_rot_q, _qrbp_::_mrac_pid_::controller_internal_parameters::Ki_omega_cmd_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::Ki_omega_cmd_rot_q, _qrbp_::_mrac_pid_::controller_internal_parameters::Ki_omega_ref_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::Ki_omega_ref_rot_q, _qrbp_::_mrac_pid_::controller_internal_parameters::Ki_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::Ki_rot_q, _qrbp_::_mrac_pid_::controller_internal_parameters::Kp_omega_cmd_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::Kp_omega_cmd_rot_q, _qrbp_::_mrac_pid_::controller_internal_parameters::Kp_omega_ref_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::Kp_omega_ref_rot_q, _qrbp_::_mrac_pid_::controller_internal_parameters::Kp_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::Kp_rot_q, _qrbp_::_mrac_pid_::controller_internal_members::omega_cmd_dot_rot, _qrbp_::_mrac_pid_::controller_internal_members::omega_cmd_rot, _qrbp_::_mrac_pid_::controller_internal_members::omega_ref_dot_rot, _qrbp_::_mrac_pid_::controller_integrated_state_members::omega_ref_rot, _qrbp_::_mrac_pid_::controller_internal_members::omega_rot, _qrbp_::_mrac_pid_::controller_internal_parameters::P_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::P_rot_q, _qrbp_::_mrac_pid_::controller_internal_members::r_cmd_rot, _qrbp_::R_Jb_Jq, _qrbp_::R_Jq_Jb, _qrbp_::_mrac_pid_::controller_internal_members::tau_rot, _qrbp_::_mrac_pid_::controller_internal_members::tau_rot_adaptive, _qrbp_::_mrac_pid_::controller_internal_members::tau_rot_baseline, _qrbp_::_mrac_pid_::controller_integrated_state_members::Theta_hat_rot, _qrbp_::_mrac_pid_::controller_internal_members::Theta_hat_rot_dot, and _qrbp_::_mrac_pid_::controller_internal_members::u.
Referenced by run().
compute_translational_control_in_I()
void _qrbp_::_mrac_pid_::mrac_pid::compute_translational_control_in_I () private
Function to compute the translational control in the inertial frame.
Definition at line 478 of file MRAC_PID.cpp.
References _qrbp_::_mrac_pid_::controller_internal_parameters::A_ref_tran, _qrbp_::_mrac_pid_::controller_internal_members::aero, _qrbp_::_mrac_pid_::controller_internal_members::augmented_outer_loop_regressor, _qrbp_::_mrac_pid_::controller_internal_parameters::B_ref_tran, _qrbp_::_mrac_pid_::controller_internal_parameters::B_tran, cim, cip, csm, _qrbp_::_mrac_pid_::controller_internal_members_aero::dyn, _qrbp_::e3_basis, _qrbp_::_mrac_pid_::controller_internal_members::e_tran, _qrbp_::_mrac_pid_::controller_internal_members::e_tran_pos, _qrbp_::_mrac_pid_::controller_integrated_state_members::e_tran_pos_I, _qrbp_::_mrac_pid_::controller_internal_members::e_tran_pos_ref, _qrbp_::_mrac_pid_::controller_integrated_state_members::e_tran_pos_ref_I, _qrbp_::_mrac_pid_::controller_internal_members::e_tran_vel, _qrbp_::G, _qrbp_::_mrac_pid_::controller_internal_parameters::Gamma_r_tran, _qrbp_::_mrac_pid_::controller_internal_parameters::Gamma_Theta_tran, _qrbp_::_mrac_pid_::controller_internal_parameters::Gamma_x_tran, _qrbp_::_mrac_pid_::controller_integrated_state_members::K_hat_r_tran, _qrbp_::_mrac_pid_::controller_internal_members::K_hat_r_tran_dot, _qrbp_::_mrac_pid_::controller_integrated_state_members::K_hat_x_tran, _qrbp_::_mrac_pid_::controller_internal_members::K_hat_x_tran_dot, _qrbp_::_mrac_pid_::controller_internal_parameters::Kd_refmod_tran, _qrbp_::_mrac_pid_::controller_internal_parameters::Kd_tran, _qrbp_::_mrac_pid_::controller_internal_parameters::Ki_refmod_tran, _qrbp_::_mrac_pid_::controller_internal_parameters::Ki_tran, _qrbp_::_mrac_pid_::controller_internal_parameters::Kp_refmod_tran, _qrbp_::_mrac_pid_::controller_internal_parameters::Kp_tran, _qrbp_::MASS, _qrbp_::_mrac_pid_::controller_internal_members::mu_tran_adaptive, _qrbp_::_mrac_pid_::controller_internal_members::mu_tran_baseline, _qrbp_::_mrac_pid_::controller_internal_members::mu_tran_I, _qrbp_::AeroDynamicMembers::outer_loop_dynamic_inv, _qrbp_::_mrac_pid_::controller_internal_members::outer_loop_regressor, _qrbp_::_mrac_pid_::controller_internal_parameters::P_tran, _qrbp_::_mrac_pid_::controller_internal_members::r_cmd_tran, _qrbp_::_mrac_pid_::controller_internal_members::r_ddot_user, _qrbp_::_mrac_pid_::controller_internal_members::r_dot_user, _qrbp_::_mrac_pid_::controller_internal_members::r_user, _qrbp_::_mrac_pid_::controller_integrated_state_members::Theta_hat_tran, _qrbp_::_mrac_pid_::controller_internal_members::Theta_hat_tran_dot, _qrbp_::_mrac_pid_::controller_internal_members::x_tran, _qrbp_::_mrac_pid_::controller_integrated_state_members::x_tran_ref, and _qrbp_::_mrac_pid_::controller_internal_members::x_tran_ref_dot.
Referenced by run().
compute_u1_eta_d()
void _qrbp_::_mrac_pid_::mrac_pid::compute_u1_eta_d () private
Function to compute the thrhust (u1) and the desired angles.
Definition at line 536 of file MRAC_PID.cpp.
References _qrbp_::A_filter_pitch_dot_ref, _qrbp_::A_filter_pitch_ref, _qrbp_::A_filter_roll_dot_ref, _qrbp_::A_filter_roll_ref, _qrbp_::A_filter_yaw_dot_ref, _qrbp_::A_filter_yaw_ref, _qrbp_::B_filter_pitch_dot_ref, _qrbp_::B_filter_pitch_ref, _qrbp_::B_filter_roll_dot_ref, _qrbp_::B_filter_roll_ref, _qrbp_::B_filter_yaw_dot_ref, _qrbp_::B_filter_yaw_ref, _qrbp_::C_filter_pitch_dot_ref, _qrbp_::C_filter_pitch_ref, _qrbp_::C_filter_roll_dot_ref, _qrbp_::C_filter_roll_ref, _qrbp_::C_filter_yaw_dot_ref, _qrbp_::C_filter_yaw_ref, cim, csm, _qrbp_::_mrac_pid_::controller_internal_members::eta_rot_acceleration_d, _qrbp_::_mrac_pid_::controller_internal_members::eta_rot_acceleration_d_b, _qrbp_::_mrac_pid_::controller_internal_members::eta_rot_acceleration_d_q, _qrbp_::_mrac_pid_::controller_internal_members::eta_rot_d, _qrbp_::_mrac_pid_::controller_internal_members::eta_rot_d_b, _qrbp_::_mrac_pid_::controller_internal_members::eta_rot_d_q, _qrbp_::_mrac_pid_::controller_internal_members::eta_rot_rate_d, _qrbp_::_mrac_pid_::controller_internal_members::eta_rot_rate_d_b, _qrbp_::_mrac_pid_::controller_internal_members::eta_rot_rate_d_q, _user_defined_trajectory_base_::trajectory_base::getUserDefinedYaw(), _user_defined_trajectory_base_::trajectory_base::getUserDefinedYawRate(), _user_defined_trajectory_base_::trajectory_base::getUserDefinedYawRateDot(), _qrbp_::_mrac_pid_::controller_internal_members::internal_state_pitch_d_filter_b, _qrbp_::_mrac_pid_::controller_internal_members::internal_state_pitch_d_filter_q, _qrbp_::_mrac_pid_::controller_internal_members::internal_state_pitch_dot_d_filter_b, _qrbp_::_mrac_pid_::controller_internal_members::internal_state_pitch_dot_d_filter_q, _qrbp_::_mrac_pid_::controller_internal_members::internal_state_roll_d_filter_q, _qrbp_::_mrac_pid_::controller_internal_members::internal_state_roll_dot_d_filter_q, _qrbp_::_mrac_pid_::controller_internal_members::internal_state_yaw_d_filter_b, _qrbp_::_mrac_pid_::controller_internal_members::internal_state_yaw_dot_d_filter_b, _qrbp_::is_biplane, _qrbp_::_mrac_pid_::controller_internal_members::mu_tran_I, _qrbp_::_mrac_pid_::controller_internal_members::mu_tran_J, _qrbp_::_mrac_pid_::controller_internal_members::mu_tran_Jb, _qrbp_::_mrac_pid_::controller_internal_members::mu_tran_Jq, _qrbp_::_mrac_pid_::controller_internal_members::R_I_Jb, _qrbp_::_mrac_pid_::controller_internal_members::R_I_Jq, _qrbp_::_mrac_pid_::controller_integrated_state_members::state_pitch_d_filter_b, _qrbp_::_mrac_pid_::controller_integrated_state_members::state_pitch_d_filter_q, _qrbp_::_mrac_pid_::controller_integrated_state_members::state_pitch_dot_d_filter_b, _qrbp_::_mrac_pid_::controller_integrated_state_members::state_pitch_dot_d_filter_q, _qrbp_::_mrac_pid_::controller_integrated_state_members::state_roll_d_filter_q, _qrbp_::_mrac_pid_::controller_integrated_state_members::state_roll_dot_d_filter_q, _qrbp_::_mrac_pid_::controller_integrated_state_members::state_yaw_d_filter_b, _qrbp_::_mrac_pid_::controller_integrated_state_members::state_yaw_dot_d_filter_b, _qrbp_::_mrac_pid_::controller_internal_members::u, and ud.
Referenced by run().
debug2terminal()
void _qrbp_::_mrac_pid_::mrac_pid::debug2terminal () private
Function to print to terminal.
Definition at line 818 of file MRAC_PID.cpp.
Referenced by run().
get_t1()
float _qrbp_::_mrac_pid_::mrac_pid::get_t1 () const
Definition at line 867 of file MRAC_PID.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t2()
float _qrbp_::_mrac_pid_::mrac_pid::get_t2 () const
Definition at line 871 of file MRAC_PID.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t3()
float _qrbp_::_mrac_pid_::mrac_pid::get_t3 () const
Definition at line 875 of file MRAC_PID.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t4()
float _qrbp_::_mrac_pid_::mrac_pid::get_t4 () const
Definition at line 879 of file MRAC_PID.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t5()
float _qrbp_::_mrac_pid_::mrac_pid::get_t5 () const
Definition at line 883 of file MRAC_PID.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t6()
float _qrbp_::_mrac_pid_::mrac_pid::get_t6 () const
Definition at line 887 of file MRAC_PID.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t7()
float _qrbp_::_mrac_pid_::mrac_pid::get_t7 () const
Definition at line 891 of file MRAC_PID.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t8()
float _qrbp_::_mrac_pid_::mrac_pid::get_t8 () const
Definition at line 895 of file MRAC_PID.cpp.
References _control_algorithm_base_::controller_base::control_input.
init()
void _qrbp_::_mrac_pid_::mrac_pid::init () private
Init function.
Translational - Initialize matrices
Quadcopter - Initialize matrices
Biplane - Initialize matrices
Definition at line 131 of file MRAC_PID.cpp.
References _qrbp_::_mrac_pid_::controller_internal_parameters::A_ref_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::A_ref_rot_q, _qrbp_::_mrac_pid_::controller_internal_parameters::A_ref_tran, _qrbp_::_mrac_pid_::controller_internal_parameters::A_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::A_rot_q, _qrbp_::_mrac_pid_::controller_internal_parameters::A_tran, _qrbp_::_mrac_pid_::controller_internal_parameters::B_ref_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::B_ref_rot_q, _qrbp_::_mrac_pid_::controller_internal_parameters::B_ref_tran, _qrbp_::_mrac_pid_::controller_internal_parameters::B_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::B_rot_q, _qrbp_::_mrac_pid_::controller_internal_parameters::B_tran, cip, dy, _qrbp_::_mrac_pid_::controller_internal_parameters::inertia_matrix, _qrbp_::inertia_matrix_q, _utilities_::initMat(), _qrbp_::is_biplane, _qrbp_::_mrac_pid_::controller_internal_parameters::Kd_refmod_tran, _qrbp_::_mrac_pid_::controller_internal_parameters::Kp_omega_ref_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::Kp_omega_ref_rot_q, _qrbp_::_mrac_pid_::controller_internal_parameters::Kp_refmod_tran, _qrbp_::MASS, _qrbp_::momentary_button, _qrbp_::_mrac_pid_::controller_internal_parameters::P_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::P_rot_q, _qrbp_::_mrac_pid_::controller_internal_parameters::P_tran, _qrbp_::_mrac_pid_::controller_internal_parameters::Q_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::Q_rot_q, _qrbp_::_mrac_pid_::controller_internal_parameters::Q_tran, _lyapunov_solver_::RealContinuousLyapunovEquation(), y, and zeros.
Referenced by mrac_pid().
model()
void _qrbp_::_mrac_pid_::mrac_pid::model (const rk4_array< double, NSI > & y, rk4_array< double, NSI > & dy, double t) private
Define the model.
Parameters
y
dy
t
Definition at line 369 of file MRAC_PID.cpp.
References _utilities_::assignElementsToDxdt(), cim, dy, _qrbp_::_mrac_pid_::controller_internal_members::e_eta, _qrbp_::_mrac_pid_::controller_internal_members::e_omega_ref, _qrbp_::_mrac_pid_::controller_internal_members::e_tran_pos, _qrbp_::_mrac_pid_::controller_internal_members::e_tran_pos_ref, _qrbp_::_mrac_pid_::controller_internal_members::internal_state_pitch_d_filter_b, _qrbp_::_mrac_pid_::controller_internal_members::internal_state_pitch_d_filter_q, _qrbp_::_mrac_pid_::controller_internal_members::internal_state_pitch_dot_d_filter_b, _qrbp_::_mrac_pid_::controller_internal_members::internal_state_pitch_dot_d_filter_q, _qrbp_::_mrac_pid_::controller_internal_members::internal_state_roll_d_filter_q, _qrbp_::_mrac_pid_::controller_internal_members::internal_state_roll_dot_d_filter_q, _qrbp_::_mrac_pid_::controller_internal_members::internal_state_yaw_d_filter_b, _qrbp_::_mrac_pid_::controller_internal_members::internal_state_yaw_dot_d_filter_q, _qrbp_::_mrac_pid_::controller_internal_members::K_hat_r_rot_dot, _qrbp_::_mrac_pid_::controller_internal_members::K_hat_r_tran_dot, _qrbp_::_mrac_pid_::controller_internal_members::K_hat_x_rot_dot, _qrbp_::_mrac_pid_::controller_internal_members::K_hat_x_tran_dot, _qrbp_::_mrac_pid_::controller_internal_members::omega_ref_dot_rot, _qrbp_::_mrac_pid_::controller_internal_members::Theta_hat_rot_dot, _qrbp_::_mrac_pid_::controller_internal_members::Theta_hat_tran_dot, and _qrbp_::_mrac_pid_::controller_internal_members::x_tran_ref_dot.
Referenced by run().
read_params()
void _qrbp_::_mrac_pid_::mrac_pid::read_params (const std::string & jsonFile) private
Implementing functions from controller_base.
Parameters
jsonFile
Definition at line 84 of file MRAC_PID.cpp.
References cip, file(), _qrbp_::_mrac_pid_::controller_internal_parameters::Gamma_r_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::Gamma_r_rot_q, _qrbp_::_mrac_pid_::controller_internal_parameters::Gamma_r_tran, _qrbp_::_mrac_pid_::controller_internal_parameters::Gamma_Theta_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::Gamma_Theta_rot_q, _qrbp_::_mrac_pid_::controller_internal_parameters::Gamma_Theta_tran, _qrbp_::_mrac_pid_::controller_internal_parameters::Gamma_x_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::Gamma_x_rot_q, _qrbp_::_mrac_pid_::controller_internal_parameters::Gamma_x_tran, _qrbp_::_mrac_pid_::controller_internal_parameters::Kd_refmod_tran, _qrbp_::_mrac_pid_::controller_internal_parameters::Kd_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::Kd_rot_q, _qrbp_::_mrac_pid_::controller_internal_parameters::Kd_tran, _qrbp_::_mrac_pid_::controller_internal_parameters::Ki_omega_cmd_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::Ki_omega_cmd_rot_q, _qrbp_::_mrac_pid_::controller_internal_parameters::Ki_omega_ref_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::Ki_omega_ref_rot_q, _qrbp_::_mrac_pid_::controller_internal_parameters::Ki_refmod_tran, _qrbp_::_mrac_pid_::controller_internal_parameters::Ki_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::Ki_rot_q, _qrbp_::_mrac_pid_::controller_internal_parameters::Ki_tran, _qrbp_::_mrac_pid_::controller_internal_parameters::Kp_omega_cmd_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::Kp_omega_cmd_rot_q, _qrbp_::_mrac_pid_::controller_internal_parameters::Kp_omega_ref_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::Kp_omega_ref_rot_q, _qrbp_::_mrac_pid_::controller_internal_parameters::Kp_refmod_tran, _qrbp_::_mrac_pid_::controller_internal_parameters::Kp_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::Kp_rot_q, _qrbp_::_mrac_pid_::controller_internal_parameters::Kp_tran, _qrbp_::_mrac_pid_::controller_internal_parameters::Q_rot_b, _qrbp_::_mrac_pid_::controller_internal_parameters::Q_rot_q, and _qrbp_::_mrac_pid_::controller_internal_parameters::Q_tran.
Referenced by mrac_pid().
reset_integrator_states()
void _qrbp_::_mrac_pid_::mrac_pid::reset_integrator_states () private
Function to reset the integrator states.
Parameters
None
Definition at line 314 of file MRAC_PID.cpp.
References _utilities_::assignElementsToMembers(), csm, _qrbp_::_mrac_pid_::controller_integrated_state_members::e_eta_I, _qrbp_::_mrac_pid_::controller_integrated_state_members::e_omega_ref_I, _qrbp_::_mrac_pid_::controller_integrated_state_members::e_tran_pos_I, _qrbp_::_mrac_pid_::controller_integrated_state_members::e_tran_pos_ref_I, _qrbp_::_mrac_pid_::controller_integrated_state_members::K_hat_r_rot, _qrbp_::_mrac_pid_::controller_integrated_state_members::K_hat_r_tran, _qrbp_::_mrac_pid_::controller_integrated_state_members::K_hat_x_rot, _qrbp_::_mrac_pid_::controller_integrated_state_members::K_hat_x_tran, _qrbp_::_mrac_pid_::controller_integrated_state_members::omega_ref_rot, _utilities_::resetElementsToMembers(), _qrbp_::_mrac_pid_::controller_integrated_state_members::state_pitch_d_filter_b, _qrbp_::_mrac_pid_::controller_integrated_state_members::state_pitch_d_filter_q, _qrbp_::_mrac_pid_::controller_integrated_state_members::state_pitch_dot_d_filter_b, _qrbp_::_mrac_pid_::controller_integrated_state_members::state_pitch_dot_d_filter_q, _qrbp_::_mrac_pid_::controller_integrated_state_members::state_roll_d_filter_q, _qrbp_::_mrac_pid_::controller_integrated_state_members::state_roll_dot_d_filter_q, _qrbp_::_mrac_pid_::controller_integrated_state_members::state_yaw_d_filter_b, _qrbp_::_mrac_pid_::controller_integrated_state_members::state_yaw_dot_d_filter_b, _qrbp_::_mrac_pid_::controller_integrated_state_members::Theta_hat_rot, _qrbp_::_mrac_pid_::controller_integrated_state_members::Theta_hat_tran, _qrbp_::_mrac_pid_::controller_integrated_state_members::x_tran_ref, y, and zeros.
Referenced by update().
run()
void _qrbp_::_mrac_pid_::mrac_pid::run (const double time_step_rk4_)
Implementing functions from controller_base.
Parameters
time_step_rk4_
Definition at line 824 of file MRAC_PID.cpp.
References _qrbp_::_mrac_pid_::controller_internal_members::aero, _qrbp_::_mrac_pid_::controller_internal_members::alg_duration, _qrbp_::_mrac_pid_::controller_internal_members::alg_end_time, _qrbp_::_mrac_pid_::controller_internal_members::alg_start_time, cim, _qrbp_::_mrac_pid_::controller_internal_members_aero::coeff, _qrbp_::compute_aero_forces_moments(), compute_innner_loop_regressor(), compute_normalized_thrusts(), compute_outer_loop_regressor(), compute_rotational_control(), compute_translational_control_in_I(), compute_u1_eta_d(), debug2terminal(), logger, _qrbp_::_mrac_pid_::mrac_pid_logger::logLogData(), model(), _qrbp_::_mrac_pid_::controller_internal_members::R_Jq_I, _qrbp_::_mrac_pid_::controller_internal_members::R_W_Jq, rk4, _qrbp_::_mrac_pid_::controller_internal_members_aero::states, _qrbp_::_mrac_pid_::controller_internal_members::t, and y.
update()
void _qrbp_::_mrac_pid_::mrac_pid::update (double time, double x, double y, double z, double vx, double vy, double vz, double q0, double q1, double q2, double q3, double roll, double pitch, double yaw, double w_x, double w_y, double w_z)
Implementing functions from controller_base.
Parameters
time
x
y
z
vx
vy
vz
q0
q1
q2
q3
roll
pitch
yaw
w_x
w_y
w_z
Definition at line 206 of file MRAC_PID.cpp.
References _qrbp_::_mrac_pid_::controller_internal_members::aero, _utilities_::aeroDCMQuadNED(), _qrbp_::_mrac_pid_::controller_internal_members::alg_start_time, _qrbp_::AeroStates::alpha, assign_from_rk4(), _qrbp_::AeroStates::beta, cim, cip, _qrbp_::_mrac_pid_::controller_internal_members_aero::coeff, _qrbp_::compute_aero_coefficients(), _qrbp_::computeAeroStatesNACA0012Quad(), _qrbp_::_mrac_pid_::controller_internal_members::eta_rot, _qrbp_::_mrac_pid_::controller_internal_members::eta_rot_b, _qrbp_::_mrac_pid_::controller_internal_members::eta_rot_q, _qrbp_::_mrac_pid_::controller_internal_members::eta_rot_rate, _user_defined_trajectory_base_::trajectory_base::getUserDefinedAcceleration(), _user_defined_trajectory_base_::trajectory_base::getUserDefinedPosition(), _user_defined_trajectory_base_::trajectory_base::getUserDefinedVelocity(), _qrbp_::_mrac_pid_::controller_internal_parameters::inertia_matrix, _qrbp_::inertia_matrix_b, _qrbp_::inertia_matrix_q, _qrbp_::is_biplane, _qrbp_::_mrac_pid_::controller_internal_members::Jacobian, _qrbp_::_mrac_pid_::controller_internal_members::Jacobian_dot, _qrbp_::_mrac_pid_::controller_internal_members::Jacobian_inv, _utilities_::jacobianMatrix(), _utilities_::jacobianMatrixDerivative(), _utilities_::jacobianMatrixInverse(), _qrbp_::momentary_button, _qrbp_::_mrac_pid_::controller_internal_members::omega_rot, _qrbp_::_mrac_pid_::controller_internal_members::omega_rot_b, _qrbp_::_mrac_pid_::controller_internal_members::omega_rot_q, _qrbp_::_mrac_pid_::controller_internal_members::q, _qrbp_::QRBPswitchFun(), _qrbp_::_mrac_pid_::controller_internal_members::r_ddot_user, _qrbp_::_mrac_pid_::controller_internal_members::r_dot_user, _qrbp_::_mrac_pid_::controller_internal_members::R_I_Jb, _qrbp_::_mrac_pid_::controller_internal_members::R_I_Jq, _qrbp_::_mrac_pid_::controller_internal_members::R_Jb_I, _qrbp_::_mrac_pid_::controller_internal_members::R_Jq_I, _qrbp_::_mrac_pid_::controller_internal_members::r_user, _qrbp_::_mrac_pid_::controller_internal_members::R_W_Jq, reset_integrator_states(), _utilities_::rotationMatrix321GlobalToLocal(), _utilities_::rotationMatrix321LocalToGlobal(), _qrbp_::_mrac_pid_::controller_internal_members_aero::states, _qrbp_::_mrac_pid_::controller_internal_members::t, ud, _qrbp_::update_states_to_biplane_quaternion_gmk(), _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::updateUserDefinedTrajectory(), _qrbp_::_mrac_pid_::controller_internal_members::x_tran, _qrbp_::_mrac_pid_::controller_internal_members::x_tran_vel_Jq, and y.
Member Data Documentation
cim
controller_internal_members _qrbp_::_mrac_pid_::mrac_pid::cim private
Definition at line 198 of file MRAC_PID.hpp.
Referenced by compute_innner_loop_regressor(), compute_normalized_thrusts(), compute_outer_loop_regressor(), compute_rotational_control(), compute_translational_control_in_I(), compute_u1_eta_d(), model(), run(), and update().
cip
controller_internal_parameters _qrbp_::_mrac_pid_::mrac_pid::cip private
Definition at line 195 of file MRAC_PID.hpp.
Referenced by compute_rotational_control(), compute_translational_control_in_I(), init(), read_params(), and update().
csm
controller_integrated_state_members _qrbp_::_mrac_pid_::mrac_pid::csm private
Definition at line 201 of file MRAC_PID.hpp.
Referenced by assign_from_rk4(), compute_rotational_control(), compute_translational_control_in_I(), compute_u1_eta_d(), and reset_integrator_states().
dy
rk4_array<double, NSI> _qrbp_::_mrac_pid_::mrac_pid::dy private
Definition at line 176 of file MRAC_PID.hpp.
Referenced by init(), and model().
logger
mrac_pid_logger _qrbp_::_mrac_pid_::mrac_pid::logger private
Definition at line 171 of file MRAC_PID.hpp.
Referenced by run().
rk4
boost::numeric::odeint::runge_kutta4<rk4_array<double, NSI> > _qrbp_::_mrac_pid_::mrac_pid::rk4 private
Definition at line 192 of file MRAC_PID.hpp.
Referenced by run().
ud
piecewise_polynomial_trajectory _qrbp_::_mrac_pid_::mrac_pid::ud private
Definition at line 168 of file MRAC_PID.hpp.
Referenced by compute_u1_eta_d(), and update().
y
rk4_array<double, NSI> _qrbp_::_mrac_pid_::mrac_pid::y private
Definition at line 175 of file MRAC_PID.hpp.
Referenced by assign_from_rk4(), init(), reset_integrator_states(), run(), and update().
zeros
rk4_array<double, NSI> _qrbp_::_mrac_pid_::mrac_pid::zeros private
Definition at line 179 of file MRAC_PID.hpp.
Referenced by init(), and reset_integrator_states().
The documentation for this class was generated from the following files:
ACSL-flightstack-winged/src/acsl_flight/include/control/platforms/qrbp/control_algorithms/MRAC_PID/MRAC_PID.hpp
ACSL-flightstack-winged/src/acsl_flight/src/control/platforms/qrbp/control_algorithms/MRAC_PID/MRAC_PID.cpp