ACSL Flightstack-winged Documentation: _drivers_::_udp_driver_::UdpReceiverNode Class Reference
_drivers_::_udp_driver_::UdpReceiverNode Class Reference final
UdpReceiverNode class which can receive UDP datagrams.
#include <mocap.hpp>
Public Member Functions
UdpReceiverNode (const IoContext &ctx, vehicle_states *d, const std::string &global_log_dir)
Constructor which accepts IoContext.
~UdpReceiverNode ()
Destructor - required to manage owned IoContext.
LNI::CallbackReturn on_configure (const lc::State &state) override
Callback from transition to "configuring" state.
LNI::CallbackReturn on_activate (const lc::State &state) override
Callback from transition to "activating" state.
LNI::CallbackReturn on_deactivate (const lc::State &state) override
Callback from transition to "deactivating" state.
LNI::CallbackReturn on_cleanup (const lc::State &state) override
Callback from transition to "unconfigured" state.
LNI::CallbackReturn on_shutdown (const lc::State &state) override
Callback from transition to "shutdown" state.
void receiver_callback (const std::vector< uint8_t > &buffer)
Callback for receiving a UDP datagram.
Public Member Functions inherited from _flight_log_::blackbox
blackbox ()
~blackbox ()
void logInitHeaders ()
bool logInitLogging ()
void logLogData ()
Private Member Functions
void get_params ()
Get the parameters for the ip and port to ping.
void debugMocapData2screen ()
Debugger function to output the mocap data.
void logInitHeaders ()
Implementing virtual functions from blackbox.
bool logInitLogging ()
void logLogData ()
Private Attributes
std::unique_ptr< IoContext > m_owned_ctx {}
Pointer to the asio context owned by this node for async communication.
std::string m_ip {}
String for the ip of the odrioid.
uint16_t m_port {}
String for the port of the odroid.
std::unique_ptr< UdpDriver > m_udp_driver
Pointer for the udp driver which wraps the udp socket.
lc::LifecyclePublisher< px4_msgs::msg::VehicleOdometry >::SharedPtr mocap_publisher_
Publisher for publishing the mocap message.
vehicle_states * vehicle_ptr
mocap_states mc_im
Declare variables to store parsed data and declare it as internal members "_im".
std::string flight_run_log_directory
Directory for logging mocap data.
Additional Inherited Members
Protected Attributes inherited from _flight_log_::blackbox
src::logger logger_logdata
src::logger logger_mocapdata
src::logger logger_viodata
Detailed Description
UdpReceiverNode class which can receive UDP datagrams.
Definition at line 139 of file mocap.hpp.
Constructor & Destructor Documentation
UdpReceiverNode()
_drivers_::_udp_driver_::UdpReceiverNode::UdpReceiverNode (const IoContext & ctx, vehicle_states * d, const std::string & global_log_dir)
Constructor which accepts IoContext.
Parameters
[in] ctx A shared IoContext
[in] pointer to vehicle states in flight_bridge
[in] string to the global flight run directory
[in] ctx A shared IoContext
[in] pointer to vehicle states in flight_bridge
[in] string to the global flight run directory
Definition at line 181 of file mocap.cpp.
References _flightstack_::FLIGHTSTACK_INFO(), get_params(), and logInitLogging().
~UdpReceiverNode()
_drivers_::_udp_driver_::UdpReceiverNode::~UdpReceiverNode ()
Destructor - required to manage owned IoContext.
Definition at line 207 of file mocap.cpp.
References _flightstack_::FLIGHTSTACK_INFO(), and m_owned_ctx.
Member Function Documentation
debugMocapData2screen()
void _drivers_::_udp_driver_::UdpReceiverNode::debugMocapData2screen () private
Debugger function to output the mocap data.
Definition at line 297 of file mocap.cpp.
References _drivers_::_udp_driver_::mocap_states::control_time, _flightstack_::FLIGHTSTACK_INFO(), mc_im, _drivers_::_udp_driver_::mocap_states::pitchspeed, _drivers_::_udp_driver_::mocap_states::q0, _drivers_::_udp_driver_::mocap_states::q1, _drivers_::_udp_driver_::mocap_states::q2, _drivers_::_udp_driver_::mocap_states::q3, _drivers_::_udp_driver_::mocap_states::rollspeed, _drivers_::_udp_driver_::mocap_states::vx, _drivers_::_udp_driver_::mocap_states::vy, _drivers_::_udp_driver_::mocap_states::vz, _drivers_::_udp_driver_::mocap_states::x, _drivers_::_udp_driver_::mocap_states::y, _drivers_::_udp_driver_::mocap_states::yawspeed, and _drivers_::_udp_driver_::mocap_states::z.
get_params()
void _drivers_::_udp_driver_::UdpReceiverNode::get_params () private
Get the parameters for the ip and port to ping.
Definition at line 196 of file mocap.cpp.
References IP_IN_USE, m_ip, m_port, and ODROID_M1S_PORT.
Referenced by UdpReceiverNode().
logInitHeaders()
void _drivers_::_udp_driver_::UdpReceiverNode::logInitHeaders () private
Implementing virtual functions from blackbox.
Definition at line 79 of file mocap.cpp.
References _flight_log_::blackbox::logger_mocapdata.
Referenced by logInitLogging().
logInitLogging()
bool _drivers_::_udp_driver_::UdpReceiverNode::logInitLogging () private
Definition at line 102 of file mocap.cpp.
References flight_run_log_directory, _flightstack_::FLIGHTSTACK_ERROR(), _flight_log_::blackbox::logger_mocapdata, and logInitHeaders().
Referenced by UdpReceiverNode().
logLogData()
void _drivers_::_udp_driver_::UdpReceiverNode::logLogData () private
Definition at line 154 of file mocap.cpp.
References _drivers_::_udp_driver_::mocap_states::control_time, _flight_log_::blackbox::logger_mocapdata, mc_im, _drivers_::_udp_driver_::mocap_states::pitchspeed, _drivers_::_udp_driver_::mocap_states::q0, _drivers_::_udp_driver_::mocap_states::q1, _drivers_::_udp_driver_::mocap_states::q2, _drivers_::_udp_driver_::mocap_states::q3, _drivers_::_udp_driver_::mocap_states::rollspeed, _drivers_::_udp_driver_::mocap_states::vx, _drivers_::_udp_driver_::mocap_states::vy, _drivers_::_udp_driver_::mocap_states::vz, _drivers_::_udp_driver_::mocap_states::x, _drivers_::_udp_driver_::mocap_states::y, _drivers_::_udp_driver_::mocap_states::yawspeed, and _drivers_::_udp_driver_::mocap_states::z.
Referenced by receiver_callback().
on_activate()
LNI::CallbackReturn _drivers_::_udp_driver_::UdpReceiverNode::on_activate (const lc::State & state) override
Callback from transition to "activating" state.
Parameters
[in] state The current state that the node is in.
Definition at line 256 of file mocap.cpp.
References mocap_publisher_.
on_cleanup()
LNI::CallbackReturn _drivers_::_udp_driver_::UdpReceiverNode::on_cleanup (const lc::State & state) override
Callback from transition to "unconfigured" state.
Parameters
[in] state The current state that the node is in.
Definition at line 278 of file mocap.cpp.
References m_udp_driver, and mocap_publisher_.
on_configure()
LNI::CallbackReturn _drivers_::_udp_driver_::UdpReceiverNode::on_configure (const lc::State & state) override
Callback from transition to "configuring" state.
Parameters
[in] state The current state that the node is in.
Definition at line 217 of file mocap.cpp.
References m_ip, m_port, m_udp_driver, mocap_publisher_, and receiver_callback().
on_deactivate()
LNI::CallbackReturn _drivers_::_udp_driver_::UdpReceiverNode::on_deactivate (const lc::State & state) override
Callback from transition to "deactivating" state.
Parameters
[in] state The current state that the node is in.
Definition at line 267 of file mocap.cpp.
References mocap_publisher_.
on_shutdown()
LNI::CallbackReturn _drivers_::_udp_driver_::UdpReceiverNode::on_shutdown (const lc::State & state) override
Callback from transition to "shutdown" state.
Parameters
[in] state The current state that the node is in.
Definition at line 289 of file mocap.cpp.
receiver_callback()
void _drivers_::_udp_driver_::UdpReceiverNode::receiver_callback (const std::vector< uint8_t > & buffer)
Callback for receiving a UDP datagram.
Definition at line 324 of file mocap.cpp.
References _drivers_::_udp_driver_::mocap_states::control_time, _flightstack_::FLIGHTSTACK_ERROR(), vehicle_states::get_controltime(), logLogData(), mc_im, mocap_publisher_, _drivers_::_udp_driver_::mocap_states::pitchspeed, POSE_FRAME_NED, _drivers_::_udp_driver_::mocap_states::q0, _drivers_::_udp_driver_::mocap_states::q1, _drivers_::_udp_driver_::mocap_states::q2, _drivers_::_udp_driver_::mocap_states::q3, _drivers_::_udp_driver_::mocap_states::rollspeed, vehicle_ptr, VELOCITY_FRAME_NED, _drivers_::_udp_driver_::mocap_states::vx, _drivers_::_udp_driver_::mocap_states::vy, _drivers_::_udp_driver_::mocap_states::vz, _drivers_::_udp_driver_::mocap_states::x, _drivers_::_udp_driver_::mocap_states::y, _drivers_::_udp_driver_::mocap_states::yawspeed, and _drivers_::_udp_driver_::mocap_states::z.
Referenced by on_configure().
Member Data Documentation
flight_run_log_directory
std::string _drivers_::_udp_driver_::UdpReceiverNode::flight_run_log_directory private
Directory for logging mocap data.
Definition at line 210 of file mocap.hpp.
Referenced by logInitLogging().
m_ip
std::string _drivers_::_udp_driver_::UdpReceiverNode::m_ip {} private
String for the ip of the odrioid.
Definition at line 183 of file mocap.hpp.
Referenced by get_params(), and on_configure().
m_owned_ctx
std::unique_ptr<IoContext> _drivers_::_udp_driver_::UdpReceiverNode::m_owned_ctx {} private
Pointer to the asio context owned by this node for async communication.
Definition at line 180 of file mocap.hpp.
Referenced by ~UdpReceiverNode().
m_port
uint16_t _drivers_::_udp_driver_::UdpReceiverNode::m_port {} private
String for the port of the odroid.
Definition at line 186 of file mocap.hpp.
Referenced by get_params(), and on_configure().
m_udp_driver
std::unique_ptr<UdpDriver> _drivers_::_udp_driver_::UdpReceiverNode::m_udp_driver private
Pointer for the udp driver which wraps the udp socket.
Definition at line 189 of file mocap.hpp.
Referenced by on_cleanup(), and on_configure().
mc_im
mocap_states _drivers_::_udp_driver_::UdpReceiverNode::mc_im private
Declare variables to store parsed data and declare it as internal members "_im".
Definition at line 199 of file mocap.hpp.
Referenced by debugMocapData2screen(), logLogData(), and receiver_callback().
mocap_publisher_
lc::LifecyclePublisher<px4_msgs::msg::VehicleOdometry>::SharedPtr _drivers_::_udp_driver_::UdpReceiverNode::mocap_publisher_ private
Publisher for publishing the mocap message.
Definition at line 192 of file mocap.hpp.
Referenced by on_activate(), on_cleanup(), on_configure(), on_deactivate(), and receiver_callback().
vehicle_ptr
vehicle_states* _drivers_::_udp_driver_::UdpReceiverNode::vehicle_ptr private
Instance of the vehicle_ptr to point to the vehicle state object in flight_bridge.cpp
Definition at line 196 of file mocap.hpp.
Referenced by receiver_callback().
The documentation for this class was generated from the following files:
ACSL-flightstack-winged/src/acsl_flight/include/mocap/mocap.hpp
ACSL-flightstack-winged/src/acsl_flight/src/mocap/mocap.cpp