ACSL Flightstack-winged Documentation: vehicle_states Class Reference
vehicle_states Class Reference
vehicle state class
#include <vehicle_class.hpp>
Public Member Functions
vehicle_states (uint64_t intial_pix_time=0, double initital_control_time=0, double initial_x=0.0, double initial_y=0.0, double initial_z=0.0, double initial_q0=1.0, double initial_q1=0.0, double initial_q2=0.0, double initial_q3=0.0, double initial_vx=0.0, double initial_vy=0.0, double initial_vz=0.0, double initial_rollspeed=0.0, double initial_pitchspeed=0.0, double initial_yawspeed=0.0, double initial_roll=0.0, double initial_pitch=0.0, double initial_yaw=0.0)
uint64_t get_pixhawktime () const
void set_pixhawktime (uint64_t value)
double get_controltime () const
void set_controltime (double value)
double get_x () const
void set_x (double value)
double get_y () const
void set_y (double value)
double get_z () const
void set_z (double value)
double get_q0 () const
void set_q0 (double value)
double get_q1 () const
void set_q1 (double value)
double get_q2 () const
void set_q2 (double value)
double get_q3 () const
void set_q3 (double value)
double get_vx () const
void set_vx (double value)
double get_vy () const
void set_vy (double value)
double get_vz () const
void set_vz (double value)
double get_rollspeed () const
void set_rollspeed (double value)
double get_pitchspeed () const
void set_pitchspeed (double value)
double get_yawspeed () const
void set_yawspeed (double value)
double get_roll () const
void set_roll (double value)
double get_pitch () const
void set_pitch (double value)
double get_yaw () const
void set_yaw (double value)
Private Attributes
std::atomic< uint64_t > pixtime
std::atomic< double > control_time
std::atomic< double > x
std::atomic< double > y
std::atomic< double > z
std::atomic< double > q0
std::atomic< double > q1
std::atomic< double > q2
std::atomic< double > q3
std::atomic< double > vx
std::atomic< double > vy
std::atomic< double > vz
std::atomic< double > rollspeed
std::atomic< double > pitchspeed
std::atomic< double > yawspeed
std::atomic< double > roll
std::atomic< double > pitch
std::atomic< double > yaw
Detailed Description
vehicle state class
Definition at line 55 of file vehicle_class.hpp.
Constructor & Destructor Documentation
vehicle_states()
vehicle_states::vehicle_states (uint64_t intial_pix_time = 0, double initital_control_time = 0, double initial_x = 0.0, double initial_y = 0.0, double initial_z = 0.0, double initial_q0 = 1.0, double initial_q1 = 0.0, double initial_q2 = 0.0, double initial_q3 = 0.0, double initial_vx = 0.0, double initial_vy = 0.0, double initial_vz = 0.0, double initial_rollspeed = 0.0, double initial_pitchspeed = 0.0, double initial_yawspeed = 0.0, double initial_roll = 0.0, double initial_pitch = 0.0, double initial_yaw = 0.0) inline
Definition at line 58 of file vehicle_class.hpp.
Member Function Documentation
get_controltime()
double vehicle_states::get_controltime () const
Definition at line 52 of file vehicle_class.cpp.
References control_time.
Referenced by _control_::controlNode::compute_and_publish_control(), _control_::controlNode::debug2screen(), _read_pix_::read_odometryNode::odometry_callback_(), _t265_::_vio_::VioT265Node::process_and_publish(), and _drivers_::_udp_driver_::UdpReceiverNode::receiver_callback().
get_pitch()
double vehicle_states::get_pitch () const
Definition at line 112 of file vehicle_class.cpp.
References pitch.
Referenced by _control_::controlNode::compute_and_publish_control(), and _control_::controlNode::debug2screen().
get_pitchspeed()
double vehicle_states::get_pitchspeed () const
Definition at line 100 of file vehicle_class.cpp.
References pitchspeed.
Referenced by _control_::controlNode::compute_and_publish_control(), and _control_::controlNode::debug2screen().
get_pixhawktime()
uint64_t vehicle_states::get_pixhawktime () const
Definition at line 48 of file vehicle_class.cpp.
References pixtime.
get_q0()
double vehicle_states::get_q0 () const
Definition at line 68 of file vehicle_class.cpp.
References q0.
Referenced by _control_::controlNode::compute_and_publish_control(), and _control_::controlNode::debug2screen().
get_q1()
double vehicle_states::get_q1 () const
Definition at line 72 of file vehicle_class.cpp.
References q1.
Referenced by _control_::controlNode::compute_and_publish_control(), and _control_::controlNode::debug2screen().
get_q2()
double vehicle_states::get_q2 () const
Definition at line 76 of file vehicle_class.cpp.
References q2.
Referenced by _control_::controlNode::compute_and_publish_control(), and _control_::controlNode::debug2screen().
get_q3()
double vehicle_states::get_q3 () const
Definition at line 80 of file vehicle_class.cpp.
References q3.
Referenced by _control_::controlNode::compute_and_publish_control(), and _control_::controlNode::debug2screen().
get_roll()
double vehicle_states::get_roll () const
Definition at line 108 of file vehicle_class.cpp.
References roll.
Referenced by _control_::controlNode::compute_and_publish_control(), and _control_::controlNode::debug2screen().
get_rollspeed()
double vehicle_states::get_rollspeed () const
Definition at line 96 of file vehicle_class.cpp.
References rollspeed.
Referenced by _control_::controlNode::compute_and_publish_control(), and _control_::controlNode::debug2screen().
get_vx()
double vehicle_states::get_vx () const
Definition at line 84 of file vehicle_class.cpp.
References vx.
Referenced by _control_::controlNode::compute_and_publish_control(), and _control_::controlNode::debug2screen().
get_vy()
double vehicle_states::get_vy () const
Definition at line 88 of file vehicle_class.cpp.
References vy.
Referenced by _control_::controlNode::compute_and_publish_control(), and _control_::controlNode::debug2screen().
get_vz()
double vehicle_states::get_vz () const
Definition at line 92 of file vehicle_class.cpp.
References vz.
Referenced by _control_::controlNode::compute_and_publish_control().
get_x()
double vehicle_states::get_x () const
Definition at line 56 of file vehicle_class.cpp.
References x.
Referenced by _control_::controlNode::compute_and_publish_control(), and _control_::controlNode::debug2screen().
get_y()
double vehicle_states::get_y () const
Definition at line 60 of file vehicle_class.cpp.
References y.
Referenced by _control_::controlNode::compute_and_publish_control(), and _control_::controlNode::debug2screen().
get_yaw()
double vehicle_states::get_yaw () const
Definition at line 116 of file vehicle_class.cpp.
References yaw.
Referenced by _control_::controlNode::compute_and_publish_control(), and _control_::controlNode::debug2screen().
get_yawspeed()
double vehicle_states::get_yawspeed () const
Definition at line 104 of file vehicle_class.cpp.
References yawspeed.
Referenced by _control_::controlNode::compute_and_publish_control(), and _control_::controlNode::debug2screen().
get_z()
double vehicle_states::get_z () const
Definition at line 64 of file vehicle_class.cpp.
References z.
Referenced by _control_::controlNode::compute_and_publish_control(), and _control_::controlNode::debug2screen().
set_controltime()
void vehicle_states::set_controltime (double value)
Definition at line 53 of file vehicle_class.cpp.
References control_time.
Referenced by _control_::controlNode::updateCurrentTime().
set_pitch()
void vehicle_states::set_pitch (double value)
Definition at line 113 of file vehicle_class.cpp.
References pitch.
Referenced by _read_pix_::read_odometryNode::odometry_callback_().
set_pitchspeed()
void vehicle_states::set_pitchspeed (double value)
Definition at line 101 of file vehicle_class.cpp.
References pitchspeed.
Referenced by _read_pix_::read_odometryNode::odometry_callback_().
set_pixhawktime()
void vehicle_states::set_pixhawktime (uint64_t value)
Definition at line 49 of file vehicle_class.cpp.
References pixtime.
Referenced by _read_pix_::read_odometryNode::odometry_callback_().
set_q0()
void vehicle_states::set_q0 (double value)
Definition at line 69 of file vehicle_class.cpp.
References q0.
Referenced by _read_pix_::read_odometryNode::odometry_callback_().
set_q1()
void vehicle_states::set_q1 (double value)
Definition at line 73 of file vehicle_class.cpp.
References q1.
Referenced by _read_pix_::read_odometryNode::odometry_callback_().
set_q2()
void vehicle_states::set_q2 (double value)
Definition at line 77 of file vehicle_class.cpp.
References q2.
Referenced by _read_pix_::read_odometryNode::odometry_callback_().
set_q3()
void vehicle_states::set_q3 (double value)
Definition at line 81 of file vehicle_class.cpp.
References q3.
Referenced by _read_pix_::read_odometryNode::odometry_callback_().
set_roll()
void vehicle_states::set_roll (double value)
Definition at line 109 of file vehicle_class.cpp.
References roll.
Referenced by _read_pix_::read_odometryNode::odometry_callback_().
set_rollspeed()
void vehicle_states::set_rollspeed (double value)
Definition at line 97 of file vehicle_class.cpp.
References rollspeed.
Referenced by _read_pix_::read_odometryNode::odometry_callback_().
set_vx()
void vehicle_states::set_vx (double value)
Definition at line 85 of file vehicle_class.cpp.
References vx.
Referenced by _read_pix_::read_odometryNode::odometry_callback_().
set_vy()
void vehicle_states::set_vy (double value)
Definition at line 89 of file vehicle_class.cpp.
References vy.
Referenced by _read_pix_::read_odometryNode::odometry_callback_().
set_vz()
void vehicle_states::set_vz (double value)
Definition at line 93 of file vehicle_class.cpp.
References vz.
Referenced by _read_pix_::read_odometryNode::odometry_callback_().
set_x()
void vehicle_states::set_x (double value)
Definition at line 57 of file vehicle_class.cpp.
References x.
Referenced by _read_pix_::read_odometryNode::odometry_callback_().
set_y()
void vehicle_states::set_y (double value)
Definition at line 61 of file vehicle_class.cpp.
References y.
Referenced by _read_pix_::read_odometryNode::odometry_callback_().
set_yaw()
void vehicle_states::set_yaw (double value)
Definition at line 117 of file vehicle_class.cpp.
References yaw.
Referenced by _read_pix_::read_odometryNode::odometry_callback_().
set_yawspeed()
void vehicle_states::set_yawspeed (double value)
Definition at line 105 of file vehicle_class.cpp.
References yawspeed.
Referenced by _read_pix_::read_odometryNode::odometry_callback_().
set_z()
void vehicle_states::set_z (double value)
Definition at line 65 of file vehicle_class.cpp.
References z.
Referenced by _read_pix_::read_odometryNode::odometry_callback_().
Member Data Documentation
control_time
std::atomic<double> vehicle_states::control_time private
Definition at line 146 of file vehicle_class.hpp.
Referenced by get_controltime(), and set_controltime().
pitch
std::atomic<double> vehicle_states::pitch private
Definition at line 161 of file vehicle_class.hpp.
Referenced by get_pitch(), and set_pitch().
pitchspeed
std::atomic<double> vehicle_states::pitchspeed private
Definition at line 158 of file vehicle_class.hpp.
Referenced by get_pitchspeed(), and set_pitchspeed().
pixtime
std::atomic<uint64_t> vehicle_states::pixtime private
Definition at line 145 of file vehicle_class.hpp.
Referenced by get_pixhawktime(), and set_pixhawktime().
q0
std::atomic<double> vehicle_states::q0 private
Definition at line 150 of file vehicle_class.hpp.
Referenced by get_q0(), and set_q0().
q1
std::atomic<double> vehicle_states::q1 private
Definition at line 151 of file vehicle_class.hpp.
Referenced by get_q1(), and set_q1().
q2
std::atomic<double> vehicle_states::q2 private
Definition at line 152 of file vehicle_class.hpp.
Referenced by get_q2(), and set_q2().
q3
std::atomic<double> vehicle_states::q3 private
Definition at line 153 of file vehicle_class.hpp.
Referenced by get_q3(), and set_q3().
roll
std::atomic<double> vehicle_states::roll private
Definition at line 160 of file vehicle_class.hpp.
Referenced by get_roll(), and set_roll().
rollspeed
std::atomic<double> vehicle_states::rollspeed private
Definition at line 157 of file vehicle_class.hpp.
Referenced by get_rollspeed(), and set_rollspeed().
vx
std::atomic<double> vehicle_states::vx private
Definition at line 154 of file vehicle_class.hpp.
Referenced by get_vx(), and set_vx().
vy
std::atomic<double> vehicle_states::vy private
Definition at line 155 of file vehicle_class.hpp.
Referenced by get_vy(), and set_vy().
vz
std::atomic<double> vehicle_states::vz private
Definition at line 156 of file vehicle_class.hpp.
Referenced by get_vz(), and set_vz().
x
std::atomic<double> vehicle_states::x private
Definition at line 147 of file vehicle_class.hpp.
Referenced by get_x(), and set_x().
y
std::atomic<double> vehicle_states::y private
Definition at line 148 of file vehicle_class.hpp.
Referenced by get_y(), and set_y().
yaw
std::atomic<double> vehicle_states::yaw private
Definition at line 162 of file vehicle_class.hpp.
Referenced by get_yaw(), and set_yaw().
yawspeed
std::atomic<double> vehicle_states::yawspeed private
Definition at line 159 of file vehicle_class.hpp.
Referenced by get_yawspeed(), and set_yawspeed().
z
std::atomic<double> vehicle_states::z private
Definition at line 149 of file vehicle_class.hpp.
Referenced by get_z(), and set_z().
The documentation for this class was generated from the following files:
ACSL-flightstack-winged/src/acsl_flight/include/vehicle_class/vehicle_class.hpp
ACSL-flightstack-winged/src/acsl_flight/src/vehicle_class/vehicle_class.cpp