ACSL Flightstack-winged Documentation: _qrbp_::_mrac_omega_::mrac_omega Class Reference
_qrbp_::_mrac_omega_::mrac_omega Class Reference
#include <MRAC_OMEGA.hpp>
Public Member Functions
mrac_omega (flight_params *p, const std::string &controller_log_dir_)
~mrac_omega ()
void run (const double time_step_rk4_)
Implementing functions from controller_base.
void update (double time, double x, double y, double z, double vx, double vy, double vz, double q0, double q1, double q2, double q3, double roll, double pitch, double yaw, double w_x, double w_y, double w_z)
float get_t1 () const
float get_t2 () const
float get_t3 () const
float get_t4 () const
float get_t5 () const
float get_t6 () const
float get_t7 () const
float get_t8 () const
Public Member Functions inherited from _control_algorithm_base_::controller_base
controller_base (flight_params *p)
~controller_base ()
void read_params ([[maybe_unused]] const std::string &jsonFile)
Read parameters.
void init ()
Initialize initial conditions.
void update ([[maybe_unused]] double time, [[maybe_unused]] double x, [[maybe_unused]] double y, [[maybe_unused]] double z, [[maybe_unused]] double vx, [[maybe_unused]] double vy, [[maybe_unused]] double vz, [[maybe_unused]] double q0, [[maybe_unused]] double q1, [[maybe_unused]] double q2, [[maybe_unused]] double q3, [[maybe_unused]] double roll, [[maybe_unused]] double pitch, [[maybe_unused]] double yaw, [[maybe_unused]] double w_x, [[maybe_unused]] double w_y, [[maybe_unused]] double w_z)
Controller Update state and trajectory.
void run ([[maybe_unused]] const double time_step_rk4_)
Controller run.
float get_t1 () const
float get_t2 () const
float get_t3 () const
float get_t4 () const
float get_t5 () const
float get_t6 () const
float get_t7 () const
float get_t8 () const
Private Member Functions
void read_params (const std::string &jsonFile)
Implementing functions from controller_base.
void init ()
init function
void model (const rk4_array< double, NSI > &y, rk4_array< double, NSI > &dy, double t)
Define the model.
void compute_outer_loop_regressor ()
Function to compute the outer loop regressor vector.
void compute_translational_control_in_I ()
Function to compute the translational control in the inertial frame.
void compute_u1_eta_d ()
Function to compute the thrust (u1) and the desired angles.
void compute_innner_loop_regressor ()
Function to compute the inner loop regressor vector.
void compute_rotational_control ()
Function to compute the rotational control input.
void compute_normalized_thrusts ()
Function to compute the normalized thrust.
void assign_from_rk4 ()
Assign the values from rk4 to controller internal members.
void debug2terminal ()
Function to print to terminal.
Private Attributes
piecewise_polynomial_trajectory ud
mrac_omega_logger logger
rk4_array< double, NSI > y
rk4_array< double, NSI > dy
boost::numeric::odeint::runge_kutta4< rk4_array< double, NSI > > rk4
controller_internal_paramters cip
controller_internal_members cim
controller_integrated_state_members csm
Additional Inherited Members
Protected Attributes inherited from _control_algorithm_base_::controller_base
Eigen::Vector< float, 8 > control_input
flight_params * flight_params_ptr
Detailed Description
Definition at line 85 of file MRAC_OMEGA.hpp.
Constructor & Destructor Documentation
mrac_omega()
_qrbp_::_mrac_omega_::mrac_omega::mrac_omega (flight_params * p, const std::string & controller_log_dir_)
Definition at line 68 of file MRAC_OMEGA.cpp.
References init(), and read_params().
~mrac_omega()
_qrbp_::_mrac_omega_::mrac_omega::~mrac_omega ()
Definition at line 80 of file MRAC_OMEGA.cpp.
Member Function Documentation
assign_from_rk4()
void _qrbp_::_mrac_omega_::mrac_omega::assign_from_rk4 () private
Assign the values from rk4 to controller internal members.
Parameters
None
Definition at line 229 of file MRAC_OMEGA.cpp.
References _utilities_::assignElementsToMembers(), csm, _qrbp_::_mrac_omega_::controller_integrated_state_members::e_rot_eta_I, _qrbp_::_mrac_omega_::controller_integrated_state_members::e_rot_omega_ref_I, _qrbp_::_mrac_omega_::controller_integrated_state_members::e_tran_pos_I, _qrbp_::_mrac_omega_::controller_integrated_state_members::e_tran_pos_ref_I, _qrbp_::_mrac_omega_::controller_integrated_state_members::K_hat_r_tran, _qrbp_::_mrac_omega_::controller_integrated_state_members::K_hat_x_tran, _qrbp_::_mrac_omega_::controller_integrated_state_members::state_omega_x_d_filter, _qrbp_::_mrac_omega_::controller_integrated_state_members::state_omega_y_d_filter, _qrbp_::_mrac_omega_::controller_integrated_state_members::state_omega_z_d_filter, _qrbp_::_mrac_omega_::controller_integrated_state_members::state_pitch_d_filter, _qrbp_::_mrac_omega_::controller_integrated_state_members::state_roll_d_filter, _qrbp_::_mrac_omega_::controller_integrated_state_members::Theta_hat_tran, _qrbp_::_mrac_omega_::controller_integrated_state_members::x_tran_ref, and y.
compute_innner_loop_regressor()
void _qrbp_::_mrac_omega_::mrac_omega::compute_innner_loop_regressor () private
Function to compute the inner loop regressor vector.
Parameters
None
Definition at line 315 of file MRAC_OMEGA.cpp.
References _qrbp_::_mrac_omega_::controller_internal_members::aero, _qrbp_::AeroStates::alpha, _qrbp_::AeroStates::beta, cim, _qrbp_::_mrac_omega_::controller_internal_members::inner_loop_regressor, _qrbp_::_mrac_omega_::controller_internal_members::omega_rot, _qrbp_::_mrac_omega_::controller_internal_members_aero::states, and _qrbp_::AeroStates::v_norm_sq.
Referenced by run().
compute_normalized_thrusts()
void _qrbp_::_mrac_omega_::mrac_omega::compute_normalized_thrusts () private
Function to compute the normalized thrust.
Parameters
None
Definition at line 511 of file MRAC_OMEGA.cpp.
References cim, _control_algorithm_base_::controller_base::control_input, _utilities_::evaluatePolynomial(), _qrbp_::MAX_THRUST, _qrbp_::MIN_THRUST, _qrbp_::mixer_matrix_qrbp, _qrbp_::_mrac_omega_::controller_internal_members::Sat_Thrust, _qrbp_::_mrac_omega_::controller_internal_members::Thrust, _qrbp_::thrust_polynomial_coeff_qrbp, and _qrbp_::_mrac_omega_::controller_internal_members::u.
Referenced by run().
compute_outer_loop_regressor()
void _qrbp_::_mrac_omega_::mrac_omega::compute_outer_loop_regressor () private
Function to compute the outer loop regressor vector.
Parameters
None
Definition at line 270 of file MRAC_OMEGA.cpp.
References _qrbp_::_mrac_omega_::controller_internal_members::aero, _qrbp_::AeroStates::alpha, _qrbp_::AeroStates::beta, cim, _qrbp_::_mrac_omega_::controller_internal_members::eta_rot, _qrbp_::_mrac_omega_::controller_internal_members::outer_loop_regressor, _qrbp_::_mrac_omega_::controller_internal_members_aero::states, and _qrbp_::AeroStates::v_norm_sq.
Referenced by run().
compute_rotational_control()
void _qrbp_::_mrac_omega_::mrac_omega::compute_rotational_control () private
Function to compute the rotational control input.
Parameters
None
Definition at line 449 of file MRAC_OMEGA.cpp.
References _qrbp_::_mrac_omega_::controller_internal_paramters::A_ref_rot, _qrbp_::_mrac_omega_::controller_internal_members::aero, _qrbp_::_mrac_omega_::controller_internal_members::alpha_rot_d, _qrbp_::_mrac_omega_::controller_internal_members::augmented_inner_loop_regressor, _qrbp_::_mrac_omega_::controller_internal_paramters::B_ref_rot, _qrbp_::_mrac_omega_::controller_internal_paramters::B_rot, cim, cip, csm, _qrbp_::_mrac_omega_::controller_internal_members_aero::dyn, _qrbp_::_mrac_omega_::controller_internal_members::e_rot_eta, _qrbp_::_mrac_omega_::controller_integrated_state_members::e_rot_eta_I, _qrbp_::_mrac_omega_::controller_internal_members::e_rot_omega, _qrbp_::_mrac_omega_::controller_internal_members::e_rot_omega_ref, _qrbp_::_mrac_omega_::controller_integrated_state_members::e_rot_omega_ref_I, _qrbp_::_mrac_omega_::controller_internal_members::eta_rot, _qrbp_::_mrac_omega_::controller_internal_members::eta_rot_d, _qrbp_::_mrac_omega_::controller_internal_paramters::Gamma_r_rot, _qrbp_::_mrac_omega_::controller_internal_paramters::Gamma_Theta_rot, _qrbp_::_mrac_omega_::controller_internal_paramters::Gamma_x_rot, _qrbp_::inertia_matrix_q, _qrbp_::AeroDynamicMembers::inner_loop_dynamic_inv, _qrbp_::_mrac_omega_::controller_internal_members::inner_loop_regressor, _qrbp_::_mrac_omega_::controller_integrated_state_members::K_hat_r_rot, _qrbp_::_mrac_omega_::controller_internal_members::K_hat_r_rot_dot, _qrbp_::_mrac_omega_::controller_integrated_state_members::K_hat_x_rot, _qrbp_::_mrac_omega_::controller_internal_members::K_hat_x_rot_dot, _qrbp_::_mrac_omega_::controller_internal_paramters::Kd_rot, _qrbp_::_mrac_omega_::controller_internal_paramters::Ki_omega_ref, _qrbp_::_mrac_omega_::controller_internal_paramters::Ki_rot, _qrbp_::_mrac_omega_::controller_internal_paramters::Kp_omega_ref, _qrbp_::_mrac_omega_::controller_internal_paramters::Kp_rot, _qrbp_::_mrac_omega_::controller_internal_members::omega_cmd, _qrbp_::_mrac_omega_::controller_internal_members::omega_rot, _qrbp_::_mrac_omega_::controller_internal_members::omega_rot_d, _qrbp_::_mrac_omega_::controller_integrated_state_members::omega_rot_ref, _qrbp_::_mrac_omega_::controller_internal_members::omega_rot_ref_dot, _qrbp_::_mrac_omega_::controller_internal_paramters::P_rot, _qrbp_::_mrac_omega_::controller_internal_members::tau_rot, _qrbp_::_mrac_omega_::controller_internal_members::tau_rot_adaptive, _qrbp_::_mrac_omega_::controller_internal_members::tau_rot_baseline, _qrbp_::_mrac_omega_::controller_integrated_state_members::Theta_hat_rot, _qrbp_::_mrac_omega_::controller_internal_members::Theta_hat_rot_dot, and _qrbp_::_mrac_omega_::controller_internal_members::u.
Referenced by run().
compute_translational_control_in_I()
void _qrbp_::_mrac_omega_::mrac_omega::compute_translational_control_in_I () private
Function to compute the translational control in the inertial frame.
Parameters
None
Definition at line 338 of file MRAC_OMEGA.cpp.
References _qrbp_::_mrac_omega_::controller_internal_paramters::A_ref_tran, _qrbp_::_mrac_omega_::controller_internal_members::aero, _qrbp_::_mrac_omega_::controller_internal_members::augmented_outer_loop_regressor, _qrbp_::_mrac_omega_::controller_internal_paramters::B_ref_tran, _qrbp_::_mrac_omega_::controller_internal_paramters::B_tran, cim, cip, csm, _qrbp_::_mrac_omega_::controller_internal_members_aero::dyn, _qrbp_::e3_basis, _qrbp_::_mrac_omega_::controller_internal_members::e_tran, _qrbp_::_mrac_omega_::controller_internal_members::e_tran_pos, _qrbp_::_mrac_omega_::controller_integrated_state_members::e_tran_pos_I, _qrbp_::_mrac_omega_::controller_internal_members::e_tran_pos_ref, _qrbp_::_mrac_omega_::controller_integrated_state_members::e_tran_pos_ref_I, _qrbp_::_mrac_omega_::controller_internal_members::e_tran_vel, _qrbp_::G, _qrbp_::_mrac_omega_::controller_internal_paramters::Gamma_r_tran, _qrbp_::_mrac_omega_::controller_internal_paramters::Gamma_Theta_tran, _qrbp_::_mrac_omega_::controller_internal_paramters::Gamma_x_tran, _qrbp_::_mrac_omega_::controller_integrated_state_members::K_hat_r_tran, _qrbp_::_mrac_omega_::controller_internal_members::K_hat_r_tran_dot, _qrbp_::_mrac_omega_::controller_integrated_state_members::K_hat_x_tran, _qrbp_::_mrac_omega_::controller_internal_members::K_hat_x_tran_dot, _qrbp_::_mrac_omega_::controller_internal_paramters::Kd_refmod_tran, _qrbp_::_mrac_omega_::controller_internal_paramters::Kd_tran, _qrbp_::_mrac_omega_::controller_internal_paramters::Ki_refmod_tran, _qrbp_::_mrac_omega_::controller_internal_paramters::Ki_tran, _qrbp_::_mrac_omega_::controller_internal_paramters::Kp_refmod_tran, _qrbp_::_mrac_omega_::controller_internal_paramters::Kp_tran, _qrbp_::MASS, _qrbp_::_mrac_omega_::controller_internal_members::mu_tran_adaptive, _qrbp_::_mrac_omega_::controller_internal_members::mu_tran_baseline, _qrbp_::_mrac_omega_::controller_internal_members::mu_tran_I, _qrbp_::AeroDynamicMembers::outer_loop_dynamic_inv, _qrbp_::_mrac_omega_::controller_internal_members::outer_loop_regressor, _qrbp_::_mrac_omega_::controller_internal_paramters::P_tran, _qrbp_::_mrac_omega_::controller_internal_members::r_cmd_tran, _qrbp_::_mrac_omega_::controller_internal_members::r_ddot_user, _qrbp_::_mrac_omega_::controller_internal_members::r_dot_user, _qrbp_::_mrac_omega_::controller_internal_members::r_user, _qrbp_::_mrac_omega_::controller_integrated_state_members::Theta_hat_tran, _qrbp_::_mrac_omega_::controller_internal_members::Theta_hat_tran_dot, _qrbp_::_mrac_omega_::controller_internal_members::x_tran, _qrbp_::_mrac_omega_::controller_integrated_state_members::x_tran_ref, and _qrbp_::_mrac_omega_::controller_internal_members::x_tran_ref_dot.
Referenced by run().
compute_u1_eta_d()
void _qrbp_::_mrac_omega_::mrac_omega::compute_u1_eta_d () private
Function to compute the thrust (u1) and the desired angles.
Parameters
None
Definition at line 397 of file MRAC_OMEGA.cpp.
References _qrbp_::A_filter_pitch_dot_ref, _qrbp_::A_filter_pitch_ref, _qrbp_::A_filter_roll_dot_ref, _qrbp_::A_filter_roll_ref, _qrbp_::A_filter_yaw_dot_ref, _qrbp_::_mrac_omega_::controller_internal_members::alpha_rot_d, _qrbp_::B_filter_pitch_dot_ref, _qrbp_::B_filter_pitch_ref, _qrbp_::B_filter_roll_dot_ref, _qrbp_::B_filter_roll_ref, _qrbp_::B_filter_yaw_dot_ref, _qrbp_::C_filter_pitch_dot_ref, _qrbp_::C_filter_pitch_ref, _qrbp_::C_filter_roll_dot_ref, _qrbp_::C_filter_roll_ref, _qrbp_::C_filter_yaw_dot_ref, cim, csm, _qrbp_::_mrac_omega_::controller_internal_members::eta_rot, _qrbp_::_mrac_omega_::controller_internal_members::eta_rot_d, _qrbp_::_mrac_omega_::controller_internal_members::eta_rot_rate_d, _qrbp_::_mrac_omega_::controller_internal_members::internal_state_omega_x_d_filter, _qrbp_::_mrac_omega_::controller_internal_members::internal_state_omega_y_d_filter, _qrbp_::_mrac_omega_::controller_internal_members::internal_state_omega_z_d_filter, _qrbp_::_mrac_omega_::controller_internal_members::internal_state_pitch_d_filter, _qrbp_::_mrac_omega_::controller_internal_members::internal_state_roll_d_filter, _qrbp_::_mrac_omega_::controller_internal_members::Jacobian, _utilities_::jacobianMatrix(), _qrbp_::_mrac_omega_::controller_internal_members::mu_tran_I, _qrbp_::_mrac_omega_::controller_internal_members::mu_tran_J, _qrbp_::_mrac_omega_::controller_internal_members::omega_rot_d, _qrbp_::_mrac_omega_::controller_internal_members::R_I_J, _qrbp_::_mrac_omega_::controller_integrated_state_members::state_omega_x_d_filter, _qrbp_::_mrac_omega_::controller_integrated_state_members::state_omega_y_d_filter, _qrbp_::_mrac_omega_::controller_integrated_state_members::state_omega_z_d_filter, _qrbp_::_mrac_omega_::controller_integrated_state_members::state_pitch_d_filter, _qrbp_::_mrac_omega_::controller_integrated_state_members::state_roll_d_filter, and _qrbp_::_mrac_omega_::controller_internal_members::u.
Referenced by run().
debug2terminal()
void _qrbp_::_mrac_omega_::mrac_omega::debug2terminal () private
Function to print to terminal.
Parameters
None
Definition at line 527 of file MRAC_OMEGA.cpp.
Referenced by run().
get_t1()
float _qrbp_::_mrac_omega_::mrac_omega::get_t1 () const
Definition at line 576 of file MRAC_OMEGA.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t2()
float _qrbp_::_mrac_omega_::mrac_omega::get_t2 () const
Definition at line 580 of file MRAC_OMEGA.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t3()
float _qrbp_::_mrac_omega_::mrac_omega::get_t3 () const
Definition at line 584 of file MRAC_OMEGA.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t4()
float _qrbp_::_mrac_omega_::mrac_omega::get_t4 () const
Definition at line 588 of file MRAC_OMEGA.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t5()
float _qrbp_::_mrac_omega_::mrac_omega::get_t5 () const
Definition at line 592 of file MRAC_OMEGA.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t6()
float _qrbp_::_mrac_omega_::mrac_omega::get_t6 () const
Definition at line 596 of file MRAC_OMEGA.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t7()
float _qrbp_::_mrac_omega_::mrac_omega::get_t7 () const
Definition at line 600 of file MRAC_OMEGA.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t8()
float _qrbp_::_mrac_omega_::mrac_omega::get_t8 () const
Definition at line 604 of file MRAC_OMEGA.cpp.
References _control_algorithm_base_::controller_base::control_input.
init()
void _qrbp_::_mrac_omega_::mrac_omega::init () private
init function
Parameters
None
Translational - Initialize matrices
Rotational - Initialize matrices
Definition at line 118 of file MRAC_OMEGA.cpp.
References _qrbp_::_mrac_omega_::controller_internal_paramters::A_ref_rot, _qrbp_::_mrac_omega_::controller_internal_paramters::A_ref_tran, _qrbp_::_mrac_omega_::controller_internal_paramters::A_rot, _qrbp_::_mrac_omega_::controller_internal_paramters::A_tran, _qrbp_::_mrac_omega_::controller_internal_paramters::B_ref_rot, _qrbp_::_mrac_omega_::controller_internal_paramters::B_ref_tran, _qrbp_::_mrac_omega_::controller_internal_paramters::B_rot, _qrbp_::_mrac_omega_::controller_internal_paramters::B_tran, cip, dy, _utilities_::initMat(), _qrbp_::_mrac_omega_::controller_internal_paramters::Kd_refmod_tran, _qrbp_::_mrac_omega_::controller_internal_paramters::Kp_omega_ref, _qrbp_::_mrac_omega_::controller_internal_paramters::Kp_refmod_tran, _qrbp_::MASS, _qrbp_::_mrac_omega_::controller_internal_paramters::P_rot, _qrbp_::_mrac_omega_::controller_internal_paramters::P_tran, _qrbp_::_mrac_omega_::controller_internal_paramters::Q_rot, _qrbp_::_mrac_omega_::controller_internal_paramters::Q_tran, _lyapunov_solver_::RealContinuousLyapunovEquation(), and y.
Referenced by mrac_omega().
model()
void _qrbp_::_mrac_omega_::mrac_omega::model (const rk4_array< double, NSI > & y, rk4_array< double, NSI > & dy, double t) private
Define the model.
Parameters
y
dy
t
Definition at line 250 of file MRAC_OMEGA.cpp.
References _utilities_::assignElementsToDxdt(), cim, dy, _qrbp_::_mrac_omega_::controller_internal_members::e_rot_eta, _qrbp_::_mrac_omega_::controller_internal_members::e_rot_omega_ref, _qrbp_::_mrac_omega_::controller_internal_members::e_tran_pos, _qrbp_::_mrac_omega_::controller_internal_members::e_tran_pos_ref, _qrbp_::_mrac_omega_::controller_internal_members::internal_state_omega_x_d_filter, _qrbp_::_mrac_omega_::controller_internal_members::internal_state_omega_y_d_filter, _qrbp_::_mrac_omega_::controller_internal_members::internal_state_omega_z_d_filter, _qrbp_::_mrac_omega_::controller_internal_members::internal_state_pitch_d_filter, _qrbp_::_mrac_omega_::controller_internal_members::internal_state_roll_d_filter, _qrbp_::_mrac_omega_::controller_internal_members::K_hat_r_tran_dot, _qrbp_::_mrac_omega_::controller_internal_members::K_hat_x_tran_dot, _qrbp_::_mrac_omega_::controller_internal_members::Theta_hat_tran_dot, and _qrbp_::_mrac_omega_::controller_internal_members::x_tran_ref_dot.
Referenced by run().
read_params()
void _qrbp_::_mrac_omega_::mrac_omega::read_params (const std::string & jsonFile) private
Implementing functions from controller_base.
Parameters
jsonFile
Definition at line 85 of file MRAC_OMEGA.cpp.
References cip, file(), _qrbp_::_mrac_omega_::controller_internal_paramters::Gamma_r_rot, _qrbp_::_mrac_omega_::controller_internal_paramters::Gamma_r_tran, _qrbp_::_mrac_omega_::controller_internal_paramters::Gamma_Theta_rot, _qrbp_::_mrac_omega_::controller_internal_paramters::Gamma_Theta_tran, _qrbp_::_mrac_omega_::controller_internal_paramters::Gamma_x_rot, _qrbp_::_mrac_omega_::controller_internal_paramters::Gamma_x_tran, _qrbp_::_mrac_omega_::controller_internal_paramters::Kd_refmod_tran, _qrbp_::_mrac_omega_::controller_internal_paramters::Kd_rot, _qrbp_::_mrac_omega_::controller_internal_paramters::Kd_tran, _qrbp_::_mrac_omega_::controller_internal_paramters::Ki_omega_ref, _qrbp_::_mrac_omega_::controller_internal_paramters::Ki_refmod_tran, _qrbp_::_mrac_omega_::controller_internal_paramters::Ki_rot, _qrbp_::_mrac_omega_::controller_internal_paramters::Ki_tran, _qrbp_::_mrac_omega_::controller_internal_paramters::Kp_omega_ref, _qrbp_::_mrac_omega_::controller_internal_paramters::Kp_refmod_tran, _qrbp_::_mrac_omega_::controller_internal_paramters::Kp_rot, _qrbp_::_mrac_omega_::controller_internal_paramters::Kp_tran, _qrbp_::_mrac_omega_::controller_internal_paramters::Q_rot, and _qrbp_::_mrac_omega_::controller_internal_paramters::Q_tran.
Referenced by mrac_omega().
run()
void _qrbp_::_mrac_omega_::mrac_omega::run (const double time_step_rk4_)
Implementing functions from controller_base.
Parameters
time_step_rk4_
Definition at line 533 of file MRAC_OMEGA.cpp.
References _qrbp_::_mrac_omega_::controller_internal_members::aero, _qrbp_::_mrac_omega_::controller_internal_members::alg_duration, _qrbp_::_mrac_omega_::controller_internal_members::alg_end_time, _qrbp_::_mrac_omega_::controller_internal_members::alg_start_time, cim, _qrbp_::_mrac_omega_::controller_internal_members_aero::coeff, _qrbp_::compute_aero_forces_moments(), compute_innner_loop_regressor(), compute_normalized_thrusts(), compute_outer_loop_regressor(), compute_rotational_control(), compute_translational_control_in_I(), compute_u1_eta_d(), debug2terminal(), logger, _qrbp_::_mrac_omega_::mrac_omega_logger::logLogData(), model(), _qrbp_::_mrac_omega_::controller_internal_members::R_J_I, _qrbp_::_mrac_omega_::controller_internal_members::R_W_J, rk4, _qrbp_::_mrac_omega_::controller_internal_members_aero::states, _qrbp_::_mrac_omega_::controller_internal_members::t, and y.
update()
void _qrbp_::_mrac_omega_::mrac_omega::update (double time, double x, double y, double z, double vx, double vy, double vz, double q0, double q1, double q2, double q3, double roll, double pitch, double yaw, double w_x, double w_y, double w_z)
Parameters
time
x
y
z
vx
vy
vz
q0
q1
q2
q3
roll
pitch
yaw
w_x
w_y
w_z
Definition at line 165 of file MRAC_OMEGA.cpp.
References _qrbp_::_mrac_omega_::controller_internal_members::aero, _utilities_::aeroDCMQuadNED(), _qrbp_::_mrac_omega_::controller_internal_members::alg_start_time, _qrbp_::AeroStates::alpha, _qrbp_::AeroStates::beta, cim, _qrbp_::_mrac_omega_::controller_internal_members_aero::coeff, _qrbp_::compute_aero_coefficients(), _qrbp_::computeAeroStatesNACA0012Quad(), _qrbp_::_mrac_omega_::controller_internal_members::eta_rot, _user_defined_trajectory_base_::trajectory_base::getUserDefinedAcceleration(), _user_defined_trajectory_base_::trajectory_base::getUserDefinedPosition(), _user_defined_trajectory_base_::trajectory_base::getUserDefinedVelocity(), _qrbp_::_mrac_omega_::controller_internal_members::omega_rot, _qrbp_::_mrac_omega_::controller_internal_members::q, _qrbp_::_mrac_omega_::controller_internal_members::r_ddot_user, _qrbp_::_mrac_omega_::controller_internal_members::r_dot_user, _qrbp_::_mrac_omega_::controller_internal_members::R_I_J, _qrbp_::_mrac_omega_::controller_internal_members::R_J_I, _qrbp_::_mrac_omega_::controller_internal_members::r_user, _qrbp_::_mrac_omega_::controller_internal_members::R_W_J, _utilities_::rotationMatrix321GlobalToLocal(), _utilities_::rotationMatrix321LocalToGlobal(), _qrbp_::_mrac_omega_::controller_internal_members_aero::states, _qrbp_::_mrac_omega_::controller_internal_members::t, ud, _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::updateUserDefinedTrajectory(), _qrbp_::_mrac_omega_::controller_internal_members::x_tran, _qrbp_::_mrac_omega_::controller_internal_members::x_tran_vel_J, and y.
Member Data Documentation
cim
controller_internal_members _qrbp_::_mrac_omega_::mrac_omega::cim private
Definition at line 191 of file MRAC_OMEGA.hpp.
Referenced by compute_innner_loop_regressor(), compute_normalized_thrusts(), compute_outer_loop_regressor(), compute_rotational_control(), compute_translational_control_in_I(), compute_u1_eta_d(), model(), run(), and update().
cip
controller_internal_paramters _qrbp_::_mrac_omega_::mrac_omega::cip private
Definition at line 188 of file MRAC_OMEGA.hpp.
Referenced by compute_rotational_control(), compute_translational_control_in_I(), init(), and read_params().
csm
controller_integrated_state_members _qrbp_::_mrac_omega_::mrac_omega::csm private
Definition at line 194 of file MRAC_OMEGA.hpp.
Referenced by assign_from_rk4(), compute_rotational_control(), compute_translational_control_in_I(), and compute_u1_eta_d().
dy
rk4_array<double, NSI> _qrbp_::_mrac_omega_::mrac_omega::dy private
Definition at line 172 of file MRAC_OMEGA.hpp.
Referenced by init(), and model().
logger
mrac_omega_logger _qrbp_::_mrac_omega_::mrac_omega::logger private
Definition at line 167 of file MRAC_OMEGA.hpp.
Referenced by run().
rk4
boost::numeric::odeint::runge_kutta4<rk4_array<double, NSI> > _qrbp_::_mrac_omega_::mrac_omega::rk4 private
Definition at line 185 of file MRAC_OMEGA.hpp.
Referenced by run().
ud
piecewise_polynomial_trajectory _qrbp_::_mrac_omega_::mrac_omega::ud private
Definition at line 164 of file MRAC_OMEGA.hpp.
Referenced by update().
y
rk4_array<double, NSI> _qrbp_::_mrac_omega_::mrac_omega::y private
Definition at line 171 of file MRAC_OMEGA.hpp.
Referenced by assign_from_rk4(), init(), run(), and update().
The documentation for this class was generated from the following files:
ACSL-flightstack-winged/src/acsl_flight/include/control/platforms/qrbp/control_algorithms/MRAC_OMEGA/MRAC_OMEGA.hpp
ACSL-flightstack-winged/src/acsl_flight/src/control/platforms/qrbp/control_algorithms/MRAC_OMEGA/MRAC_OMEGA.cpp