ACSL Flightstack-winged Documentation: _rostestdrone_::_pid_::pid Class Reference
_rostestdrone_::_pid_::pid Class Reference
class pid : public controller_base, public blackbox
#include <PID_TD.hpp>
Public Member Functions
pid (flight_params *p, const std::string &controller_log_dir_)
~pid ()
void run (const double time_step_rk4_)
Run the class pid.
void update (double time, double x, double y, double z, double vx, double vy, double vz, double q0, double q1, double q2, double q3, double roll, double pitch, double yaw, double w_x, double w_y, double w_z)
Update pid class.
float get_t1 () const
float get_t2 () const
float get_t3 () const
float get_t4 () const
float get_t5 () const
float get_t6 () const
float get_t7 () const
float get_t8 () const
Public Member Functions inherited from _control_algorithm_base_::controller_base
controller_base (flight_params *p)
~controller_base ()
void read_params ([[maybe_unused]] const std::string &jsonFile)
Read parameters.
void init ()
Initialize initial conditions.
void update ([[maybe_unused]] double time, [[maybe_unused]] double x, [[maybe_unused]] double y, [[maybe_unused]] double z, [[maybe_unused]] double vx, [[maybe_unused]] double vy, [[maybe_unused]] double vz, [[maybe_unused]] double q0, [[maybe_unused]] double q1, [[maybe_unused]] double q2, [[maybe_unused]] double q3, [[maybe_unused]] double roll, [[maybe_unused]] double pitch, [[maybe_unused]] double yaw, [[maybe_unused]] double w_x, [[maybe_unused]] double w_y, [[maybe_unused]] double w_z)
Controller Update state and trajectory.
void run ([[maybe_unused]] const double time_step_rk4_)
Controller run.
float get_t1 () const
float get_t2 () const
float get_t3 () const
float get_t4 () const
float get_t5 () const
float get_t6 () const
float get_t7 () const
float get_t8 () const
Private Member Functions
void read_params (const std::string &jsonFile)
Read the parameters from the json file.
void init ()
void model (const rk4_array< double, 14 > &y, rk4_array< double, 14 > &dy, double t)
Define model.
void compute_translational_control_in_I ()
Compute the translational control in the inertial frame.
void compute_u1_eta_d ()
compute the thrust (u1) and the desired angles
void compute_rotational_control ()
Compute the rotational control input.
void compute_normalized_thrusts ()
Compute the normalized thrust.
void assign_from_rk4 ()
Assign the values from rk4 to controller internal members.
void debug2terminal ()
Function to print to terminal.
Private Attributes
piecewise_polynomial_trajectory ud
pid_logger logger
rk4_array< double, 14 > y
rk4_array< double, 14 > dy
rk4_array< double, 14 > zeros
boost::numeric::odeint::runge_kutta4< rk4_array< double, 14 > > rk4
controller_internal_parameters cip
controller_internal_members cim
controller_integrated_state_members csm
Additional Inherited Members
Protected Attributes inherited from _control_algorithm_base_::controller_base
Eigen::Vector< float, 8 > control_input
flight_params * flight_params_ptr
Detailed Description
class pid : public controller_base, public blackbox
Definition at line 74 of file PID_TD.hpp.
Constructor & Destructor Documentation
pid()
_rostestdrone_::_pid_::pid::pid (flight_params * p, const std::string & controller_log_dir_)
Definition at line 61 of file PID_TD.cpp.
References init(), and read_params().
~pid()
_rostestdrone_::_pid_::pid::~pid ()
Definition at line 72 of file PID_TD.cpp.
Member Function Documentation
assign_from_rk4()
void _rostestdrone_::_pid_::pid::assign_from_rk4 () private
Assign the values from rk4 to controller internal members.
Parameters
None
Definition at line 166 of file PID_TD.cpp.
References _utilities_::assignElementsToMembers(), csm, _rostestdrone_::_pid_::controller_integrated_state_members::e_eta_I, _rostestdrone_::_pid_::controller_integrated_state_members::e_tran_pos_I, _rostestdrone_::_pid_::controller_integrated_state_members::state_pitch_d_filter, _rostestdrone_::_pid_::controller_integrated_state_members::state_pitch_dot_d_filter, _rostestdrone_::_pid_::controller_integrated_state_members::state_roll_d_filter, _rostestdrone_::_pid_::controller_integrated_state_members::state_roll_dot_d_filter, and y.
Referenced by update().
compute_normalized_thrusts()
void _rostestdrone_::_pid_::pid::compute_normalized_thrusts () private
Compute the normalized thrust.
Parameters
None
Definition at line 275 of file PID_TD.cpp.
References cim, _control_algorithm_base_::controller_base::control_input, _utilities_::evaluatePolynomial(), _rostestdrone_::MAX_THRUST, _rostestdrone_::MIN_THRUST, _rostestdrone_::mixer_matrix_qrbp, _rostestdrone_::_pid_::controller_internal_members::Sat_Thrust, _rostestdrone_::_pid_::controller_internal_members::Thrust, _rostestdrone_::thrust_polynomial_coeff_qrbp, and _rostestdrone_::_pid_::controller_internal_members::u.
Referenced by run().
compute_rotational_control()
void _rostestdrone_::_pid_::pid::compute_rotational_control () private
Compute the rotational control input.
Parameters
None
Definition at line 249 of file PID_TD.cpp.
References cim, cip, csm, _rostestdrone_::_pid_::controller_internal_members::e_eta, _rostestdrone_::_pid_::controller_integrated_state_members::e_eta_I, _rostestdrone_::_pid_::controller_internal_members::e_eta_rate, _rostestdrone_::_pid_::controller_internal_members::eta_rot, _rostestdrone_::_pid_::controller_internal_members::eta_rot_acceleration_d, _rostestdrone_::_pid_::controller_internal_members::eta_rot_d, _rostestdrone_::_pid_::controller_internal_members::eta_rot_rate, _rostestdrone_::_pid_::controller_internal_members::eta_rot_rate_d, _rostestdrone_::inertia_matrix_q, _rostestdrone_::_pid_::controller_internal_parameters::Kd_rot, _rostestdrone_::_pid_::controller_internal_parameters::Ki_rot, _rostestdrone_::_pid_::controller_internal_parameters::Kp_rot, _rostestdrone_::_pid_::controller_internal_members::omega_rot, _rostestdrone_::_pid_::controller_internal_members::tau_rot, _rostestdrone_::_pid_::controller_internal_members::tau_rot_baseline, and _rostestdrone_::_pid_::controller_internal_members::u.
Referenced by run().
compute_translational_control_in_I()
void _rostestdrone_::_pid_::pid::compute_translational_control_in_I () private
Compute the translational control in the inertial frame.
Parameters
None
Definition at line 191 of file PID_TD.cpp.
References cim, cip, csm, _rostestdrone_::e3_basis, _rostestdrone_::_pid_::controller_internal_members::e_tran_pos, _rostestdrone_::_pid_::controller_integrated_state_members::e_tran_pos_I, _rostestdrone_::_pid_::controller_internal_members::e_tran_vel, _rostestdrone_::G, _rostestdrone_::_pid_::controller_internal_parameters::Kd_tran, _rostestdrone_::_pid_::controller_internal_parameters::Ki_tran, _rostestdrone_::_pid_::controller_internal_parameters::Kp_tran, _rostestdrone_::MASS, _rostestdrone_::_pid_::controller_internal_members::mu_tran_baseline, _rostestdrone_::_pid_::controller_internal_members::mu_tran_I, _rostestdrone_::_pid_::controller_internal_members::r_ddot_user, _rostestdrone_::_pid_::controller_internal_members::r_dot_user, _rostestdrone_::_pid_::controller_internal_members::r_user, _rostestdrone_::_pid_::controller_internal_members::x_tran_pos, and _rostestdrone_::_pid_::controller_internal_members::x_tran_vel.
Referenced by run().
compute_u1_eta_d()
void _rostestdrone_::_pid_::pid::compute_u1_eta_d () private
compute the thrust (u1) and the desired angles
Parameters
None
Definition at line 207 of file PID_TD.cpp.
References _rostestdrone_::A_filter_pitch_dot_ref, _rostestdrone_::A_filter_pitch_ref, _rostestdrone_::A_filter_roll_dot_ref, _rostestdrone_::A_filter_roll_ref, _rostestdrone_::B_filter_pitch_dot_ref, _rostestdrone_::B_filter_pitch_ref, _rostestdrone_::B_filter_roll_dot_ref, _rostestdrone_::B_filter_roll_ref, _rostestdrone_::C_filter_pitch_dot_ref, _rostestdrone_::C_filter_pitch_ref, _rostestdrone_::C_filter_roll_dot_ref, _rostestdrone_::C_filter_roll_ref, cim, csm, _rostestdrone_::_pid_::controller_internal_members::eta_rot_acceleration_d, _rostestdrone_::_pid_::controller_internal_members::eta_rot_d, _rostestdrone_::_pid_::controller_internal_members::eta_rot_rate_d, _rostestdrone_::_pid_::controller_internal_members::internal_state_pitch_d_filter, _rostestdrone_::_pid_::controller_internal_members::internal_state_pitch_dot_d_filter, _rostestdrone_::_pid_::controller_internal_members::internal_state_roll_d_filter, _rostestdrone_::_pid_::controller_internal_members::internal_state_roll_dot_d_filter, _rostestdrone_::_pid_::controller_internal_members::mu_tran_I, _rostestdrone_::_pid_::controller_internal_members::mu_tran_J, _rostestdrone_::_pid_::controller_internal_members::R_I_J, _rostestdrone_::_pid_::controller_integrated_state_members::state_pitch_d_filter, _rostestdrone_::_pid_::controller_integrated_state_members::state_pitch_dot_d_filter, _rostestdrone_::_pid_::controller_integrated_state_members::state_roll_d_filter, _rostestdrone_::_pid_::controller_integrated_state_members::state_roll_dot_d_filter, and _rostestdrone_::_pid_::controller_internal_members::u.
Referenced by run().
debug2terminal()
void _rostestdrone_::_pid_::pid::debug2terminal () private
Function to print to terminal.
Parameters
None
Definition at line 290 of file PID_TD.cpp.
Referenced by run().
get_t1()
float _rostestdrone_::_pid_::pid::get_t1 () const
Definition at line 329 of file PID_TD.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t2()
float _rostestdrone_::_pid_::pid::get_t2 () const
Definition at line 333 of file PID_TD.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t3()
float _rostestdrone_::_pid_::pid::get_t3 () const
Definition at line 337 of file PID_TD.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t4()
float _rostestdrone_::_pid_::pid::get_t4 () const
Definition at line 341 of file PID_TD.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t5()
float _rostestdrone_::_pid_::pid::get_t5 () const
Definition at line 345 of file PID_TD.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t6()
float _rostestdrone_::_pid_::pid::get_t6 () const
Definition at line 349 of file PID_TD.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t7()
float _rostestdrone_::_pid_::pid::get_t7 () const
Definition at line 353 of file PID_TD.cpp.
References _control_algorithm_base_::controller_base::control_input.
get_t8()
float _rostestdrone_::_pid_::pid::get_t8 () const
Definition at line 357 of file PID_TD.cpp.
References _control_algorithm_base_::controller_base::control_input.
init()
void _rostestdrone_::_pid_::pid::init () private
Definition at line 95 of file PID_TD.cpp.
References dy, y, and zeros.
Referenced by pid().
model()
void _rostestdrone_::_pid_::pid::model (const rk4_array< double, 14 > & y, rk4_array< double, 14 > & dy, double t) private
Define model.
Parameters
y
dy
t
Referenced by run().
read_params()
void _rostestdrone_::_pid_::pid::read_params (const std::string & jsonFile) private
Read the parameters from the json file.
Parameters
jsonFile
Definition at line 77 of file PID_TD.cpp.
References cip, file(), _rostestdrone_::_pid_::controller_internal_parameters::Kd_rot, _rostestdrone_::_pid_::controller_internal_parameters::Kd_tran, _rostestdrone_::_pid_::controller_internal_parameters::Ki_rot, _rostestdrone_::_pid_::controller_internal_parameters::Ki_tran, _rostestdrone_::_pid_::controller_internal_parameters::Kp_rot, and _rostestdrone_::_pid_::controller_internal_parameters::Kp_tran.
Referenced by pid().
run()
void _rostestdrone_::_pid_::pid::run (const double time_step_rk4_)
Run the class pid.
Parameters
time_step_rk4_
Definition at line 295 of file PID_TD.cpp.
References _rostestdrone_::_pid_::controller_internal_members::alg_duration, _rostestdrone_::_pid_::controller_internal_members::alg_end_time, _rostestdrone_::_pid_::controller_internal_members::alg_start_time, cim, compute_normalized_thrusts(), compute_rotational_control(), compute_translational_control_in_I(), compute_u1_eta_d(), debug2terminal(), logger, _rostestdrone_::_pid_::pid_logger::logLogData(), model(), rk4, _rostestdrone_::_pid_::controller_internal_members::t, and y.
update()
void _rostestdrone_::_pid_::pid::update (double time, double x, double y, double z, double vx, double vy, double vz, double q0, double q1, double q2, double q3, double roll, double pitch, double yaw, double w_x, double w_y, double w_z)
Update pid class.
Parameters
time
x
y
z
vx
vy
vz
q0
q1
q2
q3
roll
pitch
yaw
w_x
w_y
w_z
Definition at line 105 of file PID_TD.cpp.
References _rostestdrone_::_pid_::controller_internal_members::alg_start_time, assign_from_rk4(), cim, _rostestdrone_::_pid_::controller_internal_members::eta_rot, _rostestdrone_::_pid_::controller_internal_members::eta_rot_acceleration_d, _rostestdrone_::_pid_::controller_internal_members::eta_rot_d, _rostestdrone_::_pid_::controller_internal_members::eta_rot_rate, _rostestdrone_::_pid_::controller_internal_members::eta_rot_rate_d, _user_defined_trajectory_base_::trajectory_base::getUserDefinedAcceleration(), _user_defined_trajectory_base_::trajectory_base::getUserDefinedPosition(), _user_defined_trajectory_base_::trajectory_base::getUserDefinedVelocity(), _user_defined_trajectory_base_::trajectory_base::getUserDefinedYaw(), _user_defined_trajectory_base_::trajectory_base::getUserDefinedYawRate(), _user_defined_trajectory_base_::trajectory_base::getUserDefinedYawRateDot(), _rostestdrone_::_pid_::controller_internal_members::Jacobian_inv, _utilities_::jacobianMatrixInverse(), _rostestdrone_::_pid_::controller_internal_members::omega_rot, _rostestdrone_::_pid_::controller_internal_members::q, _rostestdrone_::_pid_::controller_internal_members::r_ddot_user, _rostestdrone_::_pid_::controller_internal_members::r_dot_user, _rostestdrone_::_pid_::controller_internal_members::R_I_J, _rostestdrone_::_pid_::controller_internal_members::R_J_I, _rostestdrone_::_pid_::controller_internal_members::r_user, _utilities_::rotationMatrix321GlobalToLocal(), _utilities_::rotationMatrix321LocalToGlobal(), _rostestdrone_::_pid_::controller_internal_members::t, ud, _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::updateUserDefinedTrajectory(), _rostestdrone_::_pid_::controller_internal_members::x_tran_pos, _rostestdrone_::_pid_::controller_internal_members::x_tran_vel, and y.
Member Data Documentation
cim
controller_internal_members _rostestdrone_::_pid_::pid::cim private
Definition at line 181 of file PID_TD.hpp.
Referenced by compute_normalized_thrusts(), compute_rotational_control(), compute_translational_control_in_I(), compute_u1_eta_d(), run(), and update().
cip
controller_internal_parameters _rostestdrone_::_pid_::pid::cip private
Definition at line 178 of file PID_TD.hpp.
Referenced by compute_rotational_control(), compute_translational_control_in_I(), and read_params().
csm
controller_integrated_state_members _rostestdrone_::_pid_::pid::csm private
Definition at line 184 of file PID_TD.hpp.
Referenced by assign_from_rk4(), compute_rotational_control(), compute_translational_control_in_I(), and compute_u1_eta_d().
dy
rk4_array<double, 14> _rostestdrone_::_pid_::pid::dy private
Definition at line 159 of file PID_TD.hpp.
Referenced by init().
logger
pid_logger _rostestdrone_::_pid_::pid::logger private
Definition at line 154 of file PID_TD.hpp.
Referenced by run().
rk4
boost::numeric::odeint::runge_kutta4<rk4_array<double, 14> > _rostestdrone_::_pid_::pid::rk4 private
Definition at line 175 of file PID_TD.hpp.
Referenced by run().
ud
piecewise_polynomial_trajectory _rostestdrone_::_pid_::pid::ud private
Definition at line 151 of file PID_TD.hpp.
Referenced by update().
y
rk4_array<double, 14> _rostestdrone_::_pid_::pid::y private
Definition at line 158 of file PID_TD.hpp.
Referenced by assign_from_rk4(), init(), run(), and update().
zeros
rk4_array<double, 14> _rostestdrone_::_pid_::pid::zeros private
Definition at line 162 of file PID_TD.hpp.
Referenced by init().
The documentation for this class was generated from the following files:
ACSL-flightstack-winged/src/acsl_flight/include/control/platforms/rostestdrone/control_algorithms/PID/PID_TD.hpp
ACSL-flightstack-winged/src/acsl_flight/src/control/platforms/rostestdrone/control_algorithms/PID/PID_TD.cpp