ACSL Flightstack-winged Documentation: _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory Class Reference
_piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory Class Reference
Piecwise polynomial trajectory.
#include <piecewise_polynomial_trajectory.hpp>
Public Member Functions
piecewise_polynomial_trajectory (flight_params *p)
void updateUserDefinedTrajectory (double controller_time)
Function to update the user defined trajectory according to the controller time.
Public Member Functions inherited from _user_defined_trajectory_base_::trajectory_base
trajectory_base ()
const Vector3d & getUserDefinedPosition () const
Get the User Defined Position object.
void setUserDefinedPosition (const Vector3d &pos)
Set the User Defined Position object.
const Vector3d & getUserDefinedVelocity () const
Get the User Defined Velocity object.
void setUserDefinedVelocity (const Vector3d &vel)
Set the User Defined Velocity object.
const Vector3d & getUserDefinedAcceleration () const
Get the User Defined Acceleration object.
void setUserDefinedAcceleration (const Vector3d &acc)
Set the User Defined Acceleration object.
const Vector3d & getUserDefinedAngle () const
void setUserDefinedAngle (const Vector3d &angle)
void setUserDefinedRoll (double x)
Set the User Defined Roll object.
void setUserDefinedPitch (double y)
Set the User Defined Pitch object.
void setUserDefinedYaw (double z)
Set the User Defined Yaw object.
double getUserDefinedRoll () const
Get the User Defined Roll object.
double getUserDefinedPitch () const
Get the User Defined Pitch object.
double getUserDefinedYaw () const
Get the User Defined Yaw object.
const Vector3d & getUserDefinedAngularRate () const
Get the User Defined Angular Rate object.
void setUserDefinedAngularRate (const Vector3d &angular_rate)
Set the User Defined Angular Rate object.
void setUserDefinedRollRate (double x)
void setUserDefinedPitchRate (double y)
void setUserDefinedYawRate (double z)
double getUserDefinedRollRate () const
double getUserDefinedPitchRate () const
double getUserDefinedYawRate () const
const Vector3d & getUserDefinedAngularRateDot () const
void setUserDefinedAngularRateDot (const Vector3d &ang_rt_dot)
void setUserDefinedRollRateDot (double x)
void setUserDefinedPitchRateDot (double y)
void setUserDefinedYawRateDot (double z)
double getUserDefinedRollRateDot () const
double getUserDefinedPitchRateDot () const
double getUserDefinedYawRateDot () const
const Vector3d & getUserDefinedAngularVelocity () const
void setUserDefinedAngularVelocity (const Vector3d &angular_vel)
void setUserDefinedOmegaX (double x)
void setUserDefinedOmegaY (double y)
void setUserDefinedOmegaZ (double z)
double getUserDefinedOmegaX () const
double getUserDefinedOmegaY () const
double getUserDefinedOmegaZ () const
const Vector3d & getUserDefinedAngularAcceleration () const
void setUserDefinedAngularAcceleration (const Vector3d &angular_acc)
void setUserDefinedAlphaX (double x)
void setUserDefinedAlphaY (double y)
void setUserDefinedAlphaZ (double z)
double getUserDefinedAlphaX () const
double getUserDefinedAlphaY () const
double getUserDefinedAlphaZ () const
Private Member Functions
void updateUserDefinedYaw ()
Function that updates the user-defined yaw, yaw_dot, and yaw_dot_dot based on the time at which it is requested to be evaulated.
double yawComputation (const VectorXd &Vx_coef, const VectorXd &Vy_coef, double t)
Compute the user-defined yaw from the trajectory velocity in the XY plane.
double yawDotComputation (const VectorXd &Vx_coef, const VectorXd &Vy_coef, const VectorXd &Ax_coef, const VectorXd &Ay_coef, double t)
Compute the user-defined yaw_dot from the trajectory velocity in the XY plane.
double yawDotDotComputation (const VectorXd &Vx_coef, const VectorXd &Vy_coef, const VectorXd &Ax_coef, const VectorXd &Ay_coef, const VectorXd &Jx_coef, const VectorXd &Jy_coef, double t)
Compute the user-defined yaw_dot_dot from the trajectory velocity in the XY plane.
void setPolynomialCoefficientMatrices ()
Set the Polynomial Coefficient Matrices object.
std::pair< double, int > polynomialTimeAdjusted (double time)
std::vector< Eigen::MatrixXd > polyCoefAssigning (const std::vector< std::vector< double >> &poly_coeff_matrix_in)
Private Attributes
flight_params * flight_params_ptr
double internal_time
double internal_time_adjusted
int segment_
Vector3d user_defined_position_previous_
double user_defined_yaw_previous_
double norm_velocity_XY_
MatrixXd position_coef_x_
MatrixXd position_coef_y_
MatrixXd position_coef_z_
MatrixXd velocity_coef_x_
MatrixXd velocity_coef_y_
MatrixXd velocity_coef_z_
MatrixXd acceleration_coef_x_
MatrixXd acceleration_coef_y_
MatrixXd acceleration_coef_z_
MatrixXd jerk_coef_x_
MatrixXd jerk_coef_y_
MatrixXd jerk_coef_z_
const VectorXd landing_position_coef_z_
Position polynomial coefficients for LANDING from (X, Y, -1) to (X, Y, 0) in 4 seconds.
const VectorXd landing_velocity_coef_z_
const VectorXd landing_acceleration_coef_z_
Additional Inherited Members
Protected Attributes inherited from _user_defined_trajectory_base_::trajectory_base
Vector3d ud_pos
Vector3d ud_vel
Vector3d ud_acc
Vector3d ud_angle
Vector3d ud_angular_rate
Vector3d ud_angular_rate_dot
Vector3d ud_angular_vel
Vector3d ud_angular_acc
Detailed Description
Piecwise polynomial trajectory.
Definition at line 64 of file piecewise_polynomial_trajectory.hpp.
Constructor & Destructor Documentation
piecewise_polynomial_trajectory()
_piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::piecewise_polynomial_trajectory (flight_params * p)
Definition at line 54 of file piecewise_polynomial_trajectory.cpp.
References setPolynomialCoefficientMatrices().
Member Function Documentation
polyCoefAssigning()
std::vector< Eigen::MatrixXd > _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::polyCoefAssigning (const std::vector< std::vector< double >> & poly_coeff_matrix_in) private
Definition at line 68 of file piecewise_polynomial_trajectory.cpp.
Referenced by setPolynomialCoefficientMatrices().
polynomialTimeAdjusted()
std::pair< double, int > _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::polynomialTimeAdjusted (double time) private
Definition at line 132 of file piecewise_polynomial_trajectory.cpp.
References flight_params_ptr, PiecewisePolynomialTrajectoryInfo::num_waypts, flight_params::traj_params, and PiecewisePolynomialTrajectoryInfo::waypoint_times_.
Referenced by updateUserDefinedTrajectory().
setPolynomialCoefficientMatrices()
void _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::setPolynomialCoefficientMatrices () private
Set the Polynomial Coefficient Matrices object.
Parameters
None
Definition at line 97 of file piecewise_polynomial_trajectory.cpp.
References acceleration_coef_x_, acceleration_coef_y_, acceleration_coef_z_, flight_params_ptr, jerk_coef_x_, jerk_coef_y_, jerk_coef_z_, PiecewisePolynomialTrajectoryInfo::piecewise_polynomial_coefficients_, polyCoefAssigning(), _utilities_::polyDerMatrix(), position_coef_x_, position_coef_y_, position_coef_z_, flight_params::traj_params, velocity_coef_x_, velocity_coef_y_, and velocity_coef_z_.
Referenced by piecewise_polynomial_trajectory().
updateUserDefinedTrajectory()
void _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::updateUserDefinedTrajectory (double controller_time)
Function to update the user defined trajectory according to the controller time.
Parameters
controller_time
Definition at line 153 of file piecewise_polynomial_trajectory.cpp.
References acceleration_coef_x_, acceleration_coef_y_, acceleration_coef_z_, _utilities_::evaluatePolynomial(), flight_params_ptr, _user_defined_trajectory_base_::trajectory_base::getUserDefinedPosition(), internal_time, internal_time_adjusted, flight_params::landing_end_time, landing_position_coef_z_, flight_params::landing_start_time, landing_velocity_coef_z_, polynomialTimeAdjusted(), position_coef_x_, position_coef_y_, position_coef_z_, segment_, _user_defined_trajectory_base_::trajectory_base::setUserDefinedAcceleration(), _user_defined_trajectory_base_::trajectory_base::setUserDefinedPosition(), _user_defined_trajectory_base_::trajectory_base::setUserDefinedVelocity(), flight_params::start_time, flight_params::traj_params, updateUserDefinedYaw(), user_defined_position_previous_, velocity_coef_x_, velocity_coef_y_, velocity_coef_z_, and PiecewisePolynomialTrajectoryInfo::waypoint_times_.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::update(), _qrbp_::_mrac_pid_::mrac_pid::update(), _qrbp_::_pid_::pid::update(), _qrbp_::_pid_omega_::pid_omega::update(), and _rostestdrone_::_pid_::pid::update().
updateUserDefinedYaw()
void _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::updateUserDefinedYaw () private
Function that updates the user-defined yaw, yaw_dot, and yaw_dot_dot based on the time at which it is requested to be evaulated.
Parameters
None
Definition at line 232 of file piecewise_polynomial_trajectory.cpp.
References acceleration_coef_x_, acceleration_coef_y_, flight_params_ptr, _user_defined_trajectory_base_::trajectory_base::getUserDefinedYaw(), internal_time, internal_time_adjusted, jerk_coef_x_, jerk_coef_y_, norm_velocity_XY_, segment_, _user_defined_trajectory_base_::trajectory_base::setUserDefinedYaw(), _user_defined_trajectory_base_::trajectory_base::setUserDefinedYawRate(), _user_defined_trajectory_base_::trajectory_base::setUserDefinedYawRateDot(), flight_params::traj_params, user_defined_yaw_previous_, velocity_coef_x_, velocity_coef_y_, PiecewisePolynomialTrajectoryInfo::waypoint_times_, yawComputation(), yawDotComputation(), and yawDotDotComputation().
Referenced by updateUserDefinedTrajectory().
yawComputation()
double _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::yawComputation (const VectorXd & Vx_coef, const VectorXd & Vy_coef, double t) private
Compute the user-defined yaw from the trajectory velocity in the XY plane.
Parameters
Vx_coef
Vy_coef
t
Returns
double
Definition at line 277 of file piecewise_polynomial_trajectory.cpp.
References _utilities_::evaluatePolynomial().
Referenced by updateUserDefinedYaw(), yawDotComputation(), and yawDotDotComputation().
yawDotComputation()
double _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::yawDotComputation (const VectorXd & Vx_coef, const VectorXd & Vy_coef, const VectorXd & Ax_coef, const VectorXd & Ay_coef, double t) private
Compute the user-defined yaw_dot from the trajectory velocity in the XY plane.
Parameters
Vx_coef
Vy_coef
Ax_coef
Ay_coef
t
Returns
double
Definition at line 290 of file piecewise_polynomial_trajectory.cpp.
References _utilities_::evaluatePolynomial(), and yawComputation().
Referenced by updateUserDefinedYaw(), and yawDotDotComputation().
yawDotDotComputation()
double _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::yawDotDotComputation (const VectorXd & Vx_coef, const VectorXd & Vy_coef, const VectorXd & Ax_coef, const VectorXd & Ay_coef, const VectorXd & Jx_coef, const VectorXd & Jy_coef, double t) private
Compute the user-defined yaw_dot_dot from the trajectory velocity in the XY plane.
Parameters
Vx_coef
Vy_coef
Ax_coef
Ay_coef
Jx_coef
Jy_coef
t
Returns
double
Definition at line 315 of file piecewise_polynomial_trajectory.cpp.
References _utilities_::evaluatePolynomial(), yawComputation(), and yawDotComputation().
Referenced by updateUserDefinedYaw().
Member Data Documentation
acceleration_coef_x_
MatrixXd _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::acceleration_coef_x_ private
Definition at line 171 of file piecewise_polynomial_trajectory.hpp.
Referenced by setPolynomialCoefficientMatrices(), updateUserDefinedTrajectory(), and updateUserDefinedYaw().
acceleration_coef_y_
MatrixXd _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::acceleration_coef_y_ private
Definition at line 172 of file piecewise_polynomial_trajectory.hpp.
Referenced by setPolynomialCoefficientMatrices(), updateUserDefinedTrajectory(), and updateUserDefinedYaw().
acceleration_coef_z_
MatrixXd _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::acceleration_coef_z_ private
Definition at line 173 of file piecewise_polynomial_trajectory.hpp.
Referenced by setPolynomialCoefficientMatrices(), and updateUserDefinedTrajectory().
flight_params_ptr
flight_params* _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::flight_params_ptr private
Instance of the flight_params_ptr to point to the flight_parameter object in flight_main.cpp
Definition at line 81 of file piecewise_polynomial_trajectory.hpp.
Referenced by polynomialTimeAdjusted(), setPolynomialCoefficientMatrices(), updateUserDefinedTrajectory(), and updateUserDefinedYaw().
internal_time
double _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::internal_time private
Definition at line 147 of file piecewise_polynomial_trajectory.hpp.
Referenced by updateUserDefinedTrajectory(), and updateUserDefinedYaw().
internal_time_adjusted
double _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::internal_time_adjusted private
Definition at line 150 of file piecewise_polynomial_trajectory.hpp.
Referenced by updateUserDefinedTrajectory(), and updateUserDefinedYaw().
jerk_coef_x_
MatrixXd _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::jerk_coef_x_ private
Definition at line 174 of file piecewise_polynomial_trajectory.hpp.
Referenced by setPolynomialCoefficientMatrices(), and updateUserDefinedYaw().
jerk_coef_y_
MatrixXd _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::jerk_coef_y_ private
Definition at line 175 of file piecewise_polynomial_trajectory.hpp.
Referenced by setPolynomialCoefficientMatrices(), and updateUserDefinedYaw().
jerk_coef_z_
MatrixXd _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::jerk_coef_z_ private
Definition at line 176 of file piecewise_polynomial_trajectory.hpp.
Referenced by setPolynomialCoefficientMatrices().
landing_acceleration_coef_z_
const VectorXd _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::landing_acceleration_coef_z_ private
Initial value:
= (VectorXd(6) <<
            -0.0512695312499999,
             0.5126953125,
            -1.640625,
             1.640625,
             0.0,
             0.0
        ).finished()
Definition at line 205 of file piecewise_polynomial_trajectory.hpp.
landing_position_coef_z_
const VectorXd _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::landing_position_coef_z_ private
Initial value:
= (VectorXd(8) <<
            -0.001220703125,
             0.01708984375,
            -0.0820312499999999,
             0.13671875,
             0.0,
             0.0,
             0.0,
            -1.0
        ).finished()
Position polynomial coefficients for LANDING from (X, Y, -1) to (X, Y, 0) in 4 seconds.
Definition at line 182 of file piecewise_polynomial_trajectory.hpp.
Referenced by updateUserDefinedTrajectory().
landing_velocity_coef_z_
const VectorXd _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::landing_velocity_coef_z_ private
Initial value:
= (VectorXd(7) <<
            -0.00854492187499999,
             0.1025390625,
            -0.41015625,
             0.546874999999999,
             0.0,
             0.0,
             0.0
        ).finished()
Definition at line 194 of file piecewise_polynomial_trajectory.hpp.
Referenced by updateUserDefinedTrajectory().
norm_velocity_XY_
double _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::norm_velocity_XY_ private
Definition at line 162 of file piecewise_polynomial_trajectory.hpp.
Referenced by updateUserDefinedYaw().
position_coef_x_
MatrixXd _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::position_coef_x_ private
Definition at line 165 of file piecewise_polynomial_trajectory.hpp.
Referenced by setPolynomialCoefficientMatrices(), and updateUserDefinedTrajectory().
position_coef_y_
MatrixXd _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::position_coef_y_ private
Definition at line 166 of file piecewise_polynomial_trajectory.hpp.
Referenced by setPolynomialCoefficientMatrices(), and updateUserDefinedTrajectory().
position_coef_z_
MatrixXd _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::position_coef_z_ private
Definition at line 167 of file piecewise_polynomial_trajectory.hpp.
Referenced by setPolynomialCoefficientMatrices(), and updateUserDefinedTrajectory().
segment_
int _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::segment_ private
Definition at line 153 of file piecewise_polynomial_trajectory.hpp.
Referenced by updateUserDefinedTrajectory(), and updateUserDefinedYaw().
user_defined_position_previous_
Vector3d _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::user_defined_position_previous_ private
Definition at line 156 of file piecewise_polynomial_trajectory.hpp.
Referenced by updateUserDefinedTrajectory().
user_defined_yaw_previous_
double _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::user_defined_yaw_previous_ private
Definition at line 159 of file piecewise_polynomial_trajectory.hpp.
Referenced by updateUserDefinedYaw().
velocity_coef_x_
MatrixXd _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::velocity_coef_x_ private
Definition at line 168 of file piecewise_polynomial_trajectory.hpp.
Referenced by setPolynomialCoefficientMatrices(), updateUserDefinedTrajectory(), and updateUserDefinedYaw().
velocity_coef_y_
MatrixXd _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::velocity_coef_y_ private
Definition at line 169 of file piecewise_polynomial_trajectory.hpp.
Referenced by setPolynomialCoefficientMatrices(), updateUserDefinedTrajectory(), and updateUserDefinedYaw().
velocity_coef_z_
MatrixXd _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::velocity_coef_z_ private
Definition at line 170 of file piecewise_polynomial_trajectory.hpp.
Referenced by setPolynomialCoefficientMatrices(), and updateUserDefinedTrajectory().
The documentation for this class was generated from the following files:
ACSL-flightstack-winged/src/acsl_flight/include/piecewise_polynomial_trajectory/piecewise_polynomial_trajectory.hpp
ACSL-flightstack-winged/src/acsl_flight/src/piecewise_polynomial_trajectory/piecewise_polynomial_trajectory.cpp