ACSL Flightstack-winged Documentation: _rostestdrone_::_pid_::pid_logger Class Reference
_rostestdrone_::_pid_::pid_logger Class Reference
Class to log PID.
#include <PID_TD_logger.hpp>
Public Member Functions
pid_logger (controller_internal_members *cim, controller_integrated_state_members *csm, Eigen::Vector< float, 8 > *control_input, const std::string &controller_log_dir_)
void logInitHeaders ()
Initialize headers.
bool logInitLogging ()
void logLogData ()
Start loggin data.
Public Member Functions inherited from _flight_log_::blackbox
blackbox ()
~blackbox ()
void logInitHeaders ()
bool logInitLogging ()
void logLogData ()
Private Attributes
controller_internal_members * CIM
controller_integrated_state_members * CSM
Eigen::Vector< float, 8 > * cntrl_input
std::string flight_run_log_directory
Additional Inherited Members
Protected Attributes inherited from _flight_log_::blackbox
src::logger logger_logdata
src::logger logger_mocapdata
src::logger logger_viodata
Detailed Description
Class to log PID.
Definition at line 69 of file PID_TD_logger.hpp.
Constructor & Destructor Documentation
pid_logger()
_rostestdrone_::_pid_::pid_logger::pid_logger (controller_internal_members * cim, controller_integrated_state_members * csm, Eigen::Vector< float, 8 > * control_input, const std::string & controller_log_dir_)
Definition at line 59 of file PID_TD_logger.cpp.
References _flightstack_::FLIGHTSTACK_INFO(), and logInitLogging().
Member Function Documentation
logInitHeaders()
void _rostestdrone_::_pid_::pid_logger::logInitHeaders ()
Initialize headers.
Definition at line 69 of file PID_TD_logger.cpp.
References _flight_log_::blackbox::logger_logdata.
Referenced by logInitLogging().
logInitLogging()
bool _rostestdrone_::_pid_::pid_logger::logInitLogging ()
Definition at line 145 of file PID_TD_logger.cpp.
References flight_run_log_directory, _flightstack_::FLIGHTSTACK_ERROR(), _flight_log_::blackbox::logger_logdata, and logInitHeaders().
Referenced by pid_logger().
logLogData()
void _rostestdrone_::_pid_::pid_logger::logLogData ()
Start loggin data.
Definition at line 243 of file PID_TD_logger.cpp.
References _rostestdrone_::_pid_::controller_internal_members::alg_duration, CIM, cntrl_input, CSM, _rostestdrone_::_pid_::controller_internal_members::e_eta, _rostestdrone_::_pid_::controller_integrated_state_members::e_eta_I, _rostestdrone_::_pid_::controller_internal_members::e_eta_rate, _rostestdrone_::_pid_::controller_internal_members::e_tran_pos, _rostestdrone_::_pid_::controller_integrated_state_members::e_tran_pos_I, _rostestdrone_::_pid_::controller_internal_members::e_tran_vel, _rostestdrone_::_pid_::controller_internal_members::eta_rot, _rostestdrone_::_pid_::controller_internal_members::eta_rot_acceleration_d, _rostestdrone_::_pid_::controller_internal_members::eta_rot_d, _rostestdrone_::_pid_::controller_internal_members::eta_rot_rate, _rostestdrone_::_pid_::controller_internal_members::eta_rot_rate_d, _flight_log_::blackbox::logger_logdata, _rostestdrone_::_pid_::controller_internal_members::mu_tran_I, _rostestdrone_::_pid_::controller_internal_members::mu_tran_J, _rostestdrone_::_pid_::controller_internal_members::r_dot_user, _rostestdrone_::_pid_::controller_internal_members::r_user, _rostestdrone_::_pid_::controller_internal_members::t, _rostestdrone_::_pid_::controller_internal_members::Thrust, _rostestdrone_::_pid_::controller_internal_members::u, _rostestdrone_::_pid_::controller_internal_members::x_tran_pos, and _rostestdrone_::_pid_::controller_internal_members::x_tran_vel.
Referenced by _rostestdrone_::_pid_::pid::run().
Member Data Documentation
CIM
controller_internal_members* _rostestdrone_::_pid_::pid_logger::CIM private
Definition at line 92 of file PID_TD_logger.hpp.
Referenced by logLogData().
cntrl_input
Eigen::Vector<float, 8>* _rostestdrone_::_pid_::pid_logger::cntrl_input private
Definition at line 98 of file PID_TD_logger.hpp.
Referenced by logLogData().
CSM
controller_integrated_state_members* _rostestdrone_::_pid_::pid_logger::CSM private
Definition at line 95 of file PID_TD_logger.hpp.
Referenced by logLogData().
flight_run_log_directory
std::string _rostestdrone_::_pid_::pid_logger::flight_run_log_directory private
Definition at line 101 of file PID_TD_logger.hpp.
Referenced by logInitLogging().
The documentation for this class was generated from the following files:
ACSL-flightstack-winged/src/acsl_flight/include/control/platforms/rostestdrone/control_algorithms/PID/PID_TD_logger.hpp
ACSL-flightstack-winged/src/acsl_flight/src/control/platforms/rostestdrone/control_algorithms/PID/PID_TD_logger.cpp