ACSL Flightstack-winged Documentation: _qrbp_::_pid_::pid_logger Class Reference
_qrbp_::_pid_::pid_logger Class Reference
Logger for the pid.
#include <PID_logger.hpp>
Public Member Functions
pid_logger (controller_internal_members *cim, controller_integrated_state_members *csm, Eigen::Vector< float, 8 > *control_input, const std::string &controller_log_dir_)
void logInitHeaders ()
Initializing headers.
bool logInitLogging ()
Initialize logging.
void logLogData ()
logging data
Public Member Functions inherited from _flight_log_::blackbox
blackbox ()
~blackbox ()
void logInitHeaders ()
bool logInitLogging ()
void logLogData ()
Private Attributes
controller_internal_members * CIM
controller_integrated_state_members * CSM
Eigen::Vector< float, 8 > * cntrl_input
std::string flight_run_log_directory
Additional Inherited Members
Protected Attributes inherited from _flight_log_::blackbox
src::logger logger_logdata
src::logger logger_mocapdata
src::logger logger_viodata
Detailed Description
Logger for the pid.
Definition at line 75 of file PID_logger.hpp.
Constructor & Destructor Documentation
pid_logger()
_qrbp_::_pid_::pid_logger::pid_logger (controller_internal_members * cim, controller_integrated_state_members * csm, Eigen::Vector< float, 8 > * control_input, const std::string & controller_log_dir_)
Definition at line 65 of file PID_logger.cpp.
References _flightstack_::FLIGHTSTACK_INFO(), and logInitLogging().
Member Function Documentation
logInitHeaders()
void _qrbp_::_pid_::pid_logger::logInitHeaders ()
Initializing headers.
Parameters
None
Definition at line 75 of file PID_logger.cpp.
References _flight_log_::blackbox::logger_logdata.
Referenced by logInitLogging().
logInitLogging()
bool _qrbp_::_pid_::pid_logger::logInitLogging ()
Initialize logging.
Parameters
None
Definition at line 151 of file PID_logger.cpp.
References flight_run_log_directory, _flightstack_::FLIGHTSTACK_ERROR(), _flight_log_::blackbox::logger_logdata, and logInitHeaders().
Referenced by pid_logger().
logLogData()
void _qrbp_::_pid_::pid_logger::logLogData ()
logging data
Parameters
None
Definition at line 249 of file PID_logger.cpp.
References _qrbp_::_pid_::controller_internal_members::alg_duration, CIM, cntrl_input, CSM, _qrbp_::_pid_::controller_internal_members::e_eta, _qrbp_::_pid_::controller_integrated_state_members::e_eta_I, _qrbp_::_pid_::controller_internal_members::e_eta_rate, _qrbp_::_pid_::controller_internal_members::e_tran_pos, _qrbp_::_pid_::controller_integrated_state_members::e_tran_pos_I, _qrbp_::_pid_::controller_internal_members::e_tran_vel, _qrbp_::_pid_::controller_internal_members::eta_rot, _qrbp_::_pid_::controller_internal_members::eta_rot_acceleration_d, _qrbp_::_pid_::controller_internal_members::eta_rot_d, _qrbp_::_pid_::controller_internal_members::eta_rot_rate, _qrbp_::_pid_::controller_internal_members::eta_rot_rate_d, _flight_log_::blackbox::logger_logdata, _qrbp_::_pid_::controller_internal_members::mu_tran_I, _qrbp_::_pid_::controller_internal_members::mu_tran_J, _qrbp_::_pid_::controller_internal_members::r_dot_user, _qrbp_::_pid_::controller_internal_members::r_user, _qrbp_::_pid_::controller_internal_members::t, _qrbp_::_pid_::controller_internal_members::Thrust, _qrbp_::_pid_::controller_internal_members::u, _qrbp_::_pid_::controller_internal_members::x_tran_pos, and _qrbp_::_pid_::controller_internal_members::x_tran_vel.
Referenced by _qrbp_::_pid_::pid::run().
Member Data Documentation
CIM
controller_internal_members* _qrbp_::_pid_::pid_logger::CIM private
Definition at line 105 of file PID_logger.hpp.
Referenced by logLogData().
cntrl_input
Eigen::Vector<float, 8>* _qrbp_::_pid_::pid_logger::cntrl_input private
Definition at line 111 of file PID_logger.hpp.
Referenced by logLogData().
CSM
controller_integrated_state_members* _qrbp_::_pid_::pid_logger::CSM private
Definition at line 108 of file PID_logger.hpp.
Referenced by logLogData().
flight_run_log_directory
std::string _qrbp_::_pid_::pid_logger::flight_run_log_directory private
Definition at line 114 of file PID_logger.hpp.
Referenced by logInitLogging().
The documentation for this class was generated from the following files:
ACSL-flightstack-winged/src/acsl_flight/include/control/platforms/qrbp/control_algorithms/PID/PID_logger.hpp
ACSL-flightstack-winged/src/acsl_flight/src/control/platforms/qrbp/control_algorithms/PID/PID_logger.cpp