ACSL Flightstack-winged Documentation: _flight_params_::FlightConfigReader Class Reference
_flight_params_::FlightConfigReader Class Reference
#include <flight_params.hpp>
Public Member Functions
FlightConfigReader ()
flight_params readFlightConfig (const std::string &jsonFile)
PiecewisePolynomialTrajectoryInfo readTrajectoryConfig (const std::string &fileName)
void printParameterTable (const flight_params &run_params)
Detailed Description
Definition at line 122 of file flight_params.hpp.
Constructor & Destructor Documentation
FlightConfigReader()
_flight_params_::FlightConfigReader::FlightConfigReader () inline
Definition at line 125 of file flight_params.hpp.
Member Function Documentation
printParameterTable()
void _flight_params_::FlightConfigReader::printParameterTable (const flight_params & run_params)
Definition at line 101 of file flight_params.cpp.
References flight_params::arm_time, COL_WIDTH, COLOR_BLUE, COLOR_GREEN, COLOR_ORANGE, COLOR_RED, COLOR_RESET, flight_params::controller_rate, flight_params::end_time, flight_params::hover_time, flight_params::landing_end_time, flight_params::landing_start_time, flight_params::min_thrust_after_arm, flight_params::mocap, flight_params::start_time, flight_params::user_defined_trajectory_file, and flight_params::vio.
Referenced by main().
readFlightConfig()
flight_params _flight_params_::FlightConfigReader::readFlightConfig (const std::string & jsonFile)
Definition at line 49 of file flight_params.cpp.
References flight_params::arm_time, COLOR_ORANGE, COLOR_RESET, flight_params::controller_rate, COUNTDOWN_TO_FLIGHT_NO_VISION, flight_params::end_time, file(), _flightstack_::FLIGHTSTACK_ERROR(), _flightstack_::FLIGHTSTACK_WARNING(), flight_params::hover_time, flight_params::landing_end_time, flight_params::landing_start_time, flight_params::min_thrust_after_arm, flight_params::mocap, readTrajectoryConfig(), flight_params::start_time, flight_params::traj_params, flight_params::user_defined_trajectory_file, flight_params::vio, and PiecewisePolynomialTrajectoryInfo::waypoint_times_.
Referenced by main().
readTrajectoryConfig()
PiecewisePolynomialTrajectoryInfo _flight_params_::FlightConfigReader::readTrajectoryConfig (const std::string & fileName)
Definition at line 160 of file flight_params.cpp.
References file(), PiecewisePolynomialTrajectoryInfo::num_waypts, PiecewisePolynomialTrajectoryInfo::piecewise_polynomial_coefficients_, and PiecewisePolynomialTrajectoryInfo::waypoint_times_.
Referenced by readFlightConfig().
The documentation for this class was generated from the following files:
ACSL-flightstack-winged/src/acsl_flight/include/flight_params/flight_params.hpp
ACSL-flightstack-winged/src/acsl_flight/src/flight_params/flight_params.cpp