ACSL Flightstack-winged Documentation: _t265_::_vio_::VioT265Node Class Reference
_t265_::_vio_::VioT265Node Class Reference final
VioT265Node class which can recieve position tracking from the Realsense T265.
#include <vio.hpp>
Public Member Functions
VioT265Node (vehicle_states *d, const std::string &global_log_dir)
Constructor.
~VioT265Node ()
Destructor - management at quit time.
LNI::CallbackReturn on_configure (const lc::State &state) override
Callback from transition to "configuring" state.
LNI::CallbackReturn on_activate (const lc::State &state) override
Callback from transition to "activating" state.
LNI::CallbackReturn on_deactivate (const lc::State &state) override
Callback from transistion to "deactivating" state.
LNI::CallbackReturn on_cleanup (const lc::State &state) override
Callback from transition to "unconfigured" state.
LNI::CallbackReturn on_shutdown (const lc::State &state) override
Callback from transition to "shutdown" state.
char * return_serial ()
Returns the serial number of the Intel Realsense T265 camera in use.
Public Member Functions inherited from _flight_log_::blackbox
blackbox ()
~blackbox ()
void logInitHeaders ()
bool logInitLogging ()
void logLogData ()
Private Member Functions
bool set_callback ()
Function to setup the callback for the frames from the T265.
void process_and_publish (const rs2::pose_frame &pose)
Funtion to process and publish the pose data for fustion to the Pixhawk.
void debugVioData2screen ()
Debugger function to output the vio data.
void logInitHeaders ()
Implementing virtual functions from blackbox.
bool logInitLogging ()
void logLogData ()
Private Attributes
std::string t265_serial {}
Serial number of the Intel Realsens t265 camera.
rs2::pipeline pipeline
Pipelines for the Intel Realsense T265 camera.
rs2::pipeline_profile profiles
Obeject for the profiles.
vehicle_states * vehicle_ptr
lc::LifecyclePublisher< px4_msgs::msg::VehicleOdometry >::SharedPtr vio_publisher_
Publisher for publishing the vio message.
vio_states vio_im
Declare variables to store parsed data and declare it as internal members "_im".
std::function< void(const rs2::frame &)> callback
Callback for receiving a state.
Vector3f position_C
Vector3f velocity_C
Vector3f acceleration_C
Vector3f angular_velocity_c
Vector3f angular_velocity_C
Vector3f angular_acceleration_c
Vector3f angular_acceleration_C
Quaternionf t265_quaternion
Quaternionf transformed_quaternion
std::string flight_run_log_directory
Directory for logging mocap data.
Additional Inherited Members
Protected Attributes inherited from _flight_log_::blackbox
src::logger logger_logdata
src::logger logger_mocapdata
src::logger logger_viodata
Detailed Description
VioT265Node class which can recieve position tracking from the Realsense T265.
VioT265Node class which can recieve position tracking from the Realsense T265
Definition at line 164 of file vio.hpp.
Constructor & Destructor Documentation
VioT265Node()
_t265_::_vio_::VioT265Node::VioT265Node (vehicle_states * d, const std::string & global_log_dir)
Constructor.
Constructor which accepts pointers for the vio node.
Parameters
[in] pointer to vehicle states in flight_bridge
[in] string to the global flight run directory
Definition at line 195 of file vio.cpp.
References logInitLogging().
~VioT265Node()
_t265_::_vio_::VioT265Node::~VioT265Node ()
Destructor - management at quit time.
Definition at line 217 of file vio.cpp.
References pipeline, and return_serial().
Member Function Documentation
debugVioData2screen()
void _t265_::_vio_::VioT265Node::debugVioData2screen () private
Debugger function to output the vio data.
Debugger function to output the mocap data.
Definition at line 402 of file vio.cpp.
logInitHeaders()
void _t265_::_vio_::VioT265Node::logInitHeaders () private
Implementing virtual functions from blackbox.
Definition at line 79 of file vio.cpp.
References _flight_log_::blackbox::logger_viodata.
Referenced by logInitLogging().
logInitLogging()
bool _t265_::_vio_::VioT265Node::logInitLogging () private
Definition at line 110 of file vio.cpp.
References flight_run_log_directory, _flightstack_::FLIGHTSTACK_ERROR(), _flight_log_::blackbox::logger_viodata, and logInitHeaders().
Referenced by VioT265Node().
logLogData()
void _t265_::_vio_::VioT265Node::logLogData () private
Definition at line 161 of file vio.cpp.
References _t265_::vio_states::ax, _t265_::vio_states::ay, _t265_::vio_states::az, _t265_::vio_states::control_time, _flight_log_::blackbox::logger_viodata, _t265_::vio_states::mapper_conf, _t265_::vio_states::pitchacceleration, _t265_::vio_states::pitchspeed, _t265_::vio_states::q0, _t265_::vio_states::q1, _t265_::vio_states::q2, _t265_::vio_states::q3, _t265_::vio_states::rollacceleration, _t265_::vio_states::rollspeed, _t265_::vio_states::tracker_conf, vio_im, _t265_::vio_states::vx, _t265_::vio_states::vy, _t265_::vio_states::vz, _t265_::vio_states::x, _t265_::vio_states::y, _t265_::vio_states::yawacceleration, _t265_::vio_states::yawspeed, and _t265_::vio_states::z.
on_activate()
LNI::CallbackReturn _t265_::_vio_::VioT265Node::on_activate (const lc::State & state) override
Callback from transition to "activating" state.
Parameters
[in] state The current state that the node is in.
Definition at line 362 of file vio.cpp.
References vio_publisher_.
on_cleanup()
LNI::CallbackReturn _t265_::_vio_::VioT265Node::on_cleanup (const lc::State & state) override
Callback from transition to "unconfigured" state.
Parameters
[in] state The current state that the node is in.
Definition at line 384 of file vio.cpp.
References vio_publisher_.
on_configure()
LNI::CallbackReturn _t265_::_vio_::VioT265Node::on_configure (const lc::State & state) override
Callback from transition to "configuring" state.
Parameters
[in] state The current state that the node is in.
Definition at line 243 of file vio.cpp.
References callback, CAMERA_ONE, CAMERA_TWO, pipeline, profiles, return_serial(), set_callback(), and vio_publisher_.
on_deactivate()
LNI::CallbackReturn _t265_::_vio_::VioT265Node::on_deactivate (const lc::State & state) override
Callback from transistion to "deactivating" state.
Callback from transition to "deactivating" state.
Parameters
[in] state The current state that the node is in.
Definition at line 373 of file vio.cpp.
References vio_publisher_.
on_shutdown()
LNI::CallbackReturn _t265_::_vio_::VioT265Node::on_shutdown (const lc::State & state) override
Callback from transition to "shutdown" state.
Parameters
[in] state The current state that the node is in.
Definition at line 394 of file vio.cpp.
process_and_publish()
void _t265_::_vio_::VioT265Node::process_and_publish (const rs2::pose_frame & pose) private
Funtion to process and publish the pose data for fustion to the Pixhawk.
Definition at line 433 of file vio.cpp.
References acceleration_C, angular_acceleration_c, angular_acceleration_C, angular_velocity_c, angular_velocity_C, _t265_::vio_states::ax, _t265_::vio_states::ay, _t265_::vio_states::az, _t265_::vio_states::control_time, vehicle_states::get_controltime(), _t265_::vio_states::mapper_conf, _t265_::vio_states::pitchacceleration, _t265_::vio_states::pitchspeed, POSE_FRAME_NED, position_C, _t265_::vio_states::q0, _t265_::vio_states::q1, _t265_::vio_states::q2, _t265_::vio_states::q3, q_J_c_inv, R_c_C, _t265_::vio_states::rollacceleration, _t265_::vio_states::rollspeed, t265_quaternion, _t265_::vio_states::tracker_conf, transformed_quaternion, vehicle_ptr, velocity_C, VELOCITY_FRAME_NED, vio_im, _t265_::vio_states::vx, _t265_::vio_states::vy, _t265_::vio_states::vz, _t265_::vio_states::x, _t265_::vio_states::y, _t265_::vio_states::yawacceleration, _t265_::vio_states::yawspeed, and _t265_::vio_states::z.
Referenced by set_callback().
return_serial()
char * _t265_::_vio_::VioT265Node::return_serial ()
Returns the serial number of the Intel Realsense T265 camera in use.
Get the parameters for the serial number of the T265 in use.
Definition at line 206 of file vio.cpp.
References SERIAL_NUMBER, and t265_serial.
Referenced by on_configure(), and ~VioT265Node().
set_callback()
bool _t265_::_vio_::VioT265Node::set_callback () private
Function to setup the callback for the frames from the T265.
Definition at line 408 of file vio.cpp.
References callback, _flightstack_::FLIGHTSTACK_ERROR(), and process_and_publish().
Referenced by on_configure().
Member Data Documentation
acceleration_C
Vector3f _t265_::_vio_::VioT265Node::acceleration_C private
Definition at line 239 of file vio.hpp.
Referenced by process_and_publish().
angular_acceleration_c
Vector3f _t265_::_vio_::VioT265Node::angular_acceleration_c private
Definition at line 242 of file vio.hpp.
Referenced by process_and_publish().
angular_acceleration_C
Vector3f _t265_::_vio_::VioT265Node::angular_acceleration_C private
Definition at line 243 of file vio.hpp.
Referenced by process_and_publish().
angular_velocity_c
Vector3f _t265_::_vio_::VioT265Node::angular_velocity_c private
Definition at line 240 of file vio.hpp.
Referenced by process_and_publish().
angular_velocity_C
Vector3f _t265_::_vio_::VioT265Node::angular_velocity_C private
Definition at line 241 of file vio.hpp.
Referenced by process_and_publish().
callback
std::function<void(const rs2::frame&)> _t265_::_vio_::VioT265Node::callback private
Callback for receiving a state.
Definition at line 223 of file vio.hpp.
Referenced by on_configure(), and set_callback().
flight_run_log_directory
std::string _t265_::_vio_::VioT265Node::flight_run_log_directory private
Directory for logging mocap data.
Definition at line 248 of file vio.hpp.
Referenced by logInitLogging().
pipeline
rs2::pipeline _t265_::_vio_::VioT265Node::pipeline private
Pipelines for the Intel Realsense T265 camera.
Definition at line 204 of file vio.hpp.
Referenced by on_configure(), and ~VioT265Node().
position_C
Vector3f _t265_::_vio_::VioT265Node::position_C private
Definition at line 237 of file vio.hpp.
Referenced by process_and_publish().
profiles
rs2::pipeline_profile _t265_::_vio_::VioT265Node::profiles private
Obeject for the profiles.
Definition at line 207 of file vio.hpp.
Referenced by on_configure().
t265_quaternion
Quaternionf _t265_::_vio_::VioT265Node::t265_quaternion private
Definition at line 244 of file vio.hpp.
Referenced by process_and_publish().
t265_serial
std::string _t265_::_vio_::VioT265Node::t265_serial {} private
Serial number of the Intel Realsens t265 camera.
Definition at line 201 of file vio.hpp.
Referenced by return_serial().
transformed_quaternion
Quaternionf _t265_::_vio_::VioT265Node::transformed_quaternion private
Definition at line 245 of file vio.hpp.
Referenced by process_and_publish().
vehicle_ptr
vehicle_states* _t265_::_vio_::VioT265Node::vehicle_ptr private
Instance of the vehicle_ptr to point to the vehicle state object in flight_bridge.cpp
Definition at line 211 of file vio.hpp.
Referenced by process_and_publish().
velocity_C
Vector3f _t265_::_vio_::VioT265Node::velocity_C private
Definition at line 238 of file vio.hpp.
Referenced by process_and_publish().
vio_im
vio_states _t265_::_vio_::VioT265Node::vio_im private
Declare variables to store parsed data and declare it as internal members "_im".
Definition at line 217 of file vio.hpp.
Referenced by logLogData(), and process_and_publish().
vio_publisher_
lc::LifecyclePublisher<px4_msgs::msg::VehicleOdometry>::SharedPtr _t265_::_vio_::VioT265Node::vio_publisher_ private
Publisher for publishing the vio message.
Definition at line 214 of file vio.hpp.
Referenced by on_activate(), on_cleanup(), on_configure(), and on_deactivate().
The documentation for this class was generated from the following files:
ACSL-flightstack-winged/src/acsl_flight/include/vio/vio.hpp
ACSL-flightstack-winged/src/acsl_flight/src/vio/vio.cpp