ACSL Flightstack-winged Documentation: _user_defined_trajectory_base_::trajectory_base Class Reference
_user_defined_trajectory_base_::trajectory_base Class Reference
base trajectory for pixhawk
#include <user_defined_trajectory_base.hpp>
Public Member Functions
trajectory_base ()
const Vector3d & getUserDefinedPosition () const
Get the User Defined Position object.
void setUserDefinedPosition (const Vector3d &pos)
Set the User Defined Position object.
const Vector3d & getUserDefinedVelocity () const
Get the User Defined Velocity object.
void setUserDefinedVelocity (const Vector3d &vel)
Set the User Defined Velocity object.
const Vector3d & getUserDefinedAcceleration () const
Get the User Defined Acceleration object.
void setUserDefinedAcceleration (const Vector3d &acc)
Set the User Defined Acceleration object.
const Vector3d & getUserDefinedAngle () const
void setUserDefinedAngle (const Vector3d &angle)
void setUserDefinedRoll (double x)
Set the User Defined Roll object.
void setUserDefinedPitch (double y)
Set the User Defined Pitch object.
void setUserDefinedYaw (double z)
Set the User Defined Yaw object.
double getUserDefinedRoll () const
Get the User Defined Roll object.
double getUserDefinedPitch () const
Get the User Defined Pitch object.
double getUserDefinedYaw () const
Get the User Defined Yaw object.
const Vector3d & getUserDefinedAngularRate () const
Get the User Defined Angular Rate object.
void setUserDefinedAngularRate (const Vector3d &angular_rate)
Set the User Defined Angular Rate object.
void setUserDefinedRollRate (double x)
void setUserDefinedPitchRate (double y)
void setUserDefinedYawRate (double z)
double getUserDefinedRollRate () const
double getUserDefinedPitchRate () const
double getUserDefinedYawRate () const
const Vector3d & getUserDefinedAngularRateDot () const
void setUserDefinedAngularRateDot (const Vector3d &ang_rt_dot)
void setUserDefinedRollRateDot (double x)
void setUserDefinedPitchRateDot (double y)
void setUserDefinedYawRateDot (double z)
double getUserDefinedRollRateDot () const
double getUserDefinedPitchRateDot () const
double getUserDefinedYawRateDot () const
const Vector3d & getUserDefinedAngularVelocity () const
void setUserDefinedAngularVelocity (const Vector3d &angular_vel)
void setUserDefinedOmegaX (double x)
void setUserDefinedOmegaY (double y)
void setUserDefinedOmegaZ (double z)
double getUserDefinedOmegaX () const
double getUserDefinedOmegaY () const
double getUserDefinedOmegaZ () const
const Vector3d & getUserDefinedAngularAcceleration () const
void setUserDefinedAngularAcceleration (const Vector3d &angular_acc)
void setUserDefinedAlphaX (double x)
void setUserDefinedAlphaY (double y)
void setUserDefinedAlphaZ (double z)
double getUserDefinedAlphaX () const
double getUserDefinedAlphaY () const
double getUserDefinedAlphaZ () const
Protected Attributes
Vector3d ud_pos
Vector3d ud_vel
Vector3d ud_acc
Vector3d ud_angle
Vector3d ud_angular_rate
Vector3d ud_angular_rate_dot
Vector3d ud_angular_vel
Vector3d ud_angular_acc
Detailed Description
base trajectory for pixhawk
Definition at line 62 of file user_defined_trajectory_base.hpp.
Constructor & Destructor Documentation
trajectory_base()
_user_defined_trajectory_base_::trajectory_base::trajectory_base () inline
Definition at line 67 of file user_defined_trajectory_base.hpp.
Member Function Documentation
getUserDefinedAcceleration()
const Vector3d& _user_defined_trajectory_base_::trajectory_base::getUserDefinedAcceleration () const inline
Get the User Defined Acceleration object.
Parameters
None
Returns
const Vector3d&
Definition at line 110 of file user_defined_trajectory_base.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::update(), _qrbp_::_mrac_pid_::mrac_pid::update(), _qrbp_::_pid_::pid::update(), _qrbp_::_pid_omega_::pid_omega::update(), and _rostestdrone_::_pid_::pid::update().
getUserDefinedAlphaX()
double _user_defined_trajectory_base_::trajectory_base::getUserDefinedAlphaX () const inline
Definition at line 213 of file user_defined_trajectory_base.hpp.
getUserDefinedAlphaY()
double _user_defined_trajectory_base_::trajectory_base::getUserDefinedAlphaY () const inline
Definition at line 214 of file user_defined_trajectory_base.hpp.
getUserDefinedAlphaZ()
double _user_defined_trajectory_base_::trajectory_base::getUserDefinedAlphaZ () const inline
Definition at line 215 of file user_defined_trajectory_base.hpp.
getUserDefinedAngle()
const Vector3d& _user_defined_trajectory_base_::trajectory_base::getUserDefinedAngle () const inline
Definition at line 119 of file user_defined_trajectory_base.hpp.
getUserDefinedAngularAcceleration()
const Vector3d& _user_defined_trajectory_base_::trajectory_base::getUserDefinedAngularAcceleration () const inline
Definition at line 206 of file user_defined_trajectory_base.hpp.
getUserDefinedAngularRate()
const Vector3d& _user_defined_trajectory_base_::trajectory_base::getUserDefinedAngularRate () const inline
Get the User Defined Angular Rate object.
Parameters
None
Returns
const Vector3d&
Definition at line 165 of file user_defined_trajectory_base.hpp.
getUserDefinedAngularRateDot()
const Vector3d& _user_defined_trajectory_base_::trajectory_base::getUserDefinedAngularRateDot () const inline
Definition at line 182 of file user_defined_trajectory_base.hpp.
getUserDefinedAngularVelocity()
const Vector3d& _user_defined_trajectory_base_::trajectory_base::getUserDefinedAngularVelocity () const inline
Definition at line 194 of file user_defined_trajectory_base.hpp.
getUserDefinedOmegaX()
double _user_defined_trajectory_base_::trajectory_base::getUserDefinedOmegaX () const inline
Definition at line 201 of file user_defined_trajectory_base.hpp.
getUserDefinedOmegaY()
double _user_defined_trajectory_base_::trajectory_base::getUserDefinedOmegaY () const inline
Definition at line 202 of file user_defined_trajectory_base.hpp.
getUserDefinedOmegaZ()
double _user_defined_trajectory_base_::trajectory_base::getUserDefinedOmegaZ () const inline
Definition at line 203 of file user_defined_trajectory_base.hpp.
getUserDefinedPitch()
double _user_defined_trajectory_base_::trajectory_base::getUserDefinedPitch () const inline
Get the User Defined Pitch object.
Returns
double
Definition at line 151 of file user_defined_trajectory_base.hpp.
getUserDefinedPitchRate()
double _user_defined_trajectory_base_::trajectory_base::getUserDefinedPitchRate () const inline
Definition at line 178 of file user_defined_trajectory_base.hpp.
getUserDefinedPitchRateDot()
double _user_defined_trajectory_base_::trajectory_base::getUserDefinedPitchRateDot () const inline
Definition at line 190 of file user_defined_trajectory_base.hpp.
getUserDefinedPosition()
const Vector3d& _user_defined_trajectory_base_::trajectory_base::getUserDefinedPosition () const inline
Get the User Defined Position object.
Parameters
None
Returns
const Vector3d&
Definition at line 82 of file user_defined_trajectory_base.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::update(), _qrbp_::_mrac_pid_::mrac_pid::update(), _qrbp_::_pid_::pid::update(), _qrbp_::_pid_omega_::pid_omega::update(), _rostestdrone_::_pid_::pid::update(), and _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::updateUserDefinedTrajectory().
getUserDefinedRoll()
double _user_defined_trajectory_base_::trajectory_base::getUserDefinedRoll () const inline
Get the User Defined Roll object.
Returns
double
Definition at line 145 of file user_defined_trajectory_base.hpp.
getUserDefinedRollRate()
double _user_defined_trajectory_base_::trajectory_base::getUserDefinedRollRate () const inline
Definition at line 177 of file user_defined_trajectory_base.hpp.
getUserDefinedRollRateDot()
double _user_defined_trajectory_base_::trajectory_base::getUserDefinedRollRateDot () const inline
Definition at line 189 of file user_defined_trajectory_base.hpp.
getUserDefinedVelocity()
const Vector3d& _user_defined_trajectory_base_::trajectory_base::getUserDefinedVelocity () const inline
Get the User Defined Velocity object.
Parameters
None
Returns
const Vector3d&
Definition at line 96 of file user_defined_trajectory_base.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::update(), _qrbp_::_mrac_pid_::mrac_pid::update(), _qrbp_::_pid_::pid::update(), _qrbp_::_pid_omega_::pid_omega::update(), and _rostestdrone_::_pid_::pid::update().
getUserDefinedYaw()
double _user_defined_trajectory_base_::trajectory_base::getUserDefinedYaw () const inline
Get the User Defined Yaw object.
Returns
double
Definition at line 157 of file user_defined_trajectory_base.hpp.
Referenced by _qrbp_::_mrac_pid_::mrac_pid::compute_u1_eta_d(), _qrbp_::_pid_::pid::update(), _qrbp_::_pid_omega_::pid_omega::update(), _rostestdrone_::_pid_::pid::update(), and _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::updateUserDefinedYaw().
getUserDefinedYawRate()
double _user_defined_trajectory_base_::trajectory_base::getUserDefinedYawRate () const inline
Definition at line 179 of file user_defined_trajectory_base.hpp.
Referenced by _qrbp_::_mrac_pid_::mrac_pid::compute_u1_eta_d(), _qrbp_::_pid_::pid::update(), _qrbp_::_pid_omega_::pid_omega::update(), and _rostestdrone_::_pid_::pid::update().
getUserDefinedYawRateDot()
double _user_defined_trajectory_base_::trajectory_base::getUserDefinedYawRateDot () const inline
Definition at line 191 of file user_defined_trajectory_base.hpp.
Referenced by _qrbp_::_mrac_pid_::mrac_pid::compute_u1_eta_d(), _qrbp_::_pid_::pid::update(), and _rostestdrone_::_pid_::pid::update().
setUserDefinedAcceleration()
void _user_defined_trajectory_base_::trajectory_base::setUserDefinedAcceleration (const Vector3d & acc) inline
Set the User Defined Acceleration object.
Parameters
acc
Definition at line 116 of file user_defined_trajectory_base.hpp.
Referenced by _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::updateUserDefinedTrajectory().
setUserDefinedAlphaX()
void _user_defined_trajectory_base_::trajectory_base::setUserDefinedAlphaX (double x) inline
Definition at line 210 of file user_defined_trajectory_base.hpp.
setUserDefinedAlphaY()
void _user_defined_trajectory_base_::trajectory_base::setUserDefinedAlphaY (double y) inline
Definition at line 211 of file user_defined_trajectory_base.hpp.
setUserDefinedAlphaZ()
void _user_defined_trajectory_base_::trajectory_base::setUserDefinedAlphaZ (double z) inline
Definition at line 212 of file user_defined_trajectory_base.hpp.
setUserDefinedAngle()
void _user_defined_trajectory_base_::trajectory_base::setUserDefinedAngle (const Vector3d & angle) inline
Definition at line 120 of file user_defined_trajectory_base.hpp.
setUserDefinedAngularAcceleration()
void _user_defined_trajectory_base_::trajectory_base::setUserDefinedAngularAcceleration (const Vector3d & angular_acc) inline
Definition at line 207 of file user_defined_trajectory_base.hpp.
setUserDefinedAngularRate()
void _user_defined_trajectory_base_::trajectory_base::setUserDefinedAngularRate (const Vector3d & angular_rate) inline
Set the User Defined Angular Rate object.
Parameters
angular_rate
Definition at line 171 of file user_defined_trajectory_base.hpp.
setUserDefinedAngularRateDot()
void _user_defined_trajectory_base_::trajectory_base::setUserDefinedAngularRateDot (const Vector3d & ang_rt_dot) inline
Definition at line 183 of file user_defined_trajectory_base.hpp.
setUserDefinedAngularVelocity()
void _user_defined_trajectory_base_::trajectory_base::setUserDefinedAngularVelocity (const Vector3d & angular_vel) inline
Definition at line 195 of file user_defined_trajectory_base.hpp.
setUserDefinedOmegaX()
void _user_defined_trajectory_base_::trajectory_base::setUserDefinedOmegaX (double x) inline
Definition at line 198 of file user_defined_trajectory_base.hpp.
setUserDefinedOmegaY()
void _user_defined_trajectory_base_::trajectory_base::setUserDefinedOmegaY (double y) inline
Definition at line 199 of file user_defined_trajectory_base.hpp.
setUserDefinedOmegaZ()
void _user_defined_trajectory_base_::trajectory_base::setUserDefinedOmegaZ (double z) inline
Definition at line 200 of file user_defined_trajectory_base.hpp.
setUserDefinedPitch()
void _user_defined_trajectory_base_::trajectory_base::setUserDefinedPitch (double y) inline
Set the User Defined Pitch object.
Parameters
y
Definition at line 133 of file user_defined_trajectory_base.hpp.
setUserDefinedPitchRate()
void _user_defined_trajectory_base_::trajectory_base::setUserDefinedPitchRate (double y) inline
Definition at line 175 of file user_defined_trajectory_base.hpp.
setUserDefinedPitchRateDot()
void _user_defined_trajectory_base_::trajectory_base::setUserDefinedPitchRateDot (double y) inline
Definition at line 187 of file user_defined_trajectory_base.hpp.
setUserDefinedPosition()
void _user_defined_trajectory_base_::trajectory_base::setUserDefinedPosition (const Vector3d & pos) inline
Set the User Defined Position object.
Parameters
pos
Definition at line 88 of file user_defined_trajectory_base.hpp.
Referenced by _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::updateUserDefinedTrajectory().
setUserDefinedRoll()
void _user_defined_trajectory_base_::trajectory_base::setUserDefinedRoll (double x) inline
Set the User Defined Roll object.
Parameters
x
Definition at line 127 of file user_defined_trajectory_base.hpp.
setUserDefinedRollRate()
void _user_defined_trajectory_base_::trajectory_base::setUserDefinedRollRate (double x) inline
Definition at line 174 of file user_defined_trajectory_base.hpp.
setUserDefinedRollRateDot()
void _user_defined_trajectory_base_::trajectory_base::setUserDefinedRollRateDot (double x) inline
Definition at line 186 of file user_defined_trajectory_base.hpp.
setUserDefinedVelocity()
void _user_defined_trajectory_base_::trajectory_base::setUserDefinedVelocity (const Vector3d & vel) inline
Set the User Defined Velocity object.
Parameters
vel
Definition at line 102 of file user_defined_trajectory_base.hpp.
Referenced by _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::updateUserDefinedTrajectory().
setUserDefinedYaw()
void _user_defined_trajectory_base_::trajectory_base::setUserDefinedYaw (double z) inline
Set the User Defined Yaw object.
Parameters
z
Definition at line 139 of file user_defined_trajectory_base.hpp.
Referenced by _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::updateUserDefinedYaw().
setUserDefinedYawRate()
void _user_defined_trajectory_base_::trajectory_base::setUserDefinedYawRate (double z) inline
Definition at line 176 of file user_defined_trajectory_base.hpp.
Referenced by _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::updateUserDefinedYaw().
setUserDefinedYawRateDot()
void _user_defined_trajectory_base_::trajectory_base::setUserDefinedYawRateDot (double z) inline
Definition at line 188 of file user_defined_trajectory_base.hpp.
Referenced by _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::updateUserDefinedYaw().
Member Data Documentation
ud_acc
Vector3d _user_defined_trajectory_base_::trajectory_base::ud_acc protected
Definition at line 230 of file user_defined_trajectory_base.hpp.
ud_angle
Vector3d _user_defined_trajectory_base_::trajectory_base::ud_angle protected
Definition at line 233 of file user_defined_trajectory_base.hpp.
ud_angular_acc
Vector3d _user_defined_trajectory_base_::trajectory_base::ud_angular_acc protected
Definition at line 245 of file user_defined_trajectory_base.hpp.
ud_angular_rate
Vector3d _user_defined_trajectory_base_::trajectory_base::ud_angular_rate protected
Definition at line 236 of file user_defined_trajectory_base.hpp.
ud_angular_rate_dot
Vector3d _user_defined_trajectory_base_::trajectory_base::ud_angular_rate_dot protected
Definition at line 239 of file user_defined_trajectory_base.hpp.
ud_angular_vel
Vector3d _user_defined_trajectory_base_::trajectory_base::ud_angular_vel protected
Definition at line 242 of file user_defined_trajectory_base.hpp.
ud_pos
Vector3d _user_defined_trajectory_base_::trajectory_base::ud_pos protected
Definition at line 224 of file user_defined_trajectory_base.hpp.
ud_vel
Vector3d _user_defined_trajectory_base_::trajectory_base::ud_vel protected
Definition at line 227 of file user_defined_trajectory_base.hpp.
The documentation for this class was generated from the following file:
ACSL-flightstack-winged/src/acsl_flight/include/utils/user_defined_trajectory_base/user_defined_trajectory_base.hpp