ACSL Flightstack-winged Documentation: _qrbp_::_mrac_pid_::mrac_pid_logger Class Reference
_qrbp_::_mrac_pid_::mrac_pid_logger Class Reference
#include <MRAC_PID_logger.hpp>
Public Member Functions
mrac_pid_logger (controller_internal_members *cim, controller_integrated_state_members *csm, Eigen::Vector< float, 8 > *control_input, const std::string &controller_log_dir_)
void logInitHeaders ()
Implementing functions from blackbox.
bool logInitLogging ()
void logLogData ()
Public Member Functions inherited from _flight_log_::blackbox
blackbox ()
~blackbox ()
void logInitHeaders ()
bool logInitLogging ()
void logLogData ()
Private Attributes
controller_internal_members * CIM
controller_integrated_state_members * CSM
Eigen::Vector< float, 8 > * cntrl_input
std::string flight_run_log_directory
Additional Inherited Members
Protected Attributes inherited from _flight_log_::blackbox
src::logger logger_logdata
src::logger logger_mocapdata
src::logger logger_viodata
Detailed Description
Definition at line 75 of file MRAC_PID_logger.hpp.
Constructor & Destructor Documentation
mrac_pid_logger()
_qrbp_::_mrac_pid_::mrac_pid_logger::mrac_pid_logger (controller_internal_members * cim, controller_integrated_state_members * csm, Eigen::Vector< float, 8 > * control_input, const std::string & controller_log_dir_)
Definition at line 67 of file MRAC_PID_logger.cpp.
References _flightstack_::FLIGHTSTACK_INFO(), and logInitLogging().
Member Function Documentation
logInitHeaders()
void _qrbp_::_mrac_pid_::mrac_pid_logger::logInitHeaders ()
Implementing functions from blackbox.
Definition at line 77 of file MRAC_PID_logger.cpp.
References _flight_log_::blackbox::logger_logdata.
Referenced by logInitLogging().
logInitLogging()
bool _qrbp_::_mrac_pid_::mrac_pid_logger::logInitLogging ()
Definition at line 228 of file MRAC_PID_logger.cpp.
References flight_run_log_directory, _flightstack_::FLIGHTSTACK_ERROR(), _flight_log_::blackbox::logger_logdata, and logInitHeaders().
Referenced by mrac_pid_logger().
logLogData()
void _qrbp_::_mrac_pid_::mrac_pid_logger::logLogData ()
Definition at line 326 of file MRAC_PID_logger.cpp.
References _qrbp_::_mrac_pid_::controller_internal_members::aero, _qrbp_::_mrac_pid_::controller_internal_members::alg_duration, _qrbp_::AeroCoeff::Cd_lt, _qrbp_::AeroCoeff::Cd_lw, _qrbp_::AeroCoeff::Cd_rt, _qrbp_::AeroCoeff::Cd_up, CIM, _qrbp_::AeroCoeff::Cl_lt, _qrbp_::AeroCoeff::Cl_lw, _qrbp_::AeroCoeff::Cl_rt, _qrbp_::AeroCoeff::Cl_up, _qrbp_::AeroCoeff::Cm_lt, _qrbp_::AeroCoeff::Cm_lw, _qrbp_::AeroCoeff::Cm_rt, _qrbp_::AeroCoeff::Cm_up, cntrl_input, _qrbp_::_mrac_pid_::controller_internal_members_aero::coeff, CSM, _qrbp_::_mrac_pid_::controller_internal_members_aero::dyn, _qrbp_::_mrac_pid_::controller_internal_members::e_eta, _qrbp_::_mrac_pid_::controller_integrated_state_members::e_eta_I, _qrbp_::_mrac_pid_::controller_internal_members::e_eta_rate, _qrbp_::_mrac_pid_::controller_internal_members::e_omega, _qrbp_::_mrac_pid_::controller_internal_members::e_omega_ref, _qrbp_::_mrac_pid_::controller_integrated_state_members::e_omega_ref_I, _qrbp_::_mrac_pid_::controller_internal_members::e_tran, _qrbp_::_mrac_pid_::controller_integrated_state_members::e_tran_pos_I, _qrbp_::_mrac_pid_::controller_internal_members::e_tran_pos_ref, _qrbp_::_mrac_pid_::controller_integrated_state_members::e_tran_pos_ref_I, _qrbp_::_mrac_pid_::controller_internal_members::eta_rot, _qrbp_::_mrac_pid_::controller_internal_members::eta_rot_b, _qrbp_::_mrac_pid_::controller_internal_members::eta_rot_d, _qrbp_::_mrac_pid_::controller_internal_members::eta_rot_q, _qrbp_::_mrac_pid_::controller_internal_members::eta_rot_rate, _qrbp_::_mrac_pid_::controller_internal_members::eta_rot_rate_d, _qrbp_::AeroDynamicMembers::inner_loop_dynamic_inv, _qrbp_::is_biplane, _flight_log_::blackbox::logger_logdata, _qrbp_::momentary_button, _qrbp_::_mrac_pid_::controller_internal_members::mu_tran_adaptive, _qrbp_::_mrac_pid_::controller_internal_members::mu_tran_baseline, _qrbp_::_mrac_pid_::controller_internal_members::mu_tran_J, _qrbp_::_mrac_pid_::controller_internal_members::omega_cmd_rot, _qrbp_::_mrac_pid_::controller_internal_members::omega_ref_dot_rot, _qrbp_::_mrac_pid_::controller_integrated_state_members::omega_ref_rot, _qrbp_::_mrac_pid_::controller_internal_members::omega_rot, _qrbp_::AeroDynamicMembers::outer_loop_dynamic_inv, _qrbp_::_mrac_pid_::controller_internal_members::r_cmd_tran, _qrbp_::_mrac_pid_::controller_internal_members::r_ddot_user, _qrbp_::_mrac_pid_::controller_internal_members::r_dot_user, _qrbp_::_mrac_pid_::controller_internal_members::r_user, _qrbp_::_mrac_pid_::controller_internal_members_aero::states, _qrbp_::_mrac_pid_::controller_internal_members::t, _qrbp_::_mrac_pid_::controller_internal_members::tau_rot_adaptive, _qrbp_::_mrac_pid_::controller_internal_members::tau_rot_baseline, _qrbp_::_mrac_pid_::controller_internal_members::Thrust, _qrbp_::_mrac_pid_::controller_internal_members::u, _qrbp_::AeroStates::v_norm_sq, _qrbp_::_mrac_pid_::controller_internal_members::x_tran, _qrbp_::_mrac_pid_::controller_integrated_state_members::x_tran_ref, and _qrbp_::_mrac_pid_::controller_internal_members::x_tran_ref_dot.
Referenced by _qrbp_::_mrac_pid_::mrac_pid::run().
Member Data Documentation
CIM
controller_internal_members* _qrbp_::_mrac_pid_::mrac_pid_logger::CIM private
Definition at line 94 of file MRAC_PID_logger.hpp.
Referenced by logLogData().
cntrl_input
Eigen::Vector<float, 8>* _qrbp_::_mrac_pid_::mrac_pid_logger::cntrl_input private
Definition at line 100 of file MRAC_PID_logger.hpp.
Referenced by logLogData().
CSM
controller_integrated_state_members* _qrbp_::_mrac_pid_::mrac_pid_logger::CSM private
Definition at line 97 of file MRAC_PID_logger.hpp.
Referenced by logLogData().
flight_run_log_directory
std::string _qrbp_::_mrac_pid_::mrac_pid_logger::flight_run_log_directory private
Definition at line 103 of file MRAC_PID_logger.hpp.
Referenced by logInitLogging().
The documentation for this class was generated from the following files:
ACSL-flightstack-winged/src/acsl_flight/include/control/platforms/qrbp/control_algorithms/MRAC_PID/MRAC_PID_logger.hpp
ACSL-flightstack-winged/src/acsl_flight/src/control/platforms/qrbp/control_algorithms/MRAC_PID/MRAC_PID_logger.cpp