ACSL Flightstack-winged Documentation: _qrbp_::_pid_omega_::pid_omega Class Reference
_qrbp_::_pid_omega_::pid_omega Class Reference
public controller_base
#include <PID_OMEGA.hpp>
Public Member Functions
pid_omega (flight_params *p, const std::string &controller_log_dir_)
~pid_omega ()
void run (const double time_step_rk4_)
Run function.
void update (double time, double x, double y, double z, double vx, double vy, double vz, double q0, double q1, double q2, double q3, double roll, double pitch, double yaw, double w_x, double w_y, double w_z)
Update function.
float get_t1 () const
float get_t2 () const
float get_t3 () const
float get_t4 () const
float get_t5 () const
float get_t6 () const
float get_t7 () const
float get_t8 () const
Public Member Functions inherited from _control_algorithm_base_::controller_base
controller_base (flight_params *p)
~controller_base ()
void read_params ([[maybe_unused]] const std::string &jsonFile)
Read parameters.
void init ()
Initialize initial conditions.
void update ([[maybe_unused]] double time, [[maybe_unused]] double x, [[maybe_unused]] double y, [[maybe_unused]] double z, [[maybe_unused]] double vx, [[maybe_unused]] double vy, [[maybe_unused]] double vz, [[maybe_unused]] double q0, [[maybe_unused]] double q1, [[maybe_unused]] double q2, [[maybe_unused]] double q3, [[maybe_unused]] double roll, [[maybe_unused]] double pitch, [[maybe_unused]] double yaw, [[maybe_unused]] double w_x, [[maybe_unused]] double w_y, [[maybe_unused]] double w_z)
Controller Update state and trajectory.
void run ([[maybe_unused]] const double time_step_rk4_)
Controller run.
float get_t1 () const
float get_t2 () const
float get_t3 () const
float get_t4 () const
float get_t5 () const
float get_t6 () const
float get_t7 () const
float get_t8 () const
Private Member Functions
void read_params (const std::string &jsonFile)
Reading params from json file.
void init ()
Init function.
void model (const rk4_array< double, NSI > &y, rk4_array< double, NSI > &dy, double t)
Defining the model.
void compute_translational_control_in_I ()
void compute_u1_eta_d ()
void compute_rotational_control ()
void compute_normalized_thrusts ()
void assign_from_rk4 ()
void debug2terminal ()
Private Attributes
piecewise_polynomial_trajectory ud
pid_omega_logger logger
Initialize the logger.
rk4_array< double, NSI > y
rk4_array< double, NSI > dy
boost::numeric::odeint::runge_kutta4< rk4_array< double, NSI > > rk4
controller_internal_parameters cip
controller_internal_members cim
controller_integrated_state_members csm
Additional Inherited Members
Protected Attributes inherited from _control_algorithm_base_::controller_base
Eigen::Vector< float, 8 > control_input
flight_params * flight_params_ptr
Detailed Description
public controller_base
Definition at line 81 of file PID_OMEGA.hpp.
Constructor & Destructor Documentation
pid_omega()
_qrbp_::_pid_omega_::pid_omega::pid_omega (flight_params * p, const std::string & controller_log_dir_)
Definition at line 70 of file PID_OMEGA.cpp.
References init(), and read_params().
~pid_omega()
_qrbp_::_pid_omega_::pid_omega::~pid_omega ()
Definition at line 81 of file PID_OMEGA.cpp.
Member Function Documentation
assign_from_rk4()
void _qrbp_::_pid_omega_::pid_omega::assign_from_rk4 () private
Definition at line 184 of file PID_OMEGA.cpp.
References _utilities_::assignElementsToMembers(), csm, _qrbp_::_pid_omega_::controller_integrated_state_members::e_rot_eta_I, _qrbp_::_pid_omega_::controller_integrated_state_members::e_tran_pos_I, _qrbp_::_pid_omega_::controller_integrated_state_members::state_omega_x_d_filter, _qrbp_::_pid_omega_::controller_integrated_state_members::state_omega_y_d_filter, _qrbp_::_pid_omega_::controller_integrated_state_members::state_omega_z_d_filter, _qrbp_::_pid_omega_::controller_integrated_state_members::state_pitch_d_filter, _qrbp_::_pid_omega_::controller_integrated_state_members::state_roll_d_filter, and y.
Referenced by update().
compute_normalized_thrusts()
void _qrbp_::_pid_omega_::pid_omega::compute_normalized_thrusts () private
Definition at line 308 of file PID_OMEGA.cpp.
References cim, _control_algorithm_base_::controller_base::control_input, _utilities_::evaluatePolynomial(), _qrbp_::MAX_THRUST, _qrbp_::MIN_THRUST, _qrbp_::mixer_matrix_qrbp, _qrbp_::_pid_omega_::controller_internal_members::Sat_Thrust, _qrbp_::_pid_omega_::controller_internal_members::Thrust, _qrbp_::thrust_polynomial_coeff_qrbp, and _qrbp_::_pid_omega_::controller_internal_members::u.
Referenced by run().
compute_rotational_control()
void _qrbp_::_pid_omega_::pid_omega::compute_rotational_control () private
Definition at line 282 of file PID_OMEGA.cpp.
References _qrbp_::_pid_omega_::controller_internal_members::alpha_rot_d, cim, cip, csm, _qrbp_::_pid_omega_::controller_internal_members::e_rot_eta, _qrbp_::_pid_omega_::controller_integrated_state_members::e_rot_eta_I, _qrbp_::_pid_omega_::controller_internal_members::e_rot_omega, _qrbp_::_pid_omega_::controller_internal_members::eta_rot, _qrbp_::_pid_omega_::controller_internal_members::eta_rot_d, _qrbp_::inertia_matrix_q, _qrbp_::_pid_omega_::controller_internal_parameters::Kd_rot, _qrbp_::_pid_omega_::controller_internal_parameters::Ki_rot, _qrbp_::_pid_omega_::controller_internal_parameters::Kp_rot, _qrbp_::_pid_omega_::controller_internal_members::omega_rot, _qrbp_::_pid_omega_::controller_internal_members::omega_rot_d, _qrbp_::_pid_omega_::controller_internal_members::tau_rot, _qrbp_::_pid_omega_::controller_internal_members::tau_rot_baseline, and _qrbp_::_pid_omega_::controller_internal_members::u.
Referenced by run().
compute_translational_control_in_I()
void _qrbp_::_pid_omega_::pid_omega::compute_translational_control_in_I () private
Definition at line 212 of file PID_OMEGA.cpp.
References cim, cip, csm, _qrbp_::e3_basis, _qrbp_::_pid_omega_::controller_internal_members::e_tran_pos, _qrbp_::_pid_omega_::controller_integrated_state_members::e_tran_pos_I, _qrbp_::_pid_omega_::controller_internal_members::e_tran_vel, _qrbp_::G, _qrbp_::_pid_omega_::controller_internal_parameters::Kd_tran, _qrbp_::_pid_omega_::controller_internal_parameters::Ki_tran, _qrbp_::_pid_omega_::controller_internal_parameters::Kp_tran, _qrbp_::MASS, _qrbp_::_pid_omega_::controller_internal_members::mu_tran_baseline, _qrbp_::_pid_omega_::controller_internal_members::mu_tran_I, _qrbp_::_pid_omega_::controller_internal_members::r_ddot_user, _qrbp_::_pid_omega_::controller_internal_members::r_dot_user, _qrbp_::_pid_omega_::controller_internal_members::r_user, _qrbp_::_pid_omega_::controller_internal_members::x_tran_pos, and _qrbp_::_pid_omega_::controller_internal_members::x_tran_vel.
Referenced by run().
compute_u1_eta_d()
void _qrbp_::_pid_omega_::pid_omega::compute_u1_eta_d () private
Definition at line 229 of file PID_OMEGA.cpp.
References _qrbp_::A_filter_pitch_dot_ref, _qrbp_::A_filter_pitch_ref, _qrbp_::A_filter_roll_dot_ref, _qrbp_::A_filter_roll_ref, _qrbp_::A_filter_yaw_dot_ref, _qrbp_::_pid_omega_::controller_internal_members::alpha_rot_d, _qrbp_::B_filter_pitch_dot_ref, _qrbp_::B_filter_pitch_ref, _qrbp_::B_filter_roll_dot_ref, _qrbp_::B_filter_roll_ref, _qrbp_::B_filter_yaw_dot_ref, _qrbp_::C_filter_pitch_dot_ref, _qrbp_::C_filter_pitch_ref, _qrbp_::C_filter_roll_dot_ref, _qrbp_::C_filter_roll_ref, _qrbp_::C_filter_yaw_dot_ref, cim, csm, _qrbp_::_pid_omega_::controller_internal_members::eta_rot, _qrbp_::_pid_omega_::controller_internal_members::eta_rot_d, _qrbp_::_pid_omega_::controller_internal_members::eta_rot_rate_d, _qrbp_::_pid_omega_::controller_internal_members::internal_state_omega_x_d_filter, _qrbp_::_pid_omega_::controller_internal_members::internal_state_omega_y_d_filter, _qrbp_::_pid_omega_::controller_internal_members::internal_state_omega_z_d_filter, _qrbp_::_pid_omega_::controller_internal_members::internal_state_pitch_d_filter, _qrbp_::_pid_omega_::controller_internal_members::internal_state_roll_d_filter, _qrbp_::_pid_omega_::controller_internal_members::Jacobian, _utilities_::jacobianMatrix(), _qrbp_::_pid_omega_::controller_internal_members::mu_tran_I, _qrbp_::_pid_omega_::controller_internal_members::mu_tran_J, _qrbp_::_pid_omega_::controller_internal_members::omega_rot_d, _qrbp_::_pid_omega_::controller_internal_members::R_I_J, _qrbp_::_pid_omega_::controller_integrated_state_members::state_omega_x_d_filter, _qrbp_::_pid_omega_::controller_integrated_state_members::state_omega_y_d_filter, _qrbp_::_pid_omega_::controller_integrated_state_members::state_omega_z_d_filter, _qrbp_::_pid_omega_::controller_integrated_state_members::state_pitch_d_filter, _qrbp_::_pid_omega_::controller_integrated_state_members::state_roll_d_filter, and _qrbp_::_pid_omega_::controller_internal_members::u.
Referenced by run().
debug2terminal()
void _qrbp_::_pid_omega_::pid_omega::debug2terminal () private
Definition at line 324 of file PID_OMEGA.cpp.
Referenced by run().
get_t1()
float _qrbp_::_pid_omega_::pid_omega::get_t1 () const
Definition at line 367 of file PID_OMEGA.cpp.
References _control_algorithm_base_::controller_base::control_input.
Referenced by _control_::controlNode::compute_and_publish_control().
get_t2()
float _qrbp_::_pid_omega_::pid_omega::get_t2 () const
Definition at line 371 of file PID_OMEGA.cpp.
References _control_algorithm_base_::controller_base::control_input.
Referenced by _control_::controlNode::compute_and_publish_control().
get_t3()
float _qrbp_::_pid_omega_::pid_omega::get_t3 () const
Definition at line 375 of file PID_OMEGA.cpp.
References _control_algorithm_base_::controller_base::control_input.
Referenced by _control_::controlNode::compute_and_publish_control().
get_t4()
float _qrbp_::_pid_omega_::pid_omega::get_t4 () const
Definition at line 379 of file PID_OMEGA.cpp.
References _control_algorithm_base_::controller_base::control_input.
Referenced by _control_::controlNode::compute_and_publish_control().
get_t5()
float _qrbp_::_pid_omega_::pid_omega::get_t5 () const
Definition at line 383 of file PID_OMEGA.cpp.
References _control_algorithm_base_::controller_base::control_input.
Referenced by _control_::controlNode::compute_and_publish_control().
get_t6()
float _qrbp_::_pid_omega_::pid_omega::get_t6 () const
Definition at line 387 of file PID_OMEGA.cpp.
References _control_algorithm_base_::controller_base::control_input.
Referenced by _control_::controlNode::compute_and_publish_control().
get_t7()
float _qrbp_::_pid_omega_::pid_omega::get_t7 () const
Definition at line 391 of file PID_OMEGA.cpp.
References _control_algorithm_base_::controller_base::control_input.
Referenced by _control_::controlNode::compute_and_publish_control().
get_t8()
float _qrbp_::_pid_omega_::pid_omega::get_t8 () const
Definition at line 395 of file PID_OMEGA.cpp.
References _control_algorithm_base_::controller_base::control_input.
Referenced by _control_::controlNode::compute_and_publish_control().
init()
void _qrbp_::_pid_omega_::pid_omega::init () private
Init function.
Parameters
None
Definition at line 106 of file PID_OMEGA.cpp.
References dy, and y.
Referenced by pid_omega().
model()
void _qrbp_::_pid_omega_::pid_omega::model (const rk4_array< double, NSI > & y, rk4_array< double, NSI > & dy, double t) private
Defining the model.
Parameters
y
dy
t
Definition at line 198 of file PID_OMEGA.cpp.
References _utilities_::assignElementsToDxdt(), cim, dy, _qrbp_::_pid_omega_::controller_internal_members::e_rot_eta, _qrbp_::_pid_omega_::controller_internal_members::e_tran_pos, _qrbp_::_pid_omega_::controller_internal_members::internal_state_omega_x_d_filter, _qrbp_::_pid_omega_::controller_internal_members::internal_state_omega_y_d_filter, _qrbp_::_pid_omega_::controller_internal_members::internal_state_omega_z_d_filter, _qrbp_::_pid_omega_::controller_internal_members::internal_state_pitch_d_filter, and _qrbp_::_pid_omega_::controller_internal_members::internal_state_roll_d_filter.
Referenced by run().
read_params()
void _qrbp_::_pid_omega_::pid_omega::read_params (const std::string & jsonFile) private
Reading params from json file.
Parameters
jsonFile
Definition at line 86 of file PID_OMEGA.cpp.
References cip, file(), _qrbp_::_pid_omega_::controller_internal_parameters::Kd_rot, _qrbp_::_pid_omega_::controller_internal_parameters::Kd_tran, _qrbp_::_pid_omega_::controller_internal_parameters::Ki_rot, _qrbp_::_pid_omega_::controller_internal_parameters::Ki_tran, _qrbp_::_pid_omega_::controller_internal_parameters::Kp_rot, and _qrbp_::_pid_omega_::controller_internal_parameters::Kp_tran.
Referenced by pid_omega().
run()
void _qrbp_::_pid_omega_::pid_omega::run (const double time_step_rk4_)
Run function.
Parameters
time_step_rk4_
Definition at line 330 of file PID_OMEGA.cpp.
References _qrbp_::_pid_omega_::controller_internal_members::aero, _qrbp_::_pid_omega_::controller_internal_members::alg_duration, _qrbp_::_pid_omega_::controller_internal_members::alg_end_time, _qrbp_::_pid_omega_::controller_internal_members::alg_start_time, cim, _qrbp_::_pid_omega_::controller_internal_members_aero::coeff, _qrbp_::compute_aero_forces_moments(), compute_normalized_thrusts(), compute_rotational_control(), compute_translational_control_in_I(), compute_u1_eta_d(), debug2terminal(), logger, _qrbp_::_pid_omega_::pid_omega_logger::logLogData(), model(), _qrbp_::_pid_omega_::controller_internal_members::R_J_I, _qrbp_::_pid_omega_::controller_internal_members::R_W_J, rk4, _qrbp_::_pid_omega_::controller_internal_members_aero::states, _qrbp_::_pid_omega_::controller_internal_members::t, and y.
Referenced by _control_::controlNode::compute_and_publish_control().
update()
void _qrbp_::_pid_omega_::pid_omega::update (double time, double x, double y, double z, double vx, double vy, double vz, double q0, double q1, double q2, double q3, double roll, double pitch, double yaw, double w_x, double w_y, double w_z)
Update function.
Parameters
time
x
y
z
vx
vy
vz
q0
q1
q2
q3
roll
pitch
yaw
w_x
w_y
w_z
Definition at line 112 of file PID_OMEGA.cpp.
References _qrbp_::_pid_omega_::controller_internal_members::aero, _utilities_::aeroDCMQuadNED(), _qrbp_::_pid_omega_::controller_internal_members::alg_start_time, _qrbp_::AeroStates::alpha, assign_from_rk4(), _qrbp_::AeroStates::beta, cim, _qrbp_::_pid_omega_::controller_internal_members_aero::coeff, _qrbp_::compute_aero_coefficients(), _qrbp_::computeAeroStatesNACA0012Quad(), _qrbp_::_pid_omega_::controller_internal_members::eta_rot, _qrbp_::_pid_omega_::controller_internal_members::eta_rot_d, _qrbp_::_pid_omega_::controller_internal_members::eta_rot_rate_d, _user_defined_trajectory_base_::trajectory_base::getUserDefinedAcceleration(), _user_defined_trajectory_base_::trajectory_base::getUserDefinedPosition(), _user_defined_trajectory_base_::trajectory_base::getUserDefinedVelocity(), _user_defined_trajectory_base_::trajectory_base::getUserDefinedYaw(), _user_defined_trajectory_base_::trajectory_base::getUserDefinedYawRate(), _qrbp_::_pid_omega_::controller_internal_members::omega_rot, _qrbp_::_pid_omega_::controller_internal_members::q, _qrbp_::_pid_omega_::controller_internal_members::r_ddot_user, _qrbp_::_pid_omega_::controller_internal_members::r_dot_user, _qrbp_::_pid_omega_::controller_internal_members::R_I_J, _qrbp_::_pid_omega_::controller_internal_members::R_J_I, _qrbp_::_pid_omega_::controller_internal_members::r_user, _qrbp_::_pid_omega_::controller_internal_members::R_W_J, _utilities_::rotationMatrix321GlobalToLocal(), _utilities_::rotationMatrix321LocalToGlobal(), _qrbp_::_pid_omega_::controller_internal_members_aero::states, _qrbp_::_pid_omega_::controller_internal_members::t, ud, _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::updateUserDefinedTrajectory(), _qrbp_::_pid_omega_::controller_internal_members::x_tran_pos, _qrbp_::_pid_omega_::controller_internal_members::x_tran_vel, _qrbp_::_pid_omega_::controller_internal_members::x_tran_vel_J, and y.
Referenced by _control_::controlNode::compute_and_publish_control().
Member Data Documentation
cim
controller_internal_members _qrbp_::_pid_omega_::pid_omega::cim private
Definition at line 192 of file PID_OMEGA.hpp.
Referenced by compute_normalized_thrusts(), compute_rotational_control(), compute_translational_control_in_I(), compute_u1_eta_d(), model(), run(), and update().
cip
controller_internal_parameters _qrbp_::_pid_omega_::pid_omega::cip private
Definition at line 189 of file PID_OMEGA.hpp.
Referenced by compute_rotational_control(), compute_translational_control_in_I(), and read_params().
csm
controller_integrated_state_members _qrbp_::_pid_omega_::pid_omega::csm private
Definition at line 195 of file PID_OMEGA.hpp.
Referenced by assign_from_rk4(), compute_rotational_control(), compute_translational_control_in_I(), and compute_u1_eta_d().
dy
rk4_array<double, NSI> _qrbp_::_pid_omega_::pid_omega::dy private
Definition at line 173 of file PID_OMEGA.hpp.
Referenced by init(), and model().
logger
pid_omega_logger _qrbp_::_pid_omega_::pid_omega::logger private
Initialize the logger.
Definition at line 168 of file PID_OMEGA.hpp.
Referenced by run().
rk4
boost::numeric::odeint::runge_kutta4<rk4_array<double, NSI> > _qrbp_::_pid_omega_::pid_omega::rk4 private
Definition at line 186 of file PID_OMEGA.hpp.
Referenced by run().
ud
piecewise_polynomial_trajectory _qrbp_::_pid_omega_::pid_omega::ud private
Definition at line 162 of file PID_OMEGA.hpp.
Referenced by update().
y
rk4_array<double, NSI> _qrbp_::_pid_omega_::pid_omega::y private
Definition at line 172 of file PID_OMEGA.hpp.
Referenced by assign_from_rk4(), init(), run(), and update().
The documentation for this class was generated from the following files:
ACSL-flightstack-winged/src/acsl_flight/include/control/platforms/qrbp/control_algorithms/PID_OMEGA/PID_OMEGA.hpp
ACSL-flightstack-winged/src/acsl_flight/src/control/platforms/qrbp/control_algorithms/PID_OMEGA/PID_OMEGA.cpp