ACSL Flightstack-winged Documentation: _flight_bridge_::flight_bridge Class Reference
_flight_bridge_::flight_bridge Class Reference
flight_bridge class
#include <flight_bridge.hpp>
Public Member Functions
flight_bridge (flight_params *p)
Constructor.
void init ()
Destructor.
Private Attributes
bool ret
Thread creation boolean.
const int CPU_ZERO = 0
CPU numbers.
const int CPU_ONE = 1
const int CPU_TWO = 2
const int CPU_THREE = 3
vehicle_states vehicle
flight_params * flight_params_ptr
std::string global_log_dir
Instance of the global flight_run_directory.
Detailed Description
flight_bridge class
Definition at line 294 of file flight_bridge.hpp.
Constructor & Destructor Documentation
flight_bridge()
_flight_bridge_::flight_bridge::flight_bridge (flight_params * p)
Constructor.
Definition at line 66 of file flight_bridge.cpp.
References _flight_bridge_::create_global_log_directory(), _flightstack_::FLIGHTSTACK_INFO(), global_log_dir, and platform_of_choice.
Member Function Documentation
init()
void _flight_bridge_::flight_bridge::init ()
Destructor.
-------------------------------— MOCAP EKF VISION FUSION MODE -------------------------------------— ///
-------------------------------— VIO EKF VISION FUSION MODE ----------------------------------------— ///
-------------------------------— GPS RTK EKF FUSION MODE -----------------------------------------— ///
Definition at line 74 of file flight_bridge.cpp.
References _flight_bridge_::configure_thread(), CPU_ONE, CPU_THREE, CPU_TWO, CPU_ZERO, flight_params_ptr, _flightstack_::FLIGHTSTACK_ERROR(), _flightstack_::FLIGHTSTACK_INFO(), _flight_bridge_::get_thread_time(), global_log_dir, _flight_bridge_::HIGH, flight_params::mocap, ret, vehicle, and flight_params::vio.
Referenced by main().
Member Data Documentation
CPU_ONE
const int _flight_bridge_::flight_bridge::CPU_ONE = 1 private
Definition at line 314 of file flight_bridge.hpp.
Referenced by init().
CPU_THREE
const int _flight_bridge_::flight_bridge::CPU_THREE = 3 private
Definition at line 316 of file flight_bridge.hpp.
Referenced by init().
CPU_TWO
const int _flight_bridge_::flight_bridge::CPU_TWO = 2 private
Definition at line 315 of file flight_bridge.hpp.
Referenced by init().
CPU_ZERO
const int _flight_bridge_::flight_bridge::CPU_ZERO = 0 private
CPU numbers.
Definition at line 313 of file flight_bridge.hpp.
Referenced by init().
flight_params_ptr
flight_params* _flight_bridge_::flight_bridge::flight_params_ptr private
Instance of the flight_params_ptr to point to the flight_parameter object in flight_main.cpp
Definition at line 323 of file flight_bridge.hpp.
Referenced by init().
global_log_dir
std::string _flight_bridge_::flight_bridge::global_log_dir private
Instance of the global flight_run_directory.
Definition at line 326 of file flight_bridge.hpp.
Referenced by flight_bridge(), and init().
ret
bool _flight_bridge_::flight_bridge::ret private
Thread creation boolean.
Definition at line 308 of file flight_bridge.hpp.
Referenced by init().
vehicle
vehicle_states _flight_bridge_::flight_bridge::vehicle private
Definition at line 319 of file flight_bridge.hpp.
Referenced by init().
The documentation for this class was generated from the following files:
ACSL-flightstack-winged/src/acsl_flight/include/flight_bridge/flight_bridge.hpp
ACSL-flightstack-winged/src/acsl_flight/src/flight_bridge/flight_bridge.cpp