ACSL Flightstack-winged Documentation: _utilities_ Namespace Reference
_utilities_ Namespace Reference
Typedefs
template<typename T , std::size_t N>
using rk4_array = boost::array< T, N >
Functions
template<typename VectorType , typename ScalarType >
ScalarType evaluatePolynomial (const VectorType coefficients, ScalarType value)
Function to evaluate a polynomial given its coefficients and a value at which to evaluate the polynomial.
template<typename VectorType , typename ScalarType >
ScalarType norm2D (const VectorType &poly_coef_x, const VectorType &poly_coef_y, ScalarType value)
template<typename VectorType , typename ScalarType >
ScalarType norm2Dderivative (const VectorType &poly_coef_x, const VectorType &poly_coef_y, const VectorType &poly_coef_x_prime, const VectorType &poly_coef_y_prime, ScalarType value)
template<typename MatrixType >
MatrixType polyDerMatrix (const MatrixType &poly_coeff_matrix_in)
Function to compute the derivative of the piecewise polynomial coefficient matrix.
template<typename T >
T wrapAngleToMinusPiAndPi (T alpha)
Wraps an angle alpha to the interval [-pi, pi].
template<typename T >
T makeYawAngularErrorContinuous (T yaw, T user_defined_yaw)
Makes the yaw angular error continuous considering the discontinuity at +/- pi.
template<typename Scalar , int Rows, int Cols>
Eigen::Matrix< Scalar, Rows, Cols > jsonToMatrix (const nlohmann::json &jsonMatrix)
Helper function to extract matrices from json files.
template<typename Scalar , int Rows, int Cols>
Eigen::Matrix< Scalar, Rows, Cols > jsonToScaledMatrix (const nlohmann::json &jsonMatrix)
Helper funtion to extract matrices with a scaling factor from json files.
template<typename T >
void checkNaN (T value, const char *message)
Inline template function to check NaN for scalar values.
template<typename Derived >
void checkNaN (const Eigen::MatrixBase< Derived > &matrix, const char *message)
Inline template function to check NaN for Eigen matrices.
template<typename MatrixType >
void initMat (MatrixType &matrix)
Function to initialize a fixed-size Eigen matrix to zero.
template<typename Scalar >
Eigen::Matrix< Scalar, 3, 3 > rotationMatrix321GlobalToLocal (const Scalar roll, const Scalar pitch, const Scalar yaw)
Function that computes the 321 rotation matrix that transforms a vector from global to local coordinates.
template<typename Scalar >
Eigen::Matrix< Scalar, 3, 3 > rotationMatrix321LocalToGlobal (const Scalar roll, const Scalar pitch, const Scalar yaw)
Function that computes the 321 rotation matrix that transforms a vector from local to global coordinates rotation_matrix_321_local_to_global = R3 * R2 * R1.
template<typename Scalar >
Eigen::Matrix< Scalar, 3, 3 > jacobianMatrixInverse (const Scalar roll, const Scalar pitch)
Function that returns a 3x3 Jacobian matrix inverse given roll and pitch angles.
template<typename Scalar >
Eigen::Matrix< Scalar, 3, 3 > jacobianMatrix (const Scalar roll, const Scalar pitch)
Function that computes the Jacobian matrix given roll and pitch angles.
template<typename Scalar >
Eigen::Matrix< Scalar, 3, 3 > jacobianMatrixDerivative (const Scalar roll, const Scalar pitch, const Scalar roll_dot, const Scalar pitch_dot)
Function that returns a 3x3 Jacobian matrix derivative given roll and pitch angles and their derivatives.
template<typename Scalar >
Eigen::Matrix< Scalar, 3, 3 > aeroDCMQuadNED (const Scalar alpha, const Scalar beta)
Function that returns a 3x3 Aerodynamic rotation matrix from Wind to Local frame.
template<typename Scalar >
Eigen::Matrix< Scalar, 3, 3 > aeroDCMBiplaneNED (const Scalar alpha, const Scalar beta)
Function that returns a 3x3 Aerodynamic rotation matrix from Wind to Local frame.
template<typename T , int Rows, int Cols, std::size_t N>
void assignElementsToDxdt (Eigen::Matrix< T, Rows, Cols > &entity, boost::array< T, N > &dxdt, int &current_index)
Assigns elements to dxdt in the model for integration.
template<typename T , int Rows, int Cols, std::size_t N>
void assignElementsToMembers (Eigen::Matrix< T, Rows, Cols > &entity, boost::array< T, N > &x, int &current_index)
Assign a map for elements from the boost array to the states after integration.
template<typename T , int Rows, int Cols, std::size_t N>
void resetElementsToMembers (Eigen::Matrix< T, Rows, Cols > &entity, boost::array< T, N > &x, int &current_index, boost::array< T, N > &zeros)
Assign a map for elements from the boost array to the states after integration with the option to reset the elements.
Typedef Documentation
rk4_array
template<typename T , std::size_t N> using _utilities_::rk4_array = typedef boost::array<T, N>
Definition at line 588 of file helper_functions.hpp.
Function Documentation
aeroDCMBiplaneNED()
template<typename Scalar > Eigen::Matrix<Scalar, 3, 3> _utilities_::aeroDCMBiplaneNED (const Scalar alpha, const Scalar beta) inline
Function that returns a 3x3 Aerodynamic rotation matrix from Wind to Local frame.
Example usage: float alpha float beta Eigen::Matrix3f R_W_J = aeroDCMBiplaneNED(alpha, eta)
Parameters
alpha
beta
Returns
Eigen::Matrix<Scalar, 3, 3>
Definition at line 567 of file helper_functions.hpp.
aeroDCMQuadNED()
template<typename Scalar > Eigen::Matrix<Scalar, 3, 3> _utilities_::aeroDCMQuadNED (const Scalar alpha, const Scalar beta) inline
Function that returns a 3x3 Aerodynamic rotation matrix from Wind to Local frame.
Example usage: float alpha float beta Eigen::Matrix3f R_W_J = aeroDCMQuadNED(alpha, beta)
Parameters
alpha
beta
Returns
Eigen::Matrix<Scalar, 3, 3>
Definition at line 532 of file helper_functions.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::update(), _qrbp_::_mrac_pid_::mrac_pid::update(), and _qrbp_::_pid_omega_::pid_omega::update().
assignElementsToDxdt()
template<typename T , int Rows, int Cols, std::size_t N> void _utilities_::assignElementsToDxdt (Eigen::Matrix< T, Rows, Cols > & entity, boost::array< T, N > & dxdt, int & current_index) inline
Assigns elements to dxdt in the model for integration.
Parameters
entity
dxdt
current_index
Definition at line 598 of file helper_functions.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::model(), _qrbp_::_mrac_pid_::mrac_pid::model(), and _qrbp_::_pid_omega_::pid_omega::model().
assignElementsToMembers()
template<typename T , int Rows, int Cols, std::size_t N> void _utilities_::assignElementsToMembers (Eigen::Matrix< T, Rows, Cols > & entity, boost::array< T, N > & x, int & current_index) inline
Assign a map for elements from the boost array to the states after integration.
Parameters
entity
x
current_index
Definition at line 614 of file helper_functions.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::assign_from_rk4(), _qrbp_::_mrac_pid_::mrac_pid::assign_from_rk4(), _qrbp_::_pid_::pid::assign_from_rk4(), _qrbp_::_pid_omega_::pid_omega::assign_from_rk4(), _rostestdrone_::_pid_::pid::assign_from_rk4(), and _qrbp_::_mrac_pid_::mrac_pid::reset_integrator_states().
checkNaN() [1/2]
template<typename Derived > void _utilities_::checkNaN (const Eigen::MatrixBase< Derived > & matrix, const char * message) inline
Inline template function to check NaN for Eigen matrices.
Parameters
matrix
message
Definition at line 306 of file helper_functions.hpp.
checkNaN() [2/2]
template<typename T > void _utilities_::checkNaN (T value, const char * message) inline
Inline template function to check NaN for scalar values.
Parameters
value
message
Definition at line 293 of file helper_functions.hpp.
evaluatePolynomial()
template<typename VectorType , typename ScalarType > ScalarType _utilities_::evaluatePolynomial (const VectorType coefficients, ScalarType value) inline
Function to evaluate a polynomial given its coefficients and a value at which to evaluate the polynomial.
Example usage: double value = 3.0; Eigen::VectorXd coeffs(3); coeffs << 1, -2, 1; // Represents the polynomial x^2 - 2x + 1 double result = evaluatePolynomial(coeffs, value);
Parameters
coefficients
value
Returns
ScalarType
Definition at line 98 of file helper_functions.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::compute_normalized_thrusts(), _qrbp_::_mrac_pid_::mrac_pid::compute_normalized_thrusts(), _qrbp_::_pid_::pid::compute_normalized_thrusts(), _qrbp_::_pid_omega_::pid_omega::compute_normalized_thrusts(), _rostestdrone_::_pid_::pid::compute_normalized_thrusts(), norm2D(), _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::updateUserDefinedTrajectory(), _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::yawComputation(), _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::yawDotComputation(), and _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::yawDotDotComputation().
initMat()
template<typename MatrixType > void _utilities_::initMat (MatrixType & matrix) inline
Function to initialize a fixed-size Eigen matrix to zero.
Parameters
matrix
Definition at line 318 of file helper_functions.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::init(), and _qrbp_::_mrac_pid_::mrac_pid::init().
jacobianMatrix()
template<typename Scalar > Eigen::Matrix<Scalar, 3, 3> _utilities_::jacobianMatrix (const Scalar roll, const Scalar pitch) inline
Function that computes the Jacobian matrix given roll and pitch angles.
Parameters
roll
pitch
Returns
Eigen::Matrix<Scalar, 3, 3>
Definition at line 456 of file helper_functions.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::compute_u1_eta_d(), _qrbp_::_pid_omega_::pid_omega::compute_u1_eta_d(), and _qrbp_::_mrac_pid_::mrac_pid::update().
jacobianMatrixDerivative()
template<typename Scalar > Eigen::Matrix<Scalar, 3, 3> _utilities_::jacobianMatrixDerivative (const Scalar roll, const Scalar pitch, const Scalar roll_dot, const Scalar pitch_dot) inline
Function that returns a 3x3 Jacobian matrix derivative given roll and pitch angles and their derivatives.
Example usage: double roll = 0.1; Example usage: double roll = 0.1; Eigen::Matrix3d jacobian_dot = jacobianMatrixDerivative(roll, pitch, roll_dot, pitch_dot);
Parameters
roll
pitch
roll_dot
pitch_dot
Returns
Eigen::Matrix<Scalar, 3, 3>
Definition at line 493 of file helper_functions.hpp.
Referenced by _qrbp_::_mrac_pid_::mrac_pid::update().
jacobianMatrixInverse()
template<typename Scalar > Eigen::Matrix<Scalar, 3, 3> _utilities_::jacobianMatrixInverse (const Scalar roll, const Scalar pitch) inline
Function that returns a 3x3 Jacobian matrix inverse given roll and pitch angles.
Example usage: double roll = 0.1;
double pitch = 0.2; Eigen::Matrix3d jacobian_inv = jacobianMatrixInverse(roll, pitch);
Parameters
roll
pitch
Returns
Eigen::Matrix<Scalar, 3, 3>
Definition at line 425 of file helper_functions.hpp.
Referenced by _qrbp_::_mrac_pid_::mrac_pid::update(), _qrbp_::_pid_::pid::update(), and _rostestdrone_::_pid_::pid::update().
jsonToMatrix()
template<typename Scalar , int Rows, int Cols> Eigen::Matrix<Scalar, Rows, Cols> _utilities_::jsonToMatrix (const nlohmann::json & jsonMatrix) inline
Helper function to extract matrices from json files.
Example usage : Eigen::Matrix<double, 3, 3> matrix3x3_double = jsonToMatrix<double, 3, 3>(jsonMatrix) Example usage : Eigen::Matrix<float, 4, 4> matrix4x4_float = jsonToMatrix<float, 4, 4>(jsonMatrix)
Parameters
jsonMatrix
Returns
Eigen::Matrix<Scalar, Rows, Cols>
Definition at line 243 of file helper_functions.hpp.
jsonToScaledMatrix()
template<typename Scalar , int Rows, int Cols> Eigen::Matrix<Scalar, Rows, Cols> _utilities_::jsonToScaledMatrix (const nlohmann::json & jsonMatrix) inline
Helper funtion to extract matrices with a scaling factor from json files.
Example usage: Eigen::Matrix<double, 3, 3> matrix3x3_double = jsonToScaledMatrix<double, 3, 3>(jsonMatrix) Example usage: Eigen::Matrix<float, 3, 3> matrix3x3_double = jsonToScaledMatrix<float, 3, 3>(jsonMatrix)
Parameters
jsonMatrix
Returns
Eigen::Matrix<Scalar, Rows, Cols>
Definition at line 266 of file helper_functions.hpp.
makeYawAngularErrorContinuous()
template<typename T > T _utilities_::makeYawAngularErrorContinuous (T yaw, T user_defined_yaw) inline
Makes the yaw angular error continuous considering the discontinuity at +/- pi.
Example usage : double result = makeYawAngularErrorContinuous<double>(yaw, user_defined_yaw); Example usage : float result = makeYawAngularErrorContinuous<float>(yaw_float, user_defined_yaw_float);
Parameters
yaw
user_defined_yaw
Returns
T
Definition at line 206 of file helper_functions.hpp.
References wrapAngleToMinusPiAndPi().
norm2D()
template<typename VectorType , typename ScalarType > ScalarType _utilities_::norm2D (const VectorType & poly_coef_x, const VectorType & poly_coef_y, ScalarType value) inline
Definition at line 113 of file helper_functions.hpp.
References evaluatePolynomial().
norm2Dderivative()
template<typename VectorType , typename ScalarType > ScalarType _utilities_::norm2Dderivative (const VectorType & poly_coef_x, const VectorType & poly_coef_y, const VectorType & poly_coef_x_prime, const VectorType & poly_coef_y_prime, ScalarType value) inline
Definition at line 132 of file helper_functions.hpp.
polyDerMatrix()
template<typename MatrixType > MatrixType _utilities_::polyDerMatrix (const MatrixType & poly_coeff_matrix_in) inline
Function to compute the derivative of the piecewise polynomial coefficient matrix.
Example Usage: Eigen::MatrixXd poly_coeff_matrix_in(3, 4); Eigen::MatrixXd result = polyDerMatrix(poly_coeff_matrix_in);
Parameters
poly_coeff_matrix_in
Returns
MatrixType
Definition at line 160 of file helper_functions.hpp.
Referenced by _piecewise_polynomial_trajectory_::piecewise_polynomial_trajectory::setPolynomialCoefficientMatrices().
resetElementsToMembers()
template<typename T , int Rows, int Cols, std::size_t N> void _utilities_::resetElementsToMembers (Eigen::Matrix< T, Rows, Cols > & entity, boost::array< T, N > & x, int & current_index, boost::array< T, N > & zeros) inline
Assign a map for elements from the boost array to the states after integration with the option to reset the elements.
Parameters
entity
x
current_index
zeros
Definition at line 636 of file helper_functions.hpp.
Referenced by _qrbp_::_mrac_pid_::mrac_pid::reset_integrator_states().
rotationMatrix321GlobalToLocal()
template<typename Scalar > Eigen::Matrix<Scalar, 3, 3> _utilities_::rotationMatrix321GlobalToLocal (const Scalar roll, const Scalar pitch, const Scalar yaw) inline
Function that computes the 321 rotation matrix that transforms a vector from global to local coordinates.
rotation_matrix_321_local_to_global = R3 * R2 * R1; // hence rotation_matrix_321_global_to_local = R1_transpose * R2_transpose * R3_transpose
Parameters
roll
pitch
yaw
Returns
Eigen::Matrix<Scalar, 3, 3>
Definition at line 337 of file helper_functions.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::update(), _qrbp_::_mrac_pid_::mrac_pid::update(), _qrbp_::_pid_::pid::update(), _qrbp_::_pid_omega_::pid_omega::update(), and _rostestdrone_::_pid_::pid::update().
rotationMatrix321LocalToGlobal()
template<typename Scalar > Eigen::Matrix<Scalar, 3, 3> _utilities_::rotationMatrix321LocalToGlobal (const Scalar roll, const Scalar pitch, const Scalar yaw) inline
Function that computes the 321 rotation matrix that transforms a vector from local to global coordinates rotation_matrix_321_local_to_global = R3 * R2 * R1.
Template Parameters
Scalar
Parameters
roll
pitch
yaw
Returns
Eigen::Matrix<Scalar, 3, 3>
Definition at line 379 of file helper_functions.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::update(), _qrbp_::_mrac_pid_::mrac_pid::update(), _qrbp_::_pid_::pid::update(), _qrbp_::_pid_omega_::pid_omega::update(), _rostestdrone_::_pid_::pid::update(), and _qrbp_::update_states_to_biplane_mode().
wrapAngleToMinusPiAndPi()
template<typename T > T _utilities_::wrapAngleToMinusPiAndPi (T alpha) inline
Wraps an angle alpha to the interval [-pi, pi].
Parameters
alpha
Returns
T
Definition at line 187 of file helper_functions.hpp.
Referenced by makeYawAngularErrorContinuous().