ACSL Flightstack-winged Documentation: _flight_bridge_ Namespace Reference
_flight_bridge_ Namespace Reference
Classes
class flight_bridge
Enumerations
enum class ThreadPriority { LOW , HIGH }
Enum for simple configuration of threads in two priority classes.
Functions
std::chrono::milliseconds get_millis_from_secs_parameter (const rclcpp::Node *node, const std::string &name)
Retrieves the value of the given seconds parameter in std::chrono nanoseconds.
template<typename T >
bool configure_native_thread (T native_handle, ThreadPriority priority, int cpu_id)
bool configure_thread (std::thread &thread, ThreadPriority priority, int cpu_id)
template<typename T >
std::chrono::nanoseconds get_native_thread_time (T native_handle)
std::chrono::nanoseconds get_thread_time (std::thread &thread)
std::chrono::nanoseconds get_current_thread_time ()
std::string create_global_log_directory (const std::string &platform_)
Enumeration Type Documentation
ThreadPriority
enum _flight_bridge_::ThreadPriority strong
Enum for simple configuration of threads in two priority classes.
Enumerator
LOW
HIGH
Definition at line 116 of file flight_bridge.hpp.
Function Documentation
configure_native_thread()
template<typename T > bool _flight_bridge_::configure_native_thread (T native_handle, ThreadPriority priority, int cpu_id)
Sets the priority of the given native thread to max or min as given. The exact priority value depends on the operating system. On Linux, this requires elevated privileges. Furthermore, if a non-negative CPU id is given, the thread is pinned to that CPU.
Definition at line 128 of file flight_bridge.hpp.
Referenced by configure_thread().
configure_thread()
bool _flight_bridge_::configure_thread (std::thread & thread, ThreadPriority priority, int cpu_id) inline
Sets the priority of the given thread to max or min as given. The exact scheduler priority depends on the operating system. On Linux, this requires elevated privileges. Furthermore, if a non-negative CPU id is given, the thread is pinned to that CPU.
Definition at line 155 of file flight_bridge.hpp.
References configure_native_thread().
Referenced by _flight_bridge_::flight_bridge::init().
create_global_log_directory()
std::string _flight_bridge_::create_global_log_directory (const std::string & platform_) inline
Retruns the global log file directory as a string to be used in logging mocap, vio, control data. This allows us to unify the data collection directory as vio and mocap are often times slower to start than the control thread.
Definition at line 191 of file flight_bridge.hpp.
Referenced by _flight_bridge_::flight_bridge::flight_bridge().
get_current_thread_time()
std::chrono::nanoseconds _flight_bridge_::get_current_thread_time () inline
Returns the time of the current thread as std::chrono timestamp. This allows measuring the execution time of this thread.
Definition at line 183 of file flight_bridge.hpp.
References get_native_thread_time().
get_millis_from_secs_parameter()
std::chrono::milliseconds _flight_bridge_::get_millis_from_secs_parameter (const rclcpp::Node * node, const std::string & name) inline
Retrieves the value of the given seconds parameter in std::chrono nanoseconds.
Definition at line 105 of file flight_bridge.hpp.
get_native_thread_time()
template<typename T > std::chrono::nanoseconds _flight_bridge_::get_native_thread_time (T native_handle)
Returns the time of the given native thread handle as std::chrono timestamp. This allows measuring the execution time of this thread.
Definition at line 163 of file flight_bridge.hpp.
Referenced by get_current_thread_time(), and get_thread_time().
get_thread_time()
std::chrono::nanoseconds _flight_bridge_::get_thread_time (std::thread & thread) inline
Returns the time of the given thread as std::chrono timestamp. This allows measuring the execution time of this thread.
Definition at line 176 of file flight_bridge.hpp.
References get_native_thread_time().
Referenced by _flight_bridge_::flight_bridge::init().