ACSL Flightstack-winged Documentation: _lyapunov_solver_::internal Namespace Reference
_lyapunov_solver_::internal Namespace Reference
Functions
Vector1d Solve1By1RealContinuousLyapunovEquation (const Eigen::Ref< const Vector1d > &A, const Eigen::Ref< const Vector1d > &Q)
Matrix2d Solve2By2RealContinuousLyapunovEquation (const Eigen::Ref< const Matrix2d > &A, const Eigen::Ref< const Matrix2d > &Q)
MatrixXd SolveReducedRealContinuousLyapunovEquation (const Eigen::Ref< const MatrixXd > &S, const Eigen::Ref< const MatrixXd > &Q_bar)
Eigen::Matrix2d Solve2By2RealContinuousLyapunovEquation (const Eigen::Ref< const Eigen::Matrix2d > &A, const Eigen::Ref< const Eigen::Matrix2d > &Q)
Eigen::MatrixXd SolveReducedRealContinuousLyapunovEquation (const Eigen::Ref< const Eigen::MatrixXd > &A, const Eigen::Ref< const Eigen::MatrixXd > &Q)
Function Documentation
Solve1By1RealContinuousLyapunovEquation()
Vector1d _lyapunov_solver_::internal::Solve1By1RealContinuousLyapunovEquation (const Eigen::Ref< const Vector1d > & A, const Eigen::Ref< const Vector1d > & Q)
Definition at line 181 of file continuous_lyapunov_equation.cpp.
Referenced by _lyapunov_solver_::RealContinuousLyapunovEquation(), and SolveReducedRealContinuousLyapunovEquation().
Solve2By2RealContinuousLyapunovEquation() [1/2]
Eigen::Matrix2d _lyapunov_solver_::internal::Solve2By2RealContinuousLyapunovEquation (const Eigen::Ref< const Eigen::Matrix2d > & A, const Eigen::Ref< const Eigen::Matrix2d > & Q)
Solve2By2RealContinuousLyapunovEquation() [2/2]
Matrix2d _lyapunov_solver_::internal::Solve2By2RealContinuousLyapunovEquation (const Eigen::Ref< const Matrix2d > & A, const Eigen::Ref< const Matrix2d > & Q)
Definition at line 186 of file continuous_lyapunov_equation.cpp.
Referenced by _lyapunov_solver_::RealContinuousLyapunovEquation(), and SolveReducedRealContinuousLyapunovEquation().
SolveReducedRealContinuousLyapunovEquation() [1/2]
Eigen::MatrixXd _lyapunov_solver_::internal::SolveReducedRealContinuousLyapunovEquation (const Eigen::Ref< const Eigen::MatrixXd > & A, const Eigen::Ref< const Eigen::MatrixXd > & Q)
SolveReducedRealContinuousLyapunovEquation() [2/2]
MatrixXd _lyapunov_solver_::internal::SolveReducedRealContinuousLyapunovEquation (const Eigen::Ref< const MatrixXd > & S, const Eigen::Ref< const MatrixXd > & Q_bar)
Definition at line 206 of file continuous_lyapunov_equation.cpp.
References Solve1By1RealContinuousLyapunovEquation(), and Solve2By2RealContinuousLyapunovEquation().
Referenced by _lyapunov_solver_::RealContinuousLyapunovEquation().