ACSL Flightstack-winged Documentation: _lyapunov_solver_ Namespace Reference
_lyapunov_solver_ Namespace Reference
Namespaces
internal
Typedefs
using Vector1d = Eigen::Matrix< double, 1, 1 >
Functions
MatrixXd RealContinuousLyapunovEquation (const Eigen::Ref< const MatrixXd > &A, const Eigen::Ref< const MatrixXd > &Q)
Eigen::MatrixXd RealContinuousLyapunovEquation (const Eigen::Ref< const Eigen::MatrixXd > &A, const Eigen::Ref< const Eigen::MatrixXd > &Q)
Typedef Documentation
Vector1d
using _lyapunov_solver_::Vector1d = typedef Eigen::Matrix<double, 1, 1>
Definition at line 101 of file continuous_lyapunov_equation.hpp.
Function Documentation
RealContinuousLyapunovEquation() [1/2]
Eigen::MatrixXd _lyapunov_solver_::RealContinuousLyapunovEquation (const Eigen::Ref< const Eigen::MatrixXd > & A, const Eigen::Ref< const Eigen::MatrixXd > & Q)
Parameters
A A user defined real square matrix.
Q A user defined real symmetric matrix.
Precondition
Q is a symmetric matrix.
Computes a unique solution X to the continuous Lyapunov equation: AᵀX + XA + Q = 0, where A is real and square, and Q is real, symmetric and of equal size as A.
Exceptions
std::runtime_error if A or Q are not square matrices or do not have the same size.
Limitations: Given the Eigenvalues of A as λ₁, ..., λₙ, there exists a unique solution if and only if λᵢ + λ̅ⱼ ≠ 0 ∀ i,j, where λ̅ⱼ is the complex conjugate of λⱼ.
Exceptions
std::runtime_error if the solution is not unique.
There are no further limitations on the eigenvalues of A. Further, if all λᵢ have negative real parts, and if Q is positive semi-definite, then X is also positive semi-definite [1]. Therefore, if one searches for a Lyapunov function V(z) = zᵀXz for the stable linear system ż = Az, then the solution of the Lyapunov Equation AᵀX + XA + Q = 0 only returns a valid Lyapunov function if Q is positive semi-definite.
The implementation is based on SLICOT routine SB03MD [2]. Note the transformation Q = -C. The complexity of this routine is O(n³). If A is larger than 2-by-2, then a Schur factorization is performed.
Exceptions
std::runtime_error if Schur factorization failed.
A tolerance of ε is used to check if a double variable is equal to zero, where the default value for ε is 1e-10. It has been used to check (1) if λᵢ + λ̅ⱼ = 0, ∀ i,j; (2) if A is a 1-by-1 zero matrix; (3) if A's trace or determinant is 0 when A is a 2-by-2 matrix.
[1] Bartels, R.H. and G.W. Stewart, "Solution of the Matrix Equation AX + XB = C," Comm. of the ACM, Vol. 15, No. 9, 1972.
[2] http://slicot.org/objects/software/shared/doc/SB03MD.html
RealContinuousLyapunovEquation() [2/2]
MatrixXd _lyapunov_solver_::RealContinuousLyapunovEquation (const Eigen::Ref< const MatrixXd > & A, const Eigen::Ref< const MatrixXd > & Q)
Definition at line 111 of file continuous_lyapunov_equation.cpp.
References _lyapunov_solver_::internal::Solve1By1RealContinuousLyapunovEquation(), _lyapunov_solver_::internal::Solve2By2RealContinuousLyapunovEquation(), and _lyapunov_solver_::internal::SolveReducedRealContinuousLyapunovEquation().
Referenced by _qrbp_::_mrac_omega_::mrac_omega::init(), and _qrbp_::_mrac_pid_::mrac_pid::init().