ACSL Flightstack-winged Documentation: _qrbp_ Namespace Reference
_qrbp_ Namespace Reference
Namespaces
_mrac_omega_
_mrac_pid_
_pid_
_pid_omega_
Classes
struct AeroStates
Angles for the wings and stabilizers.
struct AeroCoeff
Aerodynamic coefficients for the QRBP.
struct AeroDynamicMembers
Structre for all the aerodynamic members of the controller.
Functions
AeroStates computeAeroStatesNACA0012Quad (const double u, const double v, const double w, const double w_x, const double w_y, const double w_z)
Inline function to compute the Aerodynamic angles for the NACA-0012 airfoil.
double compute_cl (double angle)
Inline function to compute the coefficient of lift for the NACA-0012 airfoil using polynomial approximations.
double compute_cd (double angle)
Inline function to compute the coefficient of drag for the NACA-0012 airfoil using polynomial approximations.
double compute_cm (double angle)
Inline function to compute the coefficient of aerodynamic moment for the NACA-0012 airfoil using polynomial approximations.
AeroCoeff compute_aero_coefficients (AeroStates states)
Inline function to compute the aerodynamic coeffiecients for the QRBP.
AeroDynamicMembers compute_aero_forces_moments (AeroStates states, AeroCoeff coeff, Eigen::Matrix3d R_J_I, Eigen::Matrix3d R_W_J)
Incine function to comput the aerodynamic and moments for the QRBP.
void QRBPswitchFun (double pitch, bool &is_biplane, bool &mnt_btn)
Inline function to compute the switch from Quadcopter mode to Biplane Mode and vice versa.
void update_states_to_biplane_mode (const Vector3d eta, const Vector3d omega, Vector3d &eta_b, Vector3d &omega_b)
Inline Function to update the biplane mode states - Goes in the inner loop bridge.
void update_states_to_biplane_quaternion_gmk (const Eigen::Quaterniond q_q, const Vector3d omega, Vector3d &eta_b, Vector3d &omega_b)
Code written by Giri Mugundan Kumar to switch states - yet to be debugged.
void update_states_to_biplane_quaternions (const Eigen::Quaterniond q_q, const Vector3d omega, Vector3d &eta_b, Vector3d &omega_b)
Code from the PX4 Repository to switch states - might need debugging.
Variables
constexpr double G = 9.81
constexpr double RHO_HAT = 1.225
constexpr double PI = 3.1415
constexpr double PIHALF = (PI/2)
constexpr double DEG2RAD = (PI/180)
constexpr double RAD2DEG = (180/PI)
constexpr double SQRT2_OVER_2 = 0.7071067
constexpr double MASS = 2.04192755
constexpr double LX = 0.097509
constexpr double LY = 0.110688
constexpr double LZ_S = 0.038779
constexpr double SPAN_W = 0.50
constexpr double CHORD_W = 0.12
constexpr double SPAN_S = 0.175
constexpr double CHORD_S = 0.02
constexpr double PLANFORM_AREA_W = (2.0 * SPAN_W * CHORD_S)
constexpr double PLANFORM_AREA_S = (2.0 * SPAN_S * CHORD_S)
constexpr double DYN_PRESS_COEFF_W = (0.5 * RHO_HAT * PLANFORM_AREA_W)
constexpr double DYN_PRESS_COEFF_S = (0.5 * RHO_HAT * PLANFORM_AREA_S)
constexpr double AoS = 70*DEG2RAD
bool is_biplane
bool momentary_button
constexpr double CT_MOTOR = 0.1017
constexpr double MAX_THRUST = 18
constexpr double MIN_THRUST = 0.3
const Eigen::Matrix2d A_filter_roll_ref
const Eigen::Vector2d B_filter_roll_ref = Eigen::Vector2d(1.0, 0)
const Eigen::RowVector2d C_filter_roll_ref = Eigen::RowVector2d(1600.0, 0)
const double D_filter_roll_ref = 0.0
const Eigen::Matrix2d A_filter_pitch_ref
const Eigen::Vector2d B_filter_pitch_ref = Eigen::Vector2d(1.0, 0)
const Eigen::RowVector2d C_filter_pitch_ref = Eigen::RowVector2d(1600.0, 0)
const double D_filter_pitch_ref = 0.0
const Eigen::Matrix2d A_filter_yaw_ref
const Eigen::Vector2d B_filter_yaw_ref = Eigen::Vector2d(1.0, 0)
const Eigen::RowVector2d C_filter_yaw_ref = Eigen::RowVector2d(1600.0, 0)
const double D_filter_yaw_ref = 0.0
const Eigen::Matrix2d A_filter_roll_dot_ref
const Eigen::Vector2d B_filter_roll_dot_ref = Eigen::Vector2d(1.0, 0)
const Eigen::RowVector2d C_filter_roll_dot_ref = Eigen::RowVector2d(0.15*2500.0, 0)
const double D_filter_roll_dot_ref = 0.0
const Eigen::Matrix2d A_filter_pitch_dot_ref
const Eigen::Vector2d B_filter_pitch_dot_ref = Eigen::Vector2d(1.0, 0)
const Eigen::RowVector2d C_filter_pitch_dot_ref = Eigen::RowVector2d(0.15*2500.0, 0)
const double D_filter_pitch_dot_ref = 0.0
const Eigen::Matrix2d A_filter_yaw_dot_ref
const Eigen::Vector2d B_filter_yaw_dot_ref = Eigen::Vector2d(1.0, 0)
const Eigen::RowVector2d C_filter_yaw_dot_ref = Eigen::RowVector2d(0.15*2500.0, 0)
const double D_filter_yaw_dot_ref = 0.0
const Eigen::VectorXd thrust_polynomial_coeff_qrbp
static const Eigen::Vector3d e3_basis = Eigen::Vector3d(0.0, 0.0, 1.0)
const Eigen::Matrix4d mixer_matrix_qrbp
const Eigen::Matrix3d inertia_matrix_q
const Eigen::Matrix3d inertia_matrix_b
const Eigen::Matrix3d R_Jq_Jb
const Eigen::Matrix3d R_Jb_Jq
const Eigen::Quaterniond PITCH_90 = Eigen::Quaterniond(cos(90*DEG2RAD/2.0), 0.0, sin(90*DEG2RAD/2.0), 0.0)
const Eigen::Quaterniond PITCH_90_INV = PITCH_90.inverse()
Function Documentation
compute_aero_coefficients()
AeroCoeff _qrbp_::compute_aero_coefficients (AeroStates states) inline
Inline function to compute the aerodynamic coeffiecients for the QRBP.
Parameters
states
Returns
AeroCoeff
Definition at line 293 of file aero_qrbp.hpp.
References _qrbp_::AeroStates::alpha_lw, _qrbp_::AeroStates::alpha_up, _qrbp_::AeroStates::beta_lt, _qrbp_::AeroStates::beta_rt, _qrbp_::AeroCoeff::Cd_lt, _qrbp_::AeroCoeff::Cd_lw, _qrbp_::AeroCoeff::Cd_rt, _qrbp_::AeroCoeff::Cd_up, _qrbp_::AeroCoeff::Cl_lt, _qrbp_::AeroCoeff::Cl_lw, _qrbp_::AeroCoeff::Cl_rt, _qrbp_::AeroCoeff::Cl_up, _qrbp_::AeroCoeff::Cm_lt, _qrbp_::AeroCoeff::Cm_lw, _qrbp_::AeroCoeff::Cm_rt, _qrbp_::AeroCoeff::Cm_up, compute_cd(), compute_cl(), and compute_cm().
Referenced by _qrbp_::_mrac_omega_::mrac_omega::update(), _qrbp_::_mrac_pid_::mrac_pid::update(), and _qrbp_::_pid_omega_::pid_omega::update().
compute_aero_forces_moments()
AeroDynamicMembers _qrbp_::compute_aero_forces_moments (AeroStates states, AeroCoeff coeff, Eigen::Matrix3d R_J_I, Eigen::Matrix3d R_W_J) inline
Incine function to comput the aerodynamic and moments for the QRBP.
Parameters
states
coeff
R_J_I
R_W_J
Returns
AeroDynamicMembers
Definition at line 325 of file aero_qrbp.hpp.
References _qrbp_::AeroStates::alpha, _qrbp_::AeroStates::beta, _qrbp_::AeroCoeff::Cd_lt, _qrbp_::AeroCoeff::Cd_lw, _qrbp_::AeroCoeff::Cd_rt, _qrbp_::AeroCoeff::Cd_up, CHORD_W, _qrbp_::AeroCoeff::Cl_lt, _qrbp_::AeroCoeff::Cl_lw, _qrbp_::AeroCoeff::Cl_rt, _qrbp_::AeroCoeff::Cl_up, _qrbp_::AeroCoeff::Cm_lt, _qrbp_::AeroCoeff::Cm_lw, _qrbp_::AeroCoeff::Cm_rt, _qrbp_::AeroCoeff::Cm_up, DYN_PRESS_COEFF_S, DYN_PRESS_COEFF_W, _qrbp_::AeroDynamicMembers::F_aero, _qrbp_::AeroDynamicMembers::inner_loop_dynamic_inv, LZ_S, _qrbp_::AeroDynamicMembers::M_aero, _qrbp_::AeroDynamicMembers::outer_loop_dynamic_inv, and _qrbp_::AeroStates::v_norm_sq.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::run(), _qrbp_::_mrac_pid_::mrac_pid::run(), and _qrbp_::_pid_omega_::pid_omega::run().
compute_cd()
double _qrbp_::compute_cd (double angle) inline
Inline function to compute the coefficient of drag for the NACA-0012 airfoil using polynomial approximations.
Parameters
angle
Returns
double
Definition at line 226 of file aero_qrbp.hpp.
References DEG2RAD.
Referenced by compute_aero_coefficients().
compute_cl()
double _qrbp_::compute_cl (double angle) inline
Inline function to compute the coefficient of lift for the NACA-0012 airfoil using polynomial approximations.
Parameters
angle
Returns
double
Definition at line 186 of file aero_qrbp.hpp.
References DEG2RAD.
Referenced by compute_aero_coefficients().
compute_cm()
double _qrbp_::compute_cm (double angle) inline
Inline function to compute the coefficient of aerodynamic moment for the NACA-0012 airfoil using polynomial approximations.
Parameters
angle
Returns
double
Definition at line 257 of file aero_qrbp.hpp.
References DEG2RAD.
Referenced by compute_aero_coefficients().
computeAeroStatesNACA0012Quad()
AeroStates _qrbp_::computeAeroStatesNACA0012Quad (const double u, const double v, const double w, const double w_x, const double w_y, const double w_z) inline
Inline function to compute the Aerodynamic angles for the NACA-0012 airfoil.
Parameters
u
v
w
w_x
w_y
w_z
Returns
AeroStates
Definition at line 128 of file aero_qrbp.hpp.
References _qrbp_::AeroStates::alpha, _qrbp_::AeroStates::alpha_lw, _qrbp_::AeroStates::alpha_up, _qrbp_::AeroStates::beta, _qrbp_::AeroStates::beta_lt, _qrbp_::AeroStates::beta_rt, LX, LY, and _qrbp_::AeroStates::v_norm_sq.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::update(), _qrbp_::_mrac_pid_::mrac_pid::update(), and _qrbp_::_pid_omega_::pid_omega::update().
QRBPswitchFun()
void _qrbp_::QRBPswitchFun (double pitch, bool & is_biplane, bool & mnt_btn) inline
Inline function to compute the switch from Quadcopter mode to Biplane Mode and vice versa.
Parameters
pitch
is_biplane
mnt_btn
Definition at line 300 of file qrbp.hpp.
References AoS, and is_biplane.
Referenced by _qrbp_::_mrac_pid_::mrac_pid::update().
update_states_to_biplane_mode()
void _qrbp_::update_states_to_biplane_mode (const Vector3d eta, const Vector3d omega, Vector3d & eta_b, Vector3d & omega_b) inline
Inline Function to update the biplane mode states - Goes in the inner loop bridge.
Need to modify. This function is written assuming that we are only going in forward flight in a straight line!!!
Parameters
eta
omega
eta_b
omega_b
The state we usually will be in
Definition at line 351 of file qrbp.hpp.
References PIHALF, R_Jq_Jb, and _utilities_::rotationMatrix321LocalToGlobal().
update_states_to_biplane_quaternion_gmk()
void _qrbp_::update_states_to_biplane_quaternion_gmk (const Eigen::Quaterniond q_q, const Vector3d omega, Vector3d & eta_b, Vector3d & omega_b) inline
Code written by Giri Mugundan Kumar to switch states - yet to be debugged.
Parameters
q_q
omega
eta_b
omega_b
Definition at line 438 of file qrbp.hpp.
References PITCH_90_INV, and R_Jq_Jb.
Referenced by _qrbp_::_mrac_pid_::mrac_pid::update().
update_states_to_biplane_quaternions()
void _qrbp_::update_states_to_biplane_quaternions (const Eigen::Quaterniond q_q, const Vector3d omega, Vector3d & eta_b, Vector3d & omega_b) inline
Code from the PX4 Repository to switch states - might need debugging.
Parameters
q_q
omega
eta_b
omega_b
Definition at line 504 of file qrbp.hpp.
References R_Jq_Jb.
Variable Documentation
A_filter_pitch_dot_ref
const Eigen::Matrix2d _qrbp_::A_filter_pitch_dot_ref
Initial value:
= (Eigen::Matrix2d() <<
                                                    -50.0, -2500.0,
                                                      1.0,    0.0
                                                ).finished()
Definition at line 175 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::compute_u1_eta_d(), _qrbp_::_mrac_pid_::mrac_pid::compute_u1_eta_d(), _qrbp_::_pid_::pid::compute_u1_eta_d(), and _qrbp_::_pid_omega_::pid_omega::compute_u1_eta_d().
A_filter_pitch_ref
const Eigen::Matrix2d _qrbp_::A_filter_pitch_ref
Initial value:
= (Eigen::Matrix2d() <<
                                                    -72.0, -1600.0,
                                                      1.0,    0.0
                                                ).finished()
Definition at line 127 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::compute_u1_eta_d(), _qrbp_::_mrac_pid_::mrac_pid::compute_u1_eta_d(), _qrbp_::_pid_::pid::compute_u1_eta_d(), and _qrbp_::_pid_omega_::pid_omega::compute_u1_eta_d().
A_filter_roll_dot_ref
const Eigen::Matrix2d _qrbp_::A_filter_roll_dot_ref
Initial value:
= (Eigen::Matrix2d() <<
                                                    -50.0, -2500.0,
                                                      1.0,    0.0
                                                ).finished()
Definition at line 159 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::compute_u1_eta_d(), _qrbp_::_mrac_pid_::mrac_pid::compute_u1_eta_d(), _qrbp_::_pid_::pid::compute_u1_eta_d(), and _qrbp_::_pid_omega_::pid_omega::compute_u1_eta_d().
A_filter_roll_ref
const Eigen::Matrix2d _qrbp_::A_filter_roll_ref
Initial value:
= (Eigen::Matrix2d() <<
                                                    -72.0, -1600.0,
                                                      1.0,    0.0
                                                ).finished()
Definition at line 111 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::compute_u1_eta_d(), _qrbp_::_mrac_pid_::mrac_pid::compute_u1_eta_d(), _qrbp_::_pid_::pid::compute_u1_eta_d(), and _qrbp_::_pid_omega_::pid_omega::compute_u1_eta_d().
A_filter_yaw_dot_ref
const Eigen::Matrix2d _qrbp_::A_filter_yaw_dot_ref
Initial value:
= (Eigen::Matrix2d() <<
                                                    -50.0, -2500.0,
                                                      1.0,    0.0
                                                ).finished()
Definition at line 191 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::compute_u1_eta_d(), _qrbp_::_mrac_pid_::mrac_pid::compute_u1_eta_d(), and _qrbp_::_pid_omega_::pid_omega::compute_u1_eta_d().
A_filter_yaw_ref
const Eigen::Matrix2d _qrbp_::A_filter_yaw_ref
Initial value:
= (Eigen::Matrix2d() <<
                                                    -72.0, -1600.0,
                                                      1.0,    0.0
                                                ).finished()
Definition at line 143 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_pid_::mrac_pid::compute_u1_eta_d().
AoS
constexpr double _qrbp_::AoS = 70*DEG2RAD inline constexpr
Definition at line 95 of file qrbp.hpp.
Referenced by QRBPswitchFun().
B_filter_pitch_dot_ref
const Eigen::Vector2d _qrbp_::B_filter_pitch_dot_ref = Eigen::Vector2d(1.0, 0)
Definition at line 181 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::compute_u1_eta_d(), _qrbp_::_mrac_pid_::mrac_pid::compute_u1_eta_d(), _qrbp_::_pid_::pid::compute_u1_eta_d(), and _qrbp_::_pid_omega_::pid_omega::compute_u1_eta_d().
B_filter_pitch_ref
const Eigen::Vector2d _qrbp_::B_filter_pitch_ref = Eigen::Vector2d(1.0, 0)
Definition at line 133 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::compute_u1_eta_d(), _qrbp_::_mrac_pid_::mrac_pid::compute_u1_eta_d(), _qrbp_::_pid_::pid::compute_u1_eta_d(), and _qrbp_::_pid_omega_::pid_omega::compute_u1_eta_d().
B_filter_roll_dot_ref
const Eigen::Vector2d _qrbp_::B_filter_roll_dot_ref = Eigen::Vector2d(1.0, 0)
Definition at line 165 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::compute_u1_eta_d(), _qrbp_::_mrac_pid_::mrac_pid::compute_u1_eta_d(), _qrbp_::_pid_::pid::compute_u1_eta_d(), and _qrbp_::_pid_omega_::pid_omega::compute_u1_eta_d().
B_filter_roll_ref
const Eigen::Vector2d _qrbp_::B_filter_roll_ref = Eigen::Vector2d(1.0, 0)
Definition at line 117 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::compute_u1_eta_d(), _qrbp_::_mrac_pid_::mrac_pid::compute_u1_eta_d(), _qrbp_::_pid_::pid::compute_u1_eta_d(), and _qrbp_::_pid_omega_::pid_omega::compute_u1_eta_d().
B_filter_yaw_dot_ref
const Eigen::Vector2d _qrbp_::B_filter_yaw_dot_ref = Eigen::Vector2d(1.0, 0)
Definition at line 197 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::compute_u1_eta_d(), _qrbp_::_mrac_pid_::mrac_pid::compute_u1_eta_d(), and _qrbp_::_pid_omega_::pid_omega::compute_u1_eta_d().
B_filter_yaw_ref
const Eigen::Vector2d _qrbp_::B_filter_yaw_ref = Eigen::Vector2d(1.0, 0)
Definition at line 149 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_pid_::mrac_pid::compute_u1_eta_d().
C_filter_pitch_dot_ref
const Eigen::RowVector2d _qrbp_::C_filter_pitch_dot_ref = Eigen::RowVector2d(0.15*2500.0, 0)
Definition at line 184 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::compute_u1_eta_d(), _qrbp_::_mrac_pid_::mrac_pid::compute_u1_eta_d(), _qrbp_::_pid_::pid::compute_u1_eta_d(), and _qrbp_::_pid_omega_::pid_omega::compute_u1_eta_d().
C_filter_pitch_ref
const Eigen::RowVector2d _qrbp_::C_filter_pitch_ref = Eigen::RowVector2d(1600.0, 0)
Definition at line 136 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::compute_u1_eta_d(), _qrbp_::_mrac_pid_::mrac_pid::compute_u1_eta_d(), _qrbp_::_pid_::pid::compute_u1_eta_d(), and _qrbp_::_pid_omega_::pid_omega::compute_u1_eta_d().
C_filter_roll_dot_ref
const Eigen::RowVector2d _qrbp_::C_filter_roll_dot_ref = Eigen::RowVector2d(0.15*2500.0, 0)
Definition at line 168 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::compute_u1_eta_d(), _qrbp_::_mrac_pid_::mrac_pid::compute_u1_eta_d(), _qrbp_::_pid_::pid::compute_u1_eta_d(), and _qrbp_::_pid_omega_::pid_omega::compute_u1_eta_d().
C_filter_roll_ref
const Eigen::RowVector2d _qrbp_::C_filter_roll_ref = Eigen::RowVector2d(1600.0, 0)
Definition at line 120 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::compute_u1_eta_d(), _qrbp_::_mrac_pid_::mrac_pid::compute_u1_eta_d(), _qrbp_::_pid_::pid::compute_u1_eta_d(), and _qrbp_::_pid_omega_::pid_omega::compute_u1_eta_d().
C_filter_yaw_dot_ref
const Eigen::RowVector2d _qrbp_::C_filter_yaw_dot_ref = Eigen::RowVector2d(0.15*2500.0, 0)
Definition at line 200 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::compute_u1_eta_d(), _qrbp_::_mrac_pid_::mrac_pid::compute_u1_eta_d(), and _qrbp_::_pid_omega_::pid_omega::compute_u1_eta_d().
C_filter_yaw_ref
const Eigen::RowVector2d _qrbp_::C_filter_yaw_ref = Eigen::RowVector2d(1600.0, 0)
Definition at line 152 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_pid_::mrac_pid::compute_u1_eta_d().
CHORD_S
constexpr double _qrbp_::CHORD_S = 0.02 inline constexpr
Definition at line 86 of file qrbp.hpp.
CHORD_W
constexpr double _qrbp_::CHORD_W = 0.12 inline constexpr
Definition at line 84 of file qrbp.hpp.
Referenced by compute_aero_forces_moments().
CT_MOTOR
constexpr double _qrbp_::CT_MOTOR = 0.1017 inline constexpr
Definition at line 104 of file qrbp.hpp.
D_filter_pitch_dot_ref
const double _qrbp_::D_filter_pitch_dot_ref = 0.0
Definition at line 187 of file qrbp.hpp.
D_filter_pitch_ref
const double _qrbp_::D_filter_pitch_ref = 0.0
Definition at line 139 of file qrbp.hpp.
D_filter_roll_dot_ref
const double _qrbp_::D_filter_roll_dot_ref = 0.0
Definition at line 171 of file qrbp.hpp.
D_filter_roll_ref
const double _qrbp_::D_filter_roll_ref = 0.0
Definition at line 123 of file qrbp.hpp.
D_filter_yaw_dot_ref
const double _qrbp_::D_filter_yaw_dot_ref = 0.0
Definition at line 203 of file qrbp.hpp.
D_filter_yaw_ref
const double _qrbp_::D_filter_yaw_ref = 0.0
Definition at line 155 of file qrbp.hpp.
DEG2RAD
constexpr double _qrbp_::DEG2RAD = (PI/180) inline constexpr
Definition at line 74 of file qrbp.hpp.
Referenced by compute_cd(), compute_cl(), and compute_cm().
DYN_PRESS_COEFF_S
constexpr double _qrbp_::DYN_PRESS_COEFF_S = (0.5 * RHO_HAT * PLANFORM_AREA_S) inline constexpr
Definition at line 92 of file qrbp.hpp.
Referenced by compute_aero_forces_moments().
DYN_PRESS_COEFF_W
constexpr double _qrbp_::DYN_PRESS_COEFF_W = (0.5 * RHO_HAT * PLANFORM_AREA_W) inline constexpr
Definition at line 91 of file qrbp.hpp.
Referenced by compute_aero_forces_moments().
e3_basis
const Eigen::Vector3d _qrbp_::e3_basis = Eigen::Vector3d(0.0, 0.0, 1.0) inline static
Definition at line 220 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::compute_translational_control_in_I(), _qrbp_::_mrac_pid_::mrac_pid::compute_translational_control_in_I(), _qrbp_::_pid_::pid::compute_translational_control_in_I(), and _qrbp_::_pid_omega_::pid_omega::compute_translational_control_in_I().
G
constexpr double _qrbp_::G = 9.81 inline constexpr
Definition at line 70 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::compute_translational_control_in_I(), _qrbp_::_mrac_pid_::mrac_pid::compute_translational_control_in_I(), _qrbp_::_pid_::pid::compute_translational_control_in_I(), and _qrbp_::_pid_omega_::pid_omega::compute_translational_control_in_I().
inertia_matrix_b
const Eigen::Matrix3d _qrbp_::inertia_matrix_b
Initial value:
= (Eigen::Matrix3d() <<
                                                 0.03676930,  0.00000339, -0.00005560,
                                                 0.00000339,  0.01964797, -0.00000662,
                                                -0.00005560, -0.00000662,  0.03093953
                                             ).finished()
Definition at line 270 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_pid_::mrac_pid::update().
inertia_matrix_q
const Eigen::Matrix3d _qrbp_::inertia_matrix_q
Initial value:
= (Eigen::Matrix3d() <<
                                                 0.03170556, -0.00000810, 0.00102548,
                                                -0.00000810,  0.02125186,-0.00000107,
                                                 0.00102548, -0.00000107, 0.03765785
                                             ).finished()
Definition at line 261 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::compute_rotational_control(), _qrbp_::_pid_::pid::compute_rotational_control(), _qrbp_::_pid_omega_::pid_omega::compute_rotational_control(), _qrbp_::_mrac_pid_::mrac_pid::init(), and _qrbp_::_mrac_pid_::mrac_pid::update().
is_biplane
bool _qrbp_::is_biplane inline
Definition at line 98 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_pid_::mrac_pid::compute_innner_loop_regressor(), _qrbp_::_mrac_pid_::mrac_pid::compute_rotational_control(), _qrbp_::_mrac_pid_::mrac_pid::compute_u1_eta_d(), _qrbp_::_mrac_pid_::mrac_pid::init(), _qrbp_::_pid_::pid::init(), _qrbp_::_mrac_pid_::mrac_pid_logger::logLogData(), QRBPswitchFun(), and _qrbp_::_mrac_pid_::mrac_pid::update().
LX
constexpr double _qrbp_::LX = 0.097509 inline constexpr
Definition at line 80 of file qrbp.hpp.
Referenced by computeAeroStatesNACA0012Quad().
LY
constexpr double _qrbp_::LY = 0.110688 inline constexpr
Definition at line 81 of file qrbp.hpp.
Referenced by computeAeroStatesNACA0012Quad().
LZ_S
constexpr double _qrbp_::LZ_S = 0.038779 inline constexpr
Definition at line 82 of file qrbp.hpp.
Referenced by compute_aero_forces_moments().
MASS
constexpr double _qrbp_::MASS = 2.04192755 inline constexpr
Definition at line 79 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::compute_translational_control_in_I(), _qrbp_::_mrac_pid_::mrac_pid::compute_translational_control_in_I(), _qrbp_::_pid_::pid::compute_translational_control_in_I(), _qrbp_::_pid_omega_::pid_omega::compute_translational_control_in_I(), _qrbp_::_mrac_omega_::mrac_omega::init(), and _qrbp_::_mrac_pid_::mrac_pid::init().
MAX_THRUST
constexpr double _qrbp_::MAX_THRUST = 18 inline constexpr
Definition at line 105 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::compute_normalized_thrusts(), _qrbp_::_mrac_pid_::mrac_pid::compute_normalized_thrusts(), _qrbp_::_pid_::pid::compute_normalized_thrusts(), and _qrbp_::_pid_omega_::pid_omega::compute_normalized_thrusts().
MIN_THRUST
constexpr double _qrbp_::MIN_THRUST = 0.3 inline constexpr
Definition at line 106 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::compute_normalized_thrusts(), _qrbp_::_mrac_pid_::mrac_pid::compute_normalized_thrusts(), _qrbp_::_pid_::pid::compute_normalized_thrusts(), and _qrbp_::_pid_omega_::pid_omega::compute_normalized_thrusts().
mixer_matrix_qrbp
const Eigen::Matrix4d _qrbp_::mixer_matrix_qrbp
Initial value:
= []() {
        Eigen::Matrix4d mat;
        mat(0, 0) =  1.0 / 4.0;
        mat(0, 1) = -1.0 / (4.0 * LY);
        mat(0, 2) =  1.0 / (4.0 * LX);
        mat(0, 3) =  1.0 / (4.0 * CT_MOTOR);
        mat(1, 0) =  1.0 / 4.0;
        mat(1, 1) =  1.0 / (4.0 * LY);
        mat(1, 2) = -1.0 / (4.0 * LX);
        mat(1, 3) =  1.0 / (4.0 * CT_MOTOR);
        mat(2, 0) =  1.0 / 4.0;
        mat(2, 1) =  1.0 / (4.0 * LY);
        mat(2, 2) =  1.0 / (4.0 * LX);
        mat(2, 3) = -1.0 / (4.0 * CT_MOTOR);
        mat(3, 0) =  1.0 / 4.0;
        mat(3, 1) = -1.0 / (4.0 * LY);
        mat(3, 2) = -1.0 / (4.0 * LX);
        mat(3, 3) = -1.0 / (4.0 * CT_MOTOR);
        return mat;
    }()
Definition at line 229 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::compute_normalized_thrusts(), _qrbp_::_mrac_pid_::mrac_pid::compute_normalized_thrusts(), _qrbp_::_pid_::pid::compute_normalized_thrusts(), and _qrbp_::_pid_omega_::pid_omega::compute_normalized_thrusts().
momentary_button
bool _qrbp_::momentary_button inline
Definition at line 99 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_pid_::mrac_pid::init(), _qrbp_::_pid_::pid::init(), _qrbp_::_mrac_pid_::mrac_pid_logger::logLogData(), and _qrbp_::_mrac_pid_::mrac_pid::update().
PI
constexpr double _qrbp_::PI = 3.1415 inline constexpr
Definition at line 72 of file qrbp.hpp.
PIHALF
constexpr double _qrbp_::PIHALF = (PI/2) inline constexpr
Definition at line 73 of file qrbp.hpp.
Referenced by update_states_to_biplane_mode().
PITCH_90
const Eigen::Quaterniond _qrbp_::PITCH_90 = Eigen::Quaterniond(cos(90*DEG2RAD/2.0), 0.0, sin(90*DEG2RAD/2.0), 0.0)
Definition at line 289 of file qrbp.hpp.
PITCH_90_INV
const Eigen::Quaterniond _qrbp_::PITCH_90_INV = PITCH_90.inverse()
Definition at line 290 of file qrbp.hpp.
Referenced by update_states_to_biplane_quaternion_gmk().
PLANFORM_AREA_S
constexpr double _qrbp_::PLANFORM_AREA_S = (2.0 * SPAN_S * CHORD_S) inline constexpr
Definition at line 88 of file qrbp.hpp.
PLANFORM_AREA_W
constexpr double _qrbp_::PLANFORM_AREA_W = (2.0 * SPAN_W * CHORD_S) inline constexpr
Definition at line 87 of file qrbp.hpp.
R_Jb_Jq
const Eigen::Matrix3d _qrbp_::R_Jb_Jq
Initial value:
= (Eigen::Matrix3d() <<
                                        0.0, 0.0, -1.0,
                                        0.0, 1.0,  0.0,
                                        1.0, 0.0,  0.0).finished()
Definition at line 283 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_pid_::mrac_pid::compute_rotational_control().
R_Jq_Jb
const Eigen::Matrix3d _qrbp_::R_Jq_Jb
Initial value:
= (Eigen::Matrix3d() <<
                                        0.0, 0.0, 1.0,
                                        0.0, 1.0, 0.0,
                                       -1.0, 0.0, 0.0).finished()
Definition at line 277 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_pid_::mrac_pid::compute_rotational_control(), update_states_to_biplane_mode(), update_states_to_biplane_quaternion_gmk(), and update_states_to_biplane_quaternions().
RAD2DEG
constexpr double _qrbp_::RAD2DEG = (180/PI) inline constexpr
Definition at line 75 of file qrbp.hpp.
RHO_HAT
constexpr double _qrbp_::RHO_HAT = 1.225 inline constexpr
Definition at line 71 of file qrbp.hpp.
SPAN_S
constexpr double _qrbp_::SPAN_S = 0.175 inline constexpr
Definition at line 85 of file qrbp.hpp.
SPAN_W
constexpr double _qrbp_::SPAN_W = 0.50 inline constexpr
Definition at line 83 of file qrbp.hpp.
SQRT2_OVER_2
constexpr double _qrbp_::SQRT2_OVER_2 = 0.7071067 inline constexpr
Definition at line 76 of file qrbp.hpp.
thrust_polynomial_coeff_qrbp
const Eigen::VectorXd _qrbp_::thrust_polynomial_coeff_qrbp
Initial value:
= (Eigen::VectorXd(8) <<
                                                            0.000000030316084940690649384320061064321,
                                                           -0.000001814468657920738862350290739045,
                                                            0.000042434512948142268497307011410058,
                                                           -0.00050487431926448940282259325584846,
                                                            0.0035249290604740459061094970394379,
                                                           -0.017552333963129614080589391278409,
                                                            0.1149654034760465154407782506496,
                                                            0.011001286689392602777259888569006
                                                        ).finished()
Definition at line 208 of file qrbp.hpp.
Referenced by _qrbp_::_mrac_omega_::mrac_omega::compute_normalized_thrusts(), _qrbp_::_mrac_pid_::mrac_pid::compute_normalized_thrusts(), _qrbp_::_pid_::pid::compute_normalized_thrusts(), and _qrbp_::_pid_omega_::pid_omega::compute_normalized_thrusts().